### ISSUE TITLE
Special Character Filters

### ISSUE THREAD

**Issue by ShammyLevva** [ShammyLevva/FTAnalyzer#1]
Issue copied from Codeplex

When loading a Gedcom I am getting a message that says 'You might get less errors if you turn on the option to 'Use Special Character Filters When Loading' from the Tools Options menu.

However when I go to the Options this selection is grayed out with a note that 'these options are not currently available.' How do I get them available?

**Comment by ShammyLevva** [comment]
I'll have a look from memory there was an issue with different character sets that was never properly resolved so I may have turned off the option to filter (as it wasn't doing anything) but forgot to turn off the message. I'll need to look at the code again.

Note you certainly shouldn't have to tinker with config files it's disabled probably because it doesn't do anything. BTW if you ONLY have a .exe in your folder then you are missing a LOT of files. If you are using the downloadable zip file then the whole of the zipfile contents should be exported keeping the directory structures intact otherwise issues with databases, configuration files, maps, and various parts of the program will simply fail to work. In fact I'm surprised it worked with only the .exe.

**Comment by fire-eggs** [comment]
>BTW if you ONLY have a .exe in your folder then you are missing a LOT of files.
In separate email with the user I confirmed that the "single EXE" referred to the "Click Once Installer". 

>Note you certainly shouldn't have to tinker with config files it's disabled probably because it doesn't do >anything.

The setting currently has the impact of checking for embedded CRs. See GedcomToXml.cs, Load(path,encoding), the use of Properties.FileHandling.Default.LoadWithFilters.  If the setting is on, then CheckSpuriousOD() is invoked.

The user in question had a problem with embedded LF. I have seen this issue myself with files where NOTE records contain email text with embedded LFs.

**Comment by ShammyLevva** [comment]
Refactored for v6.1.3 and enabled hopefully this fixes the issue. I'll leave it open until confirmed fix I don't have a test file that shows the issue.

**Comment by fire-eggs** [comment]
The attached file "should" illustrate the issue. The file is CR-LF terminated; at lines 416 and 489, I've introduced embedded LFs. Line 416 corresponds to one of the original reporter's symptoms: a "3 PAGE" tag. Line 489 is another variant.  E.g. "3 PAGE Foo bar<CR><LF>" was transformed to "3 PAGE Foo <LF> bar<CR><LF>".

[FTA_Issue1.zip](https://github.com/ShammyLevva/FTAnalyzer/files/1711876/FTA_Issue1.zip)

**Comment by ShammyLevva** [comment]
That's 6 months since this was opened I believe this is now fixed as no further errors have been brought to my attention.
