### ISSUE TITLE
Multiple entries in 'Found in Census' report - should they exist?

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#101]
I can understand that when individuals are NOT found on a Census, you duplicate individuals across family groups to assist in locating where they might be.

However, for found on a Census reports, I think there should only be duplicate (individual) entries if you have multiple (complete and unique) references for a given Census??  Perhaps for the odd time they are listed on both their parents form and elsewhere (eg with a neighbour/relative/spouse).  There wouldn’t be many of these, so duplicates should be close to nil.

**Comment by ShammyLevva** [comment]
No sorry they are based on the same Census Family and the program has NO way of telling what the data in the census is. I won't be making this change.

**Comment by bmurcutt** [comment]
No prob.  Thanks.
