### ISSUE TITLE
[BUG] Lost Cousin load failures - 1 - Invalid Surname

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#103]
Version 7.3.7.1

The following scenario failed to load:

England & Wales Census 1881 - Failed to add I2328: Mary Ann [-------]   b.ABT 1840, Piece: 4714, Folio: 71, Page: 1.

Manually trying to load on LC gave an error response of: **Surname includes invalid characters**

Recommendation: include a check to confirm the surname meets LC checking rules

**Comment by ShammyLevva** [comment]
Yup good idea thanks.

**Comment by bmurcutt** [comment]
7.3.7.3 - noted that you are picking up a married name now (presumably a related issue to this one!).  Do you interrogate the marriage details to determine the appropriate married name to use (in the case of multiple marriages existing?

I have noted one case where there was no husband (ie mother appeared on a census but I have no father details), so she still appears on the 'Potential to upload to LC' list with surname [--- ? ---]

Can't test the actual upload to see how things are handled at that point as LC appears to be unavailable currently.  Will try later.

**Comment by ShammyLevva** [comment]
However the surname has ALWAYS been used for this as it's used elsewhere in the various census reports. What the issue appears to be is down to the invalid characters and how I'm currently filtering. The referenced issue is a result of how I tried to handle it on iteration number 1.

**Comment by ShammyLevva** [comment]
This should be fixed in v7.3.7.4

**Comment by bmurcutt** [comment]
Resolved.  A side issue of now (7.3.7.4) loading a surname of '------' to LC has been raised in Issue #117
