### ISSUE TITLE
[BUG] Lost Cousin load failures - 2 - Nickname not accepted

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#104]
Version 7.3.7.1

The following scenario failed to load:

England & Wales Census 1841 - Failed to add I6060: Frances "Fanny" Tremelling Blewett b.ABT 1807, Piece: 142, Book: 10, Folio:   51, Page: 1.

In Legacy, it is a recommended practice to identify common/nicknames using quoted names in the name field.

For example:  Given: Frances "Fanny" Tremelling    Surname: Blewett

Manually trying to load on LC gave an error response of: **Forename contains invalid characters**

It is recommended to either:
 - remove quoted given names from the name field before trying to load to LC
 - include any quoted given names in the 'middle names or initials' field, as it does not have the same limitation (and works through the LC manual process)
 - detect the existence of invalid characters in the individuals given name and not accept record to load (not preferred ;) )

**Comment by ShammyLevva** [comment]
Ah ok then Legacy is going against the standard convention which is to use an AKA fact type (Also Known As). 

I can look at this stripping of quotes from forename or as you say move it to middle name. Since its fairly unlikely that this AKA name would appear on the census I suspect the best is to drop the contents in quotes.

**Comment by bmurcutt** [comment]
Legacy does have an AKA option as well.

Using the quoted name (as I understand it) allows (in Legacy) for the common/nickname to be used in reports It is able to generate.

But yes, it is a non-standard use.

You will find that the nicknames would be commonly used in a Census (eg Betty instead of Elizabeth).  One thing FTA is doing is using the 'formal' name always, not the name used on the Census form or transcript.  Depending on the Census (and LC rules) this might cause issues matching a manually loaded record with an FTA loaded one.

Not much you (FTA) can do about it though.  Maybe something for Peter to consider if it causes issues on his side!

Brian

**Comment by ShammyLevva** [comment]
Ok option to strip anything it finds in quotes added. Needs testing.

**Comment by bmurcutt** [comment]
7.3.7.3

Quoted name still appears in 'potential to upload to LC' file.

Can't test the actual upload process as LC is currently down.  Will try later ...

**Comment by ShammyLevva** [comment]
Note Peter has said the backup happens at 1am UK time for about 10-15 mins.

**Comment by ShammyLevva** [comment]
This should be fixed in v7.3.7.4

**Comment by bmurcutt** [comment]
It loaded successfully - however:

It should (methinks) load as:

Surname:  Blewett
Forename: Frances
Middle names: "Fanny" Tremelling

It loaded (ftanalyzer LC test) as:
Surname:  Blewett
Forename: Frances
Middle names: FannyTremelling (note - no space between words)

In the context I raised this, "Fanny" is a common or nickname entered according to how Legacy Family Tree recommend (rather than an AKA, which they use more for alternate formal names).  LC does not allow quotes to be used in the Forename (but allow it in the Middle Name field).

Alternatively, Middle names could be just 'Tremelling', or possibly 'Fanny Tremelling' (with a space).  Probably moot whichever way as LC prefer the actual census reference name.  Probably whatever is easiest to fix/implement will suffice :)

**Comment by ShammyLevva** [comment]
Fixed in v7.3.7.5

**Comment by bmurcutt** [comment]
Worked OK.

I did get an error the first time I tried to load the test file.  

I deleted the previous load from LC, and renamed the geocodes file out of the way.

Got an SQL error dialog - but I lost the snap.  I did copy the 'detail' info.  I retried (deleting the record again and deleting the geocode file), but it worked OK.

Also, the load log didn't continue after hitting 'continue' on the dialog message.

As I haven't replicated it (yet), I'm not worried about it.  But if it makes sense to you, fix away :)

Here's the 'detail':

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such table: LostCousins
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at FTAnalyzer.Utilities.DatabaseHelper.LostCousinsExists(CensusIndividual ind)
   at FTAnalyzer.Exports.ExportToLostCousins.ProcessList(List`1 individuals, IProgress`1 outputText)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FTAnalyzer.MainForm.<BtnUpdateLostCousinsWebsite_Click>d__123.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
FTAnalyzer
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/FTAnalyzer.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
log4net
    Assembly Version: 2.0.8.0
    Win32 Version: 2.0.8.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
GeoAPI
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/GeoAPI.DLL
----------------------------------------
ProjNet
    Assembly Version: 1.3.0.3
    Win32 Version: 1.3.0.4
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/ProjNet.DLL
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.109.0
    Win32 Version: 1.0.109.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Printing.DataGridViewPrint
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/Printing.DataGridViewPrint.DLL
----------------------------------------
SharpMap
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/SharpMap.DLL
----------------------------------------
GoogleAnalyticsTracker.Core
    Assembly Version: 4.6.8.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/GoogleAnalyticsTracker.Core.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.8.14.0
    Win32 Version: 1.8.14
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/HtmlAgilityPack.DLL
----------------------------------------
GoogleAnalyticsTracker.Simple
    Assembly Version: 4.6.8.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///C:/Users/BrianM/AppData/Local/Apps/2.0/9ODYCOPV.1P7/V28J6Z9J.H8O/ftan..tion_c7ce9728f49d2c1c_0007.0003_5793428e62b06605/GoogleAnalyticsTracker.Simple.DLL
----------------------------------------
System.Threading.Tasks
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Threading.Tasks/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.Tasks.dll
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll
----------------------------------------
System.Globalization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Reflection
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.dll
----------------------------------------
System.Reflection.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Reflection.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Reflection.Extensions.dll
----------------------------------------
System.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Text.Encoding
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Text.Encoding/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Text.Encoding.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3282.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by ShammyLevva** [comment]
The detail says it couldn’t find the lost cousins table.
