### ISSUE TITLE
[BUG] Application does not start maximised

### ISSUE THREAD

**Issue by myfta** [ShammyLevva/FTAnalyzer#106]
Version 7.3.7.1
When the application starts it does not start fullscreen but partially under the toolbar (I have my toolbar at the top of the screen!) So each time I have to move the toolbar to the side, expand the application to fullscreen and move the toolbar back.

The application properties does not include an option/tab to change the shortcut behaviour.

**Comment by ShammyLevva** [comment]
If you move the window whilst it's not maximised it will remember the location and start from there each time. I'll investigate how it can start maximised shouldn't be difficult. Thanks for report.

**Comment by myfta** [comment]
Despite moving, exiting the application and restarting it always opens in
the very top left of the screen.

**Comment by ShammyLevva** [comment]
Extremely odd I just tested on my PC (Windows 10 1809) and it works correctly. It should be saving temp locations to it's registry sub-key, then loading them on restart.

The values get stored in Computer\HKEY_CURRENT_USER\Software\FTAnalyzer\FTAnalyzer\1.0.0.0

I've added support for remembering maximisied status too. However if something is blocking the App from writing to it's own registry values then yes various things may not work correctly.

**Comment by myfta** [comment]
I have two similar machines that I have tried it on and it behaves the same
way on both. There are many other settings for FTA in your registry
location but not one that appears to relate to window position.

Graham

**Comment by ShammyLevva** [comment]
Ok very curious. Yes there is a default but it SHOULD be overridden by the registry values. I may have to create a test version that writes out some data to say what it's doing. Would you be ok trialing a test version?

Basically I'd add in a good few extra lines around the code that does the positioning that interrupted the program periodically to confirm values and attempt to determine at what point it reverted to the defaults. This would likely not be a terribly usable version as it would need to alert you to where it was at different stages but it should help narrow down the error. I'd release it as a test on my public dropbox folder and send you a link. 

NB. I'm off to visit family in 4 hours then flying to Spain in early hours of tomorrow morning, and it's my Mums birthday on Wednesday. So I'll be out of contact for a few days.

**Comment by ShammyLevva** [comment]
Added extra code to move window down if it detects taskbar at top. From what I read this may fix issue of topbar positioning.

I've got a beta to test at https://www.dropbox.com/s/qzrsv2ce30ensif/FTAnalyzer%20v7.3.7.4-beta.zip?dl=0 if you can let me know how that works. 

NB. this version tried a different approach from debugging instead it checks the taskbar position and forces windows from hiding under the bar. If that still doesn't work I'll need to try the debug option.

**Comment by myfta** [comment]
OK, this is definitely better for me. It certainly detects the taskbar when
it is at the top of the screen now. So this solves my problem.

I did try and break it though! If you move your taskbar to the left side it
does slip underneath when you open FTA, but that is less a problem as you
have access to the top of the frame for FTA.

Thanks,

Graham

**Comment by ShammyLevva** [comment]
Ok thanks I’ll close this out and the update will appear officially soon.
