### ISSUE TITLE
[BUG] Interpretation of Question Mark in Occupation Fact

### ISSUE THREAD

**Issue by MRG37** [ShammyLevva/FTAnalyzer#108]
**Version 7.3.7.1**

**Describe the bug**
The importation of a GEDCOM file does not correctly interpret the use of a question mark within an Occupation fact.

**To Reproduce**
1. Start with the text 'OCCU Fireman?' in a GEDCOM file
2. Click on 'File>Open GEDCOM file...'
3. Click on 'Main Lists>Occupations'
4. See that Occupation is incorrectly listed as 'Fireman-'

**Expected behavior**
1. Start with the text 'OCCU Fireman?' in a GEDCOM file
2. Click on 'File>Open GEDCOM file...'
3. Click on 'Main Lists>Occupations'
4. See that Occupation is correctly listed as 'Fireman?'

![fireman](https://user-images.githubusercontent.com/47303651/52181398-3ca7bd80-27e9-11e9-8fe6-18a396d9e974.PNG)
![fireman-](https://user-images.githubusercontent.com/47303651/52181402-429d9e80-27e9-11e9-8eb6-c2f47c4d79cf.PNG)

**Comment by ShammyLevva** [comment]
This is a tricky one. The general code for replacing notes to fix census refs uses the same conversion. 

I've noted the same issue with surnames/forenames with ?'s. I think I may have changed a filter when dealing with census references (which I've done a LOT of recently) and it's applied where it shouldn't do.

**Comment by ShammyLevva** [comment]
Ok found it at some point when fixing diacritics it changed a diacritic character replacement to a dash line. It appears that it didn't recognise the diacritic as a valid character and changed it to a ? thus ?'s became dashes instead of the diacritic character becoming a -.
