### ISSUE TITLE
[BUG] Interpretation of Ordinal Numbers in Occupation Fact

### ISSUE THREAD

**Issue by MRG37** [ShammyLevva/FTAnalyzer#109]
**Version 7.3.7.1**

**Describe the bug**
The importation of a GEDCOM file does not correctly interpret the use of lower case ordinals within an Occupation fact.

**To Reproduce**
Start with the text 'OCCU Instructor 13th Battalion Railway Volunteers' in a GEDCOM file
Click on 'File>Open GEDCOM file...'
Click on 'Main Lists>Occupations'
See that Occupation is incorrectly listed as 'OCCU Instructor 13Th Battalion Railway Volunteers'

**Expected behavior**
Start with the text 'OCCU Instructor 13th Battalion Railway Volunteers' in a GEDCOM file
Click on 'File>Open GEDCOM file...'
Click on 'Main Lists>Occupations'
See that Occupation is correctly listed as 'OCCU Instructor 13th Battalion Railway Volunteers'

![image](https://user-images.githubusercontent.com/47303651/52181480-37973e00-27ea-11e9-8745-2b9070582378.png)

![image](https://user-images.githubusercontent.com/47303651/52181507-b42a1c80-27ea-11e9-9b3d-665e0e6f8772.png)

**Comment by ShammyLevva** [comment]
Thanks I thought I'd caught all of these instances. Clearly not.

**Comment by ShammyLevva** [comment]
Fixed.

I'd catered for 1st, 21st, 31st etc but not 11th. Same for 2nd, 22nd, 32nd not 12th and 3rd, 23rd, 33rd but not 13th.
