### ISSUE TITLE
[BUG] startIndex error on LC upload

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#113]
7.3.7.3

Getting the following error when uploading to LC:

Problem accessing Lost Cousins Website to send record below.  Error message is: startIndex must be less than length of string. Parameter name: startIndex
Record 2 of 50: England & Wales Census 1881 - Failed to add I2328: Mary Ann [--- ? ---] b.ABT 1840, Piece: 4714, Folio: 71, Page: 1.

Note that:
- Record 1 failed to load because of undetermined age error (b. UNKNOWN) - should these types of errors be detected before creating the LC update file?
- All records that did not get such errors (so presumably got to actually try to load!) got the startIndex error.
- In the 'potential to upload' file, the Census Name for the failed record above appears as: Mary Ann Hey  ([--- ? ---]) - so you appear to be losing the married/census name prior to the actual upload (or the error message isn't reporting it properly) - related to issue #103?

![image](https://user-images.githubusercontent.com/47096037/52249822-26187800-2949-11e9-9226-08aa8be40044.png)

**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
Thinking about it the issue here is that it’s stripped everything and left nothing in surname that’s alphabetic so the starting point character 1 is greater than the length of the string 0. 

What I’ll need to do is add a Lost Cousins forename and lost cousins surname field so I can check if they are empty before choosing them as candidate uploads. As you say they should just be ignored and not even sent to LostCousins to fail.

**Comment by Onceageordie** [comment]
I also have this error, but with "clean" data -

Started Processing Lost Cousins entries.

Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 1 of 29: England & Wales Census 1881 - Failed to add I01991: William Kenny b.30 AUG 1877, Piece: 4956, Folio: 112, Page: 5.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 2 of 29: England & Wales Census 1881 - Failed to add I02438: Sarah Thomasina Stewart b.20 JUL 1876, Piece: 5037, Folio: 71, Page: 13.
Record 3 of 29: England & Wales Census 1881 - Already Present I03329: William Thomas Scott b.DEC 1865, Piece: 5053, Folio: 13, Page: 19.

Failed to save Lost Cousins record in database error was: constraint failed
UNIQUE constraint failed: LostCousins.CensusYear, LostCousins.CensusCountry, LostCousins.CensusRef, LostCousins.IndIDProblem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 4 of 29: England & Wales Census 1881 - Failed to add I10137: Jane UNKNOWN b.ABT 1827, Piece: 5120, Folio: 34, Page: 8.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 5 of 29: England & Wales Census 1881 - Failed to add I01301: Elizabeth Frost b.ABT 1860, Piece: 5080, Folio: 51, Page: 22.
Record 6 of 29: England & Wales Census 1881 - Already Present I13285: Ann Elizabeth Watson b.APR 1876, Piece: 754, Folio: 31, Page: 56.

Failed to save Lost Cousins record in database error was: constraint failed
UNIQUE constraint failed: LostCousins.CensusYear, LostCousins.CensusCountry, LostCousins.CensusRef, LostCousins.IndIDRecord 7 of 29: England & Wales Census 1881 - Already Present I14363: James Forrest b.6 OCT 1879, Piece: 693, Folio: 27, Page: 50.

Failed to save Lost Cousins record in database error was: constraint failed
UNIQUE constraint failed: LostCousins.CensusYear, LostCousins.CensusCountry, LostCousins.CensusRef, LostCousins.IndIDProblem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 8 of 29: England & Wales Census 1881 - Failed to add I17467: George Hunter b.10 MAR 1876, Piece: 5011, Folio: 104, Page: 28.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 9 of 29: England & Wales Census 1881 - Failed to add I29992: Janet UNKNOWN b.ABT 1848, Piece: 4852, Folio: 105, Page: 4.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 10 of 29: England & Wales Census 1881 - Failed to add I30505: Jane Elizabeth UNKNOWN b.ABT 1852, Piece: 5115, Folio: 110, Page: 28.
Record 11 of 29: England & Wales Census 1881 - Already Present I36831: John Charles Stewart b.JUN 1835, Piece: 5096, Folio: 86, Page: 33.

Failed to save Lost Cousins record in database error was: constraint failed
UNIQUE constraint failed: LostCousins.CensusYear, LostCousins.CensusCountry, LostCousins.CensusRef, LostCousins.IndIDProblem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 12 of 29: England & Wales Census 1881 - Failed to add I36915: Andrew Nichol Dodds b.1831, Piece: 5079, Folio: 89, Page: 6.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 13 of 29: England & Wales Census 1881 - Failed to add I23865: Mary Arnott Jowsey b.ABT 1835, Piece: 5079, Folio: 89, Page: 6.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 14 of 29: England & Wales Census 1881 - Failed to add I36918: Jane Eleanor Dodds b.JAN 1872, Piece: 5079, Folio: 89, Page: 6.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 15 of 29: England & Wales Census 1881 - Failed to add I36919: Charles Grey b.24 OCT 1873, Piece: 5114, Folio: 41, Page: 20.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 16 of 29: England & Wales Census 1881 - Failed to add I36924: Alfred Henry Gray b.OCT 1875, Piece: 752, Folio: 60, Page: 19.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 17 of 29: England & Wales Census 1881 - Failed to add I36930: Ellen Eliza Davis b.APR 1880, Piece: 1239, Folio: 55, Page: 17.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 18 of 29: England & Wales Census 1881 - Failed to add I36931: Frederick Samuel Penn b.JUL 1875, Piece: 1133, Folio: 65, Page: 22.
Record 19 of 29: England & Wales Census 1911 - Already Present I15403: James Andrew Holmes b.OCT 1909, Piece: 30284, Schedule: 197.

Failed to save Lost Cousins record in database error was: constraint failed
UNIQUE constraint failed: LostCousins.CensusYear, LostCousins.CensusCountry, LostCousins.CensusRef, LostCousins.IndIDRecord 20 of 29: England & Wales Census 1911 - Already Present I02490: John George Adamson b.OCT 1885, Piece: 30089, Schedule: 28.

Failed to save Lost Cousins record in database error was: constraint failed
UNIQUE constraint failed: LostCousins.CensusYear, LostCousins.CensusCountry, LostCousins.CensusRef, LostCousins.IndIDProblem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 21 of 29: Scotland Census 1881 - Failed to add I12486: Catherine Lugton Outterson b.27 JUN 1868, Parish: Edinburgh St Cuthberts, ED: 64, Page: 9.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 22 of 29: US Federal Census 1880 - Failed to add I34817: Sarah UNKNOWN b.FEB 1837, Roll: 907, ED: 211, Page: 248D.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 23 of 29: US Federal Census 1880 - Failed to add I34878: Ann Eliza UNKNOWN b.1826, Roll: 915, ED: 262, Page: 64B.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 24 of 29: US Federal Census 1880 - Failed to add I34930: Ellen UNKNOWN b.1843, Roll: 100, ED: 060, Page: 650C.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 25 of 29: US Federal Census 1940 - Failed to add I34785: Nancy UNKNOWN b.ABT 1867, Roll: 1596, ED: 7-107, Page: 11B.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 26 of 29: US Federal Census 1940 - Failed to add I35219: Isabel UNKNOWN b.ABT 1907, Roll: 3684, ED: 71-80, Page: 11A.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 27 of 29: US Federal Census 1940 - Failed to add I36241: Magine O UNKNOWN b.ABT 1917, Roll: 572, ED: 1-556, Page: 4A.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 28 of 29: US Federal Census 1940 - Failed to add I36355: Margaret R UNKNOWN b.1920, Roll: 4211, ED: 4-39, Page: 7A.
Problem accessing Lost Cousins Website to send record below. Error message is: startIndex must be less than length of string.
Parameter name: startIndex
Record 29 of 29: US Federal Census 1940 - Failed to add I36773: Ellie Irene UNKNOWN b.ABT 1920, Roll: 4481, ED: 22-33, Page: 1B.

Finished writing Entries to Lost Cousins website. 0 successfully added, 6 already present, 0 possible duplicates and 23 failed.
View Lost Cousins Report tab to see current status.

Cheers

Dale

**Comment by ShammyLevva** [comment]
Thanks Dale very useful. I’ll rethink how I’m processing this.

**Comment by ShammyLevva** [comment]
Ok fixed I think for next version.

**Comment by ShammyLevva** [comment]
V7.3.7.4 released could users affected retry please to confirm fix so I can close out this one.

**Comment by Onceageordie** [comment]
Just re-tried but program is not updating. Still showing 7.3.7.3.

**Comment by ShammyLevva** [comment]
Oh bugger maybe didn’t update version number when I released it.

**Comment by ShammyLevva** [comment]
Yes should pre filter. I’d forgotten to properly test that. Will have a look once done with Spain drama.

**Comment by bmurcutt** [comment]
Appears to be resolved in 7.3.7.4
