### ISSUE TITLE
[BUG] 1841 Census - Folio/Book swapped

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#114]
Version as at 31 Jan 10am (and probably current available 7.3.7.3)

We have got the following pattern (EW_CENSUS_1841_51_PATTERN6, I think) mapping incorrectly:

3 PAGE Bethnal Green, folio 10/9, page 11, Caroline Shaboe; digita
4 CONC l images, \i FindMyPast.co.uk\i0  (https://search.findmypas
4 CONC t.co.uk/search-world-Records/1841-england-wales-and-scotlan
4 CONC d-census : accessed 29 Dec 2009); citing PRO HO/107/692

Should result in the same outcome as:

Archive reference HO107
Piece number 692
Book number  10
Folio number  9
Page number  11

We have Book and Folio swapped around (Folio 10/9 should be read as Book 10 Folio 9)!

Detected by finding duplicate entries in LC with differing references  :(

A 'delete' function would be useful now :)

**Comment by ShammyLevva** [comment]
I’m planning on adding a verification tab that may allow a selective delete.

**Comment by ShammyLevva** [comment]
Fixed in v7.3.7.5

**Comment by bmurcutt** [comment]
FAILED.

Census reference (in potential upload file) still has it the wrong way …

![image](https://user-images.githubusercontent.com/47096037/52826577-94152a00-3115-11e9-8ced-2f787f1a66a3.png)

**Comment by ShammyLevva** [comment]
Is it the case that it is ALWAYS book/folio or is it 50/50. If 50/50 then I need to delete this pattern or change it to have incomplete reference, as there is nothing at all to tell what way round it is.

**Comment by ShammyLevva** [comment]
folio 10/9 is surely folio 10 book 9?

**Comment by bmurcutt** [comment]
Good question!

To my knowledge it is always book/folio.  But I am not an expert!  I identified that I had a number of cases I had already on LC that FTAnalyzer loaded again with the book/folio reference reversed.  They all appeared to have this format.

Were there others that worked 'correctly' in the same format?  No idea!

I can surmise that while it is phrased as Folio 01/02, it is identifying a unique folio reference by linking with the book reference (ie folio 02 within book 01).  One would think the referencing would be consistent!

I'm not sure how to confirm though ... perhaps Peter will be more knowledgeable about it??

Brian

**Comment by bmurcutt** [comment]
That's what I assumed originally too!

But see my last message, and the original post for this issue.

Checking with Peter may be worthwhile ... we probably want to be 100% sure before changing things!

Brian

**Comment by bmurcutt** [comment]
Just looked at Peter's FAQs about references.

It doesn’t specifically cover this format scenario.  But he does explain that (for 1841) a 'folio' is a two-sided piece of paper - so it is broader than a page, but less than a book.

It also seemed (to me) that page is probably unique within a book too, so folio, while a required element, is perhaps obsolete in terms of identifying uniqueness??  Again, a Peter question (if you can't find a source of truth elsewhere).

Brian

**Comment by ShammyLevva** [comment]
Thanks I’ll ask him and see what he says.

**Comment by ShammyLevva** [comment]
https://www.findmypast.co.uk/search/results?datasetname=1841+england%2c+wales+%26+scotland+census&pieceno=692&folio=9&page=11&book=10
has some records whereas 

https://www.findmypast.co.uk/search/results?datasetname=1841+england%2c+wales+%26+scotland+census&pieceno=692&folio=10&page=11&book=9

has none. Can you confirm that the first one has your census folks?

**Comment by ShammyLevva** [comment]
Checking the weblink to Find my past book/folio is right by looks of things

**Comment by bmurcutt** [comment]
Yes, the first link (book 10, folio 9) has my people (the Shaboe family).

This is consistent with the LC result - when both formats were there, the original would link to the Census form, the FTAnalyzer version would not.

In this case (and several others I had), the folio/book combination were being incorrectly set in FTAnalyzer.

As to whether it is the situation in ALL cases of the combined reference format, I can’t be 100% sure!!  That's the question for Peter 🤓

Brian

**Comment by ShammyLevva** [comment]
Peter has clarified for folio 10/9 it is book 10 folio 9 and this is confirmed by checking the reports on FindMyPast. Fixed for v7.3.7.7
