### ISSUE TITLE
Check existing Lost Cousins entries

### ISSUE THREAD

**Issue by jgcirencester** [ShammyLevva/FTAnalyzer#115]
**Is your feature request related to a problem? Please describe.**
Loading entries from ged file must involve deciding whether they are already there.  Perhaps the same lookup could be attached to a button to verify the links already present and produce report of mis-matches.

**Describe the solution you'd like**
New button and feagture

**Describe alternatives you've considered**
one at a time check, tedious if lots loaded at once.

**Comment by ShammyLevva** [comment]
Not entirely sure what check is requested here. What links already present are you referring to and what mismatches do you mean? 

If you mean the links on the my ancestors page yes they are loaded and presented on the verification tab (not yet visible). However the links to FindMyPast do not permit automated lookups to check against the data in your tree. So whilst I was hoping to add a "traffic light" system to visually show the bad and potentially bad entries I've had to shelve that in favour of a check the household manually option. 

Sadly it would break the terms of the licence FindMyPast have with LostCousins to fully automate this as it would be regarded as harvesting the data from their database. Even though it would be a limited subset of data per user.

If I have misunderstood your request please respond.

My hope is that I can produce something to allow users to mark households as checked.

**Comment by jgcirencester** [comment]
Thanks for the update.  Didn't realise that an automatic check would break the license terms so what I hoped for can't be done. 

The verification tab and check marks sound excellent alternatives.
