### ISSUE TITLE
Restore window positioning

### ISSUE THREAD

**Issue by nomadyow** [ShammyLevva/FTAnalyzer#116]
I have my taskbar set to the top of the screen.  Every window that FTAnalyzer opens, the top of the window is hidden under the taskbar so that I can't grab and reposition it.  I've worked around it by resizing these windows which causes them to 'pop' out from under the taskbar and that allows me to move them around.

A simple fix for this would be to remember the x & y of each window's location so that the next time the same window type is opened it opens in its previous location.

Alternatively figuring out how to initially position the window so that it isn't under the Windows taskbar would work as well.

**Comment by ShammyLevva** [comment]
Fixed for next version.
