### ISSUE TITLE
[BUG] Invalid 'potential' Lost Cousin update records

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#117]
7.3.7.3

The following issues appear in the potential LC upload file:

**Census Ref:** 
   Piece: 141, Book: **see census image (stamped on the census page after the piece number)**, Folio: 19, Page: 2

Sourced from GEDCOM extract:
3 PAGE Leeds Town, Crowan, Helston, Cornwall, England, folio 19, p
4 CONC age 2, John Jenkin; digital images, \i FindMyPast.co.uk\i
4 CONC 0  (https://search.findmypast.co.uk/search-world-Records/18
4 CONC 41-england-wales-and-scotland-census : accessed 5 Oct 2015)
4 CONC ; citing PRO HO/107/141/6
…
5 CONT Archive reference HO107
5 CONT Piece number 141
5 CONT Book number 6
5 CONT Folio number 19
5 CONT Page number 2

**Expected Result:**  Valid Reference, or flagged as an invalid reference

------------------

**Census Ref:** 
   **< blank >**

Sourced from GEDCOM extract:
3 PAGE Bunt Lodge, Nether Street, Finchley, Barnet, London, Englan
4 CONC d, folio 3/16, page 24, William Morcot; digital images, \
4 CONC i FindMyPast.co.uk\i0  (https://search.findmypast.co.uk/sea
4 CONC rch-world-Records/1841-england-wales-and-scotland-censu
4 CONC s : accessed 22 Sep 2009); citing PRO HO/107/RG HO107
…
5 CONT Archive reference HO107
5 CONT Piece number 663
5 CONT Book number 3
5 CONT Folio number 16
5 CONT Page number 24

**Expected Result:**  Valid Reference, or flagged as an invalid reference

 -----------------

**Age:**
   **UNKNOWN**

No birth fact (and Christening fact not used as substitute)

**Expected Result:**  Record flagged as error (invalid age or similar) and not generated as a potential LC load record

---------------

**Surname and Maiden Name not known** (my default for both is {--- ? ---] - all special chars)

Maiden name unknown, and no spouse record in GEDCOM (on review, the census surname is recorded in the Census record, but I haven't created a 'dummy' spouse record for your determination of it)

**Expected Result:**  Record flagged as error (full census name not defined or similar) and not generated as a potential LC load record

**Comment by ShammyLevva** [comment]
Is it possible to email a GEDCOM with these issues evidenced.

**Comment by bmurcutt** [comment]
I’ll try and put one together tomorrow (my time!)

B

**Comment by bmurcutt** [comment]
OK … got it sorted I think …

IMPORTANT TO NOTE:  It depends on who is the root person as to how these manifest themselves in the Potential Lost Cousins Upload list!!  Even with all relationship types (incl 'unknown') selected on the Census tab.

In theory, the root person should not matter (for these issues) - but I suspect that 'Unknown' relationship types are being ignored from a LC handling perspective (I can understand that - in theory at least - they probably are not relevant in an LC context).  They do all seem to appear on the 'Facts' tab 'Census' type list.

In this cut-down extract, lots of relationships are 'unknown', whereas they would all be related (to me) in some way in my full file.  

I loaded to your test ftanalyzer LC account - having 'renamed' my Geocodes file first to avoid hassles with its involvement.  

Sub-issue 1:  Book reference

Essentially is the same as that noted in issue 98.  You will find it in Family 1 in attached GEDCOM
Set I2079 as the root person.  You will see all of Family 1 with an invalid Census reference.  They are the only entries.
All failed to load (I5 because it failed the Age test first, the rest because of the reference).

Sub-issue 2:  Invalid age

See I0117 in attached GEDCOM.
Set I0117 as the root person.  You will see one entry for an unknown Age.  It is the only one.  
It failed to load.

Sub-issue 3:  Blank census reference

Essentially is the same as that noted in issue 100.  See I3321 in attached GEDCOM (1841 reference).
Set I3321 as the root person.      
The 1881 entry loaded successfully (startIndex issue #113 appears to be resolved).
The 1841 entry failed to load.

Sub-issue 4:  Surname issue

Essentially is the same as that noted in issue 103.  See I4636 in attached GEDCOM
Set I4636 as the root person.  You will see she has no determinable census surname.
All records loaded!!!!!  Including I4636 - with a surname of '------' (from '[---?---]).  Theoretically it shouldn't load, but ultimately it probably doesn't matter (it'll never likely match anyone, and if I find a name later, it'll load the new name (I think)).

Regards.

**Comment by bmurcutt** [comment]
[FTA Issue 117.txt](https://github.com/ShammyLevva/FTAnalyzer/files/2843653/FTA.Issue.117.txt)

Here's the GEDCOM - rename to a .ged (I couldn't attach it otherwise!)

**Comment by ShammyLevva** [comment]
Issue 117a fixed.

**Comment by ShammyLevva** [comment]
Issue 117c - Not sure that simply excluding records is good idea. That then means there is nothing at all to tell the user WHY they are excluded. If they fail the upload the user is given explicit indication it failed because name was invalid or age was invalid etc. Tempted to revert changes to name to simply fail so user gets error not that the name/age doesn't allow them to upload.

**Comment by ShammyLevva** [comment]
Issue 117 subissue 4 - Added extra trimming of multiple dashes however as per subissue 2 this will load and fail not just be hidden.

**Comment by bmurcutt** [comment]
Hi Alexander.

I raised the issue/s on the basis that (my understanding of the intent of the process was) records available to load should not fail basic LC validations.

You already exclude records that have detected census references issues

I agree that you would either:
 - need to extend this to include other invalid conditions (eg unknown birth age, no derivable census surname, etc)
 - create a second category of LC transaction fail issues separate from the census references
 - include the conditions in the general error checks (if they make sense to put there - but I'm not sure they do??)

It would be inappropriate (as you say) to just have the issues 'disappear'.

While I lean towards the early reporting of conditions that will be known to fail, I can certainly see (and accept!) that adding conditions (and complexity) that LC already manages adds little value to the outcome of ensuring that what is loaded to LC is valid and suitable, so why duplicate it?  

If you determine that is the way it should be (for now at least), I would also suggest you leave the invalid chars in names as they are (avoiding something like 'Sm?th' loading as 'Smth'.  Along with (however it is appropriate to do so) indicating that records are not guaranteed to load dependant on LC checks.

Regards,

Brian

**Comment by ShammyLevva** [comment]
Yup it’s a tricky call. What I’ve done is to have the.routine check the valid names and ages and report before sending to Lost Cousins. This will let the user know that the census reference is ok but there is a problem with age or name. In theory if the person is found on the census then the name and age (as per the census) should be known. So in theory it’s a simple fix for the user. 

The married name should be picked up if the maiden name is unknown as per your —-?—— examples.

I guess it’s a bit of trial and error to see what works best.

**Comment by bmurcutt** [comment]
Or, as in a number of my cases, select the 'use baptism date as birth date' option 😜

Usually my surname issue is that I don't know the maiden name, and I haven’t entered a 'dummy' spouse name with the married name as recorded on the Census so you can derive an 'as at Census name'.  Usually only happens when the wife's widowed mother is recorded at the household.

If that type of case doesn’t load, I think Peter's view is other household members should match anyway, so nothing is lost from his end.  

But I should enter the dummy spouse.  We're getting into the 'related by marriage only' area, so sometimes I haven't followed through!

Regards,

Brian

**Comment by ShammyLevva** [comment]
I think these are all fixed in v7.3.7.5 I'll close and if you can generate new ones if something still odd.

**Comment by bmurcutt** [comment]
Invalid reference - fixed
Blank reference - fixed

Before I re-raise anything, just want to confirm …

AGE undetermined - are you staying with the idea that the record is included in the potential load file and will try to (and fail) the actual load?

Census Surname - where the surname is (my) "[--- ? ---]" it will try to (and succeed) loading to LC as "--".  You strip off invalid characters, leaving dashes, and it succeeds in loading to LC.  Should you leave the invalid characters in the load and let the load record fail???

**Comment by ShammyLevva** [comment]
Yes age will say - Cannot determine age at census

Census Surname - it will strip non Lost Cousins characters and if it ends up as a load of dashes it will treat that name as Unknown and so should give a message  Cannot process person with unknown forename or surname

**Comment by bmurcutt** [comment]
Age - worked like that.
Surname - didn’t ... it loaded '—'.  Do you want me to raise an issue?

Brian

**Comment by ShammyLevva** [comment]
Ah ok I thought I'd stripped multi dashes.

**Comment by bmurcutt** [comment]
Confirming surname issue - you will load to LC a determined surname of "[--- ? ---]" as "-", rather than have it fail?  If so, that's what it did.  
![image](https://user-images.githubusercontent.com/47096037/52922855-74317080-3378-11e9-9dee-70e1d39582a3.png)

If not … (according to your comment above "it will strip non Lost Cousins characters and if it ends up as a load of dashes it will treat that name as Unknown and so should give a message Cannot process person with unknown forename or surname") … then the test failed (look at I4636 in file FTA issue 117.ged, with I4636 as root), and record loaded to your LC test account??

**Comment by ShammyLevva** [comment]
Ah ok yes it should have converted a single dash to Unknown.
