### ISSUE TITLE
[BUG] LC Updated "Correct Surname" Problem

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#118]
V7.3.7.4

After correct update to LostCousins when checking the upload the Maiden Name, Surname, Forename & Middle Names are duplicated in the corrections area. This is a great timesaver for any editing needed. However, if the Surname is a married name the maiden name gets duplicated in the Corrected Surname instead of the married name.

![image](https://user-images.githubusercontent.com/35932839/52473214-25702380-2b8d-11e9-8c85-0540a4445605.png)

**Comment by ShammyLevva** [comment]
Thanks will be a simple fix.

**Comment by ShammyLevva** [comment]
Fixed
