### ISSUE TITLE
[BUG] LC Already Present & Failed To Add - Not being removed between sessions

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#119]
V7.3.7.4

After updating LostCousins I have a number of entries that show Already Present. These entries do not disappear after ending the program and re-opening. Even if I use a new Gedcom they still keep coming up.

Also all of the entries with UNKNOWN Surname are Failed To Add. I have checked these entries on the LC site and they are all there. I have changed to surnames on all these entries to the correct married name but they are still showing up in the "update" report.

Is there a way to remove all of the se erroneous entries?

Cheers

Dale

Started Processing Lost Cousins entries.

Record 1 of 22: England & Wales Census 1881 - Already Present I03329: William Thomas Scott b.DEC 1865, Piece: 5053, Folio: 13, Page: 19.
Record 2 of 22: England & Wales Census 1881 - Failed to add I10137: Jane UNKNOWN b.ABT 1827, Piece: 5120, Folio: 34, Page: 8.
Record 3 of 22: England & Wales Census 1881 - Already Present I02419: Sarah Snowdon b.2 NOV 1862, Piece: 4887, Folio: 99, Page: 3.
Record 4 of 22: England & Wales Census 1881 - Already Present I13285: Ann Elizabeth Watson b.APR 1876, Piece: 754, Folio: 31, Page: 56.
Record 5 of 22: England & Wales Census 1881 - Already Present I14363: James Forrest b.6 OCT 1879, Piece: 693, Folio: 27, Page: 50.
Record 6 of 22: England & Wales Census 1881 - Already Present I16283: Ann Edith Hardy b.APR 1871, Piece: 4847, Folio: 52, Page: 14.
Record 7 of 22: England & Wales Census 1881 - Already Present I22786: Lilly Usher Lacy b.14 JUN 1878, Piece: 4857, Folio: 7, Page: 7.
Record 8 of 22: England & Wales Census 1881 - Failed to add I29992: Janet UNKNOWN b.ABT 1848, Piece: 4852, Folio: 105, Page: 4.
Record 9 of 22: England & Wales Census 1881 - Failed to add I30505: Jane Elizabeth UNKNOWN b.ABT 1852, Piece: 5115, Folio: 110, Page: 28.
Record 10 of 22: England & Wales Census 1881 - Already Present I36831: John Charles Stewart b.JUN 1835, Piece: 5096, Folio: 86, Page: 33.
Record 11 of 22: England & Wales Census 1911 - Already Present I15403: James Andrew Holmes b.OCT 1909, Piece: 30284, Schedule: 197.
Record 12 of 22: England & Wales Census 1911 - Already Present I02490: John George Adamson b.OCT 1885, Piece: 30089, Schedule: 28.
Record 13 of 22: England & Wales Census 1911 - Already Present I03333: Alice Marion Stobbs b.ABT 1901, Piece: 11489, Schedule: 66.
Record 14 of 22: Scotland Census 1881 - Already Present I12486: Catherine Lugton Outterson b.27 JUN 1868, Parish: Edinburgh St Cuthberts, ED: 64, Page: 9.
Record 15 of 22: US Federal Census 1880 - Failed to add I34817: Sarah UNKNOWN b.FEB 1837, Roll: 907, ED: 211, Page: 248D.
Record 16 of 22: US Federal Census 1880 - Failed to add I34878: Ann Eliza UNKNOWN b.1826, Roll: 915, ED: 262, Page: 64B.
Record 17 of 22: US Federal Census 1880 - Already submitted this session I34930: Ellen UNKNOWN b.1843, Roll: 100, ED: 060, Page: 650C. Possible duplicate Individual
Record 18 of 22: US Federal Census 1940 - Failed to add I34785: Nancy UNKNOWN b.ABT 1867, Roll: 1596, ED: 7-107, Page: 11B.
Record 19 of 22: US Federal Census 1940 - Failed to add I35219: Isabel UNKNOWN b.ABT 1907, Roll: 3684, ED: 71-80, Page: 11A.
Record 20 of 22: US Federal Census 1940 - Failed to add I36241: Magine O UNKNOWN b.ABT 1917, Roll: 572, ED: 1-556, Page: 4A.
Record 21 of 22: US Federal Census 1940 - Failed to add I36355: Margaret R UNKNOWN b.1920, Roll: 4211, ED: 4-39, Page: 7A.
Record 22 of 22: US Federal Census 1940 - Failed to add I36773: Ellie Irene UNKNOWN b.ABT 1920, Roll: 4481, ED: 22-33, Page: 1B.

Finished writing Entries to Lost Cousins website. 0 successfully added, 11 already present, 1 possible duplicates and 10 failed.
View Lost Cousins Report tab to see current status.

**Comment by ShammyLevva** [comment]
The already present should auto create a LostCousins custom fact and save it in database. I’ll have a look to see why this is not happening. 

Meantime you can add a custom Lost Cousins fact yourself. Before the auto upload this is how users dealt with the LostCousins entries.  

Format is custom fact called Lost Cousins date is the year of census.

**Comment by ShammyLevva** [comment]
Added extra check for already present.

**Comment by ShammyLevva** [comment]
Added unknown surname filter.

**Comment by ShammyLevva** [comment]
This should all be fixed in v7.3.7.5
