### ISSUE TITLE
Not handling Julian calendar dates correctly

### ISSUE THREAD

**Issue by ColinD3** [ShammyLevva/FTAnalyzer#12]
I have a birth on 20 May 1744 and a burial on 20 May 1744. This is correct as the Julian year starts on 25 March and ends on the 24th of March, These dates are reported as an error "burial before birth". It is not until 1752 that the calendar changed to the modern calendar.

**Comment by ShammyLevva** [comment]
I’m not sure it’s anything to do with the change of calendar. I suspect it’s to do with being on same day. Can you provide me with a GEDCOM snippet that shows this issue and I’ll aim to get it fixed today.

**Comment by ShammyLevva** [comment]
I’ve just had a look at the code can you check what the error says please there isn’t an error type that says burial before birth. I’d need to know the actual wording to be sure I was checking the right code. Or have a snippet to see the issue for myself.

**Comment by ColinD3** [comment]
Error message is “

	Birth after death/burial

I0876

Mary Manfield

Buried 20 MAY 1744 before born

15 JAN 1743/44

1744”

My apologies, I got it the wrong way round. She was actually born 15 Jan 1743 but my genealogical program allows for both calendars hence the 1743/44.

 

The gedcom snippet is :-

 

1 REFN 876

1 NAME Mary /Manfield/ 

1 SEX F

1 CHAN

2 DATE 13 OCT 2016                  

1 DEAT

2 DATE 1744

1 BAPM

2 DATE 15 JAN 1743/44

2 PLAC Nailsea, Somerset, England

2 SOUR @S55@

2 SOUR @S67@

3 PAGE Holy Trinity Nailsea DP NA HT 2/1/2

1 BURI

2 DATE 20 MAY 1744

2 PLAC Nailsea, Somerset, England

 

I think the problem is that the birth date has been interpreted as 1744 and 20 May 1744 comes before 15 Jan 1744. So if the year is written as 1743/1744 then in should be interpreted for checking purposes as 1743 the we would have the birth as 15 Jan 1743 and the death as 20 May 1744.

 

I hope that helps,

 

Colin Daniels

**Comment by ShammyLevva** [comment]
Thanks for that helps a lot. It appears that the IsBefore and IsAfter functions are not correct when dealing with a year 1744 vs a double date. I'll have to tweak to code to fix this.

**Comment by ColinD3** [comment]
I am sure you realise that is not just the year 1744 but all those prior to 1752.

**Comment by ShammyLevva** [comment]
Yup it's the IsBefore and IsAfter routines check for double dates it's mishandling these edge cases where the year is the same as one of the years in the double date.

**Comment by ShammyLevva** [comment]
Fixed in v6.1.0.0

**Comment by ColinD3** [comment]
Alexander,

 

Thank you for your efforts.

 

When will v6.1.0 be available?

 

Regards,

 

Colin Daniels

**Comment by ShammyLevva** [comment]
Later this week.
