### ISSUE TITLE
[BUG] LC Corrected Middle Names error

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#120]
V7.3.7.4

When checking an uploaded record on LostCousins, if the person has two (or More?) middle names, they are being concatenated in both the Middle Names field and the Corrected Middle Names field. In the Middle Names field the second name has its initial letter converted to lower case, while it is correct in the Corrected Middle Names field.

![image](https://user-images.githubusercontent.com/35932839/52561727-25259180-2df4-11e9-85d3-a874980f24d2.png)

**Comment by ShammyLevva** [comment]
Fixed in v7.3.7.5
