### ISSUE TITLE
[BUG] 7.3.7.4 You have 1 Census facts with no Lost Cousins fact

### ISSUE THREAD

**Issue by David-fh** [ShammyLevva/FTAnalyzer#122]

**Comment by David-fh** [comment]
Load gedcom file and goto Lost Cousins tab.
Family loaded to Family Historian using Ancestral Sources Data Entry so census record for each should be same. However George Green id 916 is reported as having no census country.
[George green.ged.txt](https://github.com/ShammyLevva/FTAnalyzer/files/2864877/George.green.ged.txt)

**Comment by ShammyLevva** [comment]
I’m not at my computer just now. However I’ve had a quick look at your file and what jumps out is your locations have 7 parts to them whereas the standard is 5 parts. So it may be the last two are getting dropped or something like that. 

Btw you closed the issue did you mean to close it?

**Comment by ShammyLevva** [comment]
Fixed for v7.3.7.7
