### ISSUE TITLE
[BUG] LC Incorrect or Missing Records

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#124]
V7.3.7.6 (and all recent versions)

When clicking the Lost Cousins Tab the Reports section tab is shown, with information relating to your Gedcom. Mine currently shows the following:

1881 England & Wales Census: 4134 LC Records, 3 Missing LC Record
1841 England & Wales Census: 852 LC Records, 1 Missing LC Record
1881 Scotland Census: 1170 LC Records, 1 Missing LC Record

When I then click on the corresponding button to the left the report pops up but none of the reports have any records in them. How can I find and display these "missing" records?

![image](https://user-images.githubusercontent.com/35932839/52897882-a2278100-31cf-11e9-8b1e-bbca4906f701.png)

Cheers

Dale

**Comment by ShammyLevva** [comment]
Hmm odd the 1881 England & Wales Census Button should show those three missing ones. The 1841 England & Wales Census button should show that 1 missing etc. Can you send me a GEDCOM that has the issue so I can investigate as I'm not seeing it with my file. ftanalyzer@gmail.com

**Comment by ShammyLevva** [comment]
Could you also send me the database file. From the file menu select geocode database and backup and it will save a file you can send.

**Comment by myfta** [comment]
I am experiencing the same problem as described here. I have just one "missing" 1841 entry apparently. I have tried to find it by comparing the LC Facts with the LC site, but without success. 

I have found one record that has census details correctly in Family Historian but the FTA census report says the fact has missing census refs. So I wonder if that is causing the anomaly?

I'll look out for the fix for the original problem here first.

Thanks, 

Graham

**Comment by Nichotj** [comment]
I had an issue like this a while back, but it may have been fixed now. The issue for me was that I had 2 census facts recorded and 1 LC fact. I don't know if FTA does a comparison and if they're the same then good, but if they are different flags it as an error?

You could try looking for duplicate facts?

**Comment by myfta** [comment]
Here are my two "strays" but the 1841 and 1881 reports do not show any suggested additions. The totals of facts reported do reconcile with the number of LC Facts found on the "Facts" tab.

![image](https://user-images.githubusercontent.com/47277622/53014765-54b24a80-3441-11e9-853a-294c6d3b8cd7.png)

**Comment by ShammyLevva** [comment]
Could you send the GEDCOM file and the database file to ftanalyzer@gmail.com 

Database file is created from file menu, geocode database, backup. 

I’ve got one sample but it has 10,000 people with 3 missing. Which is a genealogy needle in a haystack. Yours is more manageable.

**Comment by Onceageordie** [comment]
Hi Alexander,

Any updates on this?

Cheers

Dale

**Comment by ShammyLevva** [comment]
Unfortunately due to family illness I’ve yet to properly look at this.

**Comment by ShammyLevva** [comment]
I think this is John Ward with a residence fact in Oct/Nov 1841. Which is a census year. The check was seeing it was a census year and saying ok it could be a census fact which the counts were using as a census fact. The reports however were checking if it was valid (it wasn't as it was after the census date) so it wasn't displayed on the reports. 

I've added a check for the counts and for other residence as census facts to exclude records that are entirely after the census date.

Fixed for v7.4.0.0

**Comment by myfta** [comment]
Thanks.

Graham

**Comment by myfta** [comment]
I don't seem to be able to find v7.4.0.0 to download either via the website
or on GitHub.

Graham

**Comment by ShammyLevva** [comment]
That's because it's not released yet. I'm adding support for auto searching of Scotlands People website so a few tests needed before I can release a working version.
