### ISSUE TITLE
[BUG] Corrected Errors still reported

### ISSUE THREAD

**Issue by cjades** [ShammyLevva/FTAnalyzer#125]
Version 7.3.7.7

I have used FTA to check a GEDCOM from Ancestry. It revealed several 'Male Wives Female Husbands' and  'Couples with same surnames'.  I went and corrected those and then downloaded a fresh GEDCOM having deleted the old one and given the new one different file name.  The same errors are still reported even after a reboot.

What other information can I send you to help?
[Clearly I can uncheck those error types in the selection list if I am confident I have corrected them.]

**Comment by cjades** [comment]
I have tracked this down to an Ancestry GEDCOM error. When imported into Roots Magic the people concerned have no specified gender even though this has been corrected on Ancestry.

**Comment by ShammyLevva** [comment]
The problem with Ancestry is that it remembers old files so you need to clear the cookies so it downloads a fresh version otherwise it thinks it’s downloaded before so just gives you the old version.
