### ISSUE TITLE
[BUG]  Download Failure - Cannot Start Application - v7.3.7.7

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#127]
**Version Number problem appears in**
v7.3.7.7

**Describe the bug**
On starting FTAnalyzer, a new version is downloaded (seemingly OK), but fails to load with message box "Cannot Start Application" and message text is "Unable to retrieve application files. Files corrupt in deployment."

**To Reproduce**
Not reproducible, launching the app a second time causes a fresh download and the app opens OK.

**Expected behaviour**
Clean load on first download.

**Screenshots**
Log file attached

**Additional context**

**Comment by ShammyLevva** [comment]
Sorry this is entirely a Microsoft issue there is absolutely nothing I can do about this. If the download fails or gets hung up on something then restarting it to retry is a worthwhile solution. I have NO control over the installation process. So I cannot fix what I cannot control thus I'll close the issue. Sorry.
