### ISSUE TITLE
[BUG] Baptism date used instead of birth date

### ISSUE THREAD

**Issue by dmmason28** [ShammyLevva/FTAnalyzer#129]
**Version Number problem appears in*v7.3.7.7*
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**
FTAnalyzer, if there is not a birth date, assumes that a baptism date is the birth date. This is not correct and can cause erroneous errors to be displayed. A baptism date can be years after a birth date.

**To Reproduce**

**Expected behavior**
FTAnalyzer should not assume a baptism date is a birth date and this would eliminate erroneous errors.

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
This is a user option go into the Tools, Options and under General Settings turn off use baptism dates if no birth date.

![image](https://user-images.githubusercontent.com/29687786/56852992-ee9ee380-6919-11e9-8d8e-980626bc6ca3.png)
