### ISSUE TITLE
Error was: No space found in line: 'www.rootsireland.ie'

### ISSUE THREAD

**Issue by JohnnyHP** [ShammyLevva/FTAnalyzer#132]
On opening my file in  v7.3.7.7 I receive an error: 
Invalid GEDCOM, Line: 39137: 'www.rootsireland.ie'. Error was: No space found in line: 'www.rootsireland.ie'

As this a link to a website it would not have a space.

Not a biggie, but just a comment, thanks.

**Comment by ShammyLevva** [comment]
That is actually an error. ALL GEDCOM lines start with a number and then have a space and the text if the line does not start with a number and a space it's not a valid GEDCOM line. So it looks like the text www.rootsireland.ie is on a line by itself with no number at the start of the line that's wrong.
