### ISSUE TITLE
[BUG] Surname for children shouldn't be married name in Lost Cousins Updates tab.

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#134]
**Version Number problem appears in**
7.4.0.0

**Describe the bug**
On the View invalid census refs report, Loct Cousins tab, Updates, the Husband/Wife/Child is not accurate for the time of the census
In the image you can see that Dora is 5, but her future married name "Ladyman" is shown, and she's described as Wife but she should be Child.

![image](https://user-images.githubusercontent.com/29726075/58768038-a4e69000-858c-11e9-9648-a8700331fc8f.png)

**Comment by ShammyLevva** [comment]
Do you have a gedcom snippet for that family so I can check why it's doing that please.

**Comment by Nichotj** [comment]
Here's the example
[Dora Sloan example.zip](https://github.com/ShammyLevva/FTAnalyzer/files/3295927/Dora.Sloan.example.zip)

**Comment by ShammyLevva** [comment]
I'm not seeing what you are seeing with that snippet. I suspect this is because the root person is different. Which person should be the root to cause this effect?

**Comment by ShammyLevva** [comment]
fixed in v8.0.1
