### ISSUE TITLE
Accept full date for census year in LostCousins tab

### ISSUE THREAD

**Issue by NickWilkinsonSA** [ShammyLevva/FTAnalyzer#135]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NickWilkinsonSA** [comment]
First let me congratulate you on a really great suite of applications which is of tremendous help in clearing up errors in all sorts of places. As a user of the LostCousins website for many years I heard about FTAnalyser and decided to use it along with my Legacy9 software for the purpose of tracking my LostCousins entries. As such I added LostCousins events to the persons in Legacy with the relevant Census dates. However I entered the full date – i.e. 6 Jun 1841, 3 Apr 1881…- and not just the census year. Now FTAnalyser does not recognise a LostCousins event with the full date format but expects just the census year. There is no simple way to do a bulk change in Legacy and I have 9000+ individuals in the tree so doing a manual change is not worthwhile. Is it possible to modify FTAnalyser to accept the full date format as well as just the year? This is not a major problem but it would help me clean up my ‘error’.
I attach a gedcom file for your testing purposes.
[Alfred Beavis.zip](https://github.com/ShammyLevva/FTAnalyzer/files/3276084/Alfred.Beavis.zip)

**Comment by ShammyLevva** [comment]
![image](https://user-images.githubusercontent.com/29687786/59390586-aa509100-8d69-11e9-9000-0ab724e57c49.png)
![image](https://user-images.githubusercontent.com/29687786/59390615-bccaca80-8d69-11e9-8e95-7d9e71554c4c.png)

In both of these cases it has correctly identified the Lost Cousins facts with the full date.
