### ISSUE TITLE
Google API Problem...

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#136]
FTA Ver 7.4.0.0

Decided to spend some time on mapping so followed instructions to setup API key. All went well, and copied key into FTA options.

When running any of the Geocoder options under Maps I get the following:

![image](https://user-images.githubusercontent.com/35932839/59281889-f2838c80-8c5f-11e9-8674-49c3d10d164e.png)

If I click Continue it runs but quickly tells me I have exceeded my daily limit so it is obviously not using the API key.

Any ideas??

Cheers

Dale Utterson

**Comment by ShammyLevva** [comment]
Hmm that’s a font issue not a API key issue. So I suspect there are two different things at work here. 

1) font issue causing crash
2) api key not being recognised

**Comment by Onceageordie** [comment]
okay sorted it. Somehow I ended up setting up two projects on the google cloud and added the billing info to the wrong one, so the key was correct but there was no billing info attached to that project. I've now rectified that and am now running FTA again which seems to be working quite happily now.

Apologies for my faux pas!

**Comment by ShammyLevva** [comment]
Ah ok makes sense I did exactly the same myself.
