### ISSUE TITLE
[BUG] "Lost Cousins" Fact interfering with Lifeline display in Maps...

### ISSUE THREAD

**Issue by Onceageordie** [ShammyLevva/FTAnalyzer#138]
V7.4.0.0

In Maps, when running the Lifelines report for an individual, if they have a "Lost Cousins" fact the location is listed as England, Scotland, United States, Canada. This really screws up the display. Could the "Lost Cousins" fact be ignored for the timeline report, or can we have somewhere to Include/Exclude facts from the report?

![image](https://user-images.githubusercontent.com/35932839/59361432-c0d6f800-8d29-11e9-9786-6db1d25a4b9c.png)

Cheers

Dale Utterson

**Comment by ShammyLevva** [comment]
Fixed for v7.4.1.0
