### ISSUE TITLE
On This Day - Exclude World Events

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#139]
May we have a new setting (perhaps in Tools -> Options) to exclude the automatic inclusion of World Events in the "On This Day" report, please?

It is particularly an issue when running with the "Whole Month" rather than "Single Day". 

Thanks, M

**Comment by ShammyLevva** [comment]
You mean this option
![image](https://user-images.githubusercontent.com/29687786/59562868-1103d200-902a-11e9-8027-1b4f1592a328.png)
