### ISSUE TITLE
Surname tab issue

### ISSUE THREAD

**Issue by burnsbarber** [ShammyLevva/FTAnalyzer#14]
At least several (possibly all) of the links to One Name Studies site give an error

**Comment by ShammyLevva** [comment]
Thanks. This is not something I've looked at for several years. I suspect the site has been re-vamped since I wrote that part. I'll investigate.

**Comment by ShammyLevva** [comment]
Yes they have radically changed the site. I've gone with a different approach. Rather than trying to check if the name exists as a one name study which was taking ages as their site is really slow. I simply open the surnames and add a link to their site for each surname. Even then the rendering of the site is painfully slow.

So fixed in v6.1.0.0

**Comment by burnsbarber** [comment]
I have just run through my list.  There are 181 surnames in my tree. 24 show a link to ONS.  Of those, 10 give an error message; 14 go to the ONS site. Curious! Fixed?

 

 

Yes they have radically changed the site. I've gone with a different approach. Rather than trying to check if the name exists as a one name study which was taking ages as their site is really slow. I simply open the surnames and add a link to their site for each surname. Even then the rendering of the site is painfully slow.

So fixed in v6.1.0.0

**Comment by burnsbarber** [comment]
Sorry my previous email referred to the old version.  I thought I had installed the new version, but it does not yet seem possible to do so.

 

 

 

Yes they have radically changed the site. I've gone with a different approach. Rather than trying to check if the name exists as a one name study which was taking ages as their site is really slow. I simply open the surnames and add a link to their site for each surname. Even then the rendering of the site is painfully slow.

So fixed in v6.1.0.0

**Comment by ShammyLevva** [comment]
Yes the current released version is v6.0.5.0. I’ve fixed this for v6.1.0.0 which I hope to release this week.
