### ISSUE TITLE
Error loading previously submitted Lost Cousins data.

### ISSUE THREAD

**Issue by BrymanNZ** [ShammyLevva/FTAnalyzer#143]
Loading a newly generated Gedcom file to v7.4.2.0 I get SQL logic error for no such column: FullName

**Comment by ShammyLevva** [comment]
Odd that suggests a bug in your local database. 

The backup option on file menu will allow backup of database so I can investigate

**Comment by BrymanNZ** [comment]
[FTAnalyzer-Geocodes-2019-07-02-v7.4.2.0.zip](https://github.com/ShammyLevva/FTAnalyzer/files/3345604/FTAnalyzer-Geocodes-2019-07-02-v7.4.2.0.zip)

**Comment by ShammyLevva** [comment]
Extra checking code was added in v8.0.0 so if there's still an issue please re-open.
