### ISSUE TITLE
Mac version has No Reports?

### ISSUE THREAD

**Issue by robinwicks** [ShammyLevva/FTAnalyzer#146]
Version 1.3.0 (54)

on iMac late 2015 OSx 10.14.5 Mojave  installed program (don't remember date).
7-13 downloaded gedcom from Ancestry and uploaded to FTA.

In preferences (before uploading) I did notice that I kept UNchecking "use baptism/chr date if no birth date" and it kept REchecking it no matter what I did AND it has a secondary yellow glow around it none of the others have, just saying.  So it ended up checked last I looked before uploading but that's not my issue.  So here were my selections:
   General:  use baptism, show ancestors related multiple
   Census:  convert residence w/census ref, tolerate slightly, add auto-created census loc.
   File Handling: retry failed lines
   Nongedcom dates:  "add non-gedcom date pref here" is checked but grayed out, can't touch it.

So I had to ck the Guide again, to be sure, and my tabs are not showing like on there and "Reports" is not at top either.  Pic attached.
<img width="1004" alt="FTA 7-14-19 RW" src="https://user-images.githubusercontent.com/52897211/61190818-f2641b80-a667-11e9-8440-52b036519fc0.png">

**Comment by ShammyLevva** [comment]
I’ve not yet implemented the reports menu on a Mac. 

I’ll have a look at the options setting issue you mentioned. 

NB. At present I’m in run up to a big event I’m helping to host with 1500 people expected. I’ve not got a lot of time to look at app just now.

**Comment by robinwicks** [comment]
Ok, don’t mess with it then, it’s the reports I was hoping on.  Will ck in future, thank you for creating this, helps w/other things!

**Comment by ShammyLevva** [comment]
Sadly I can no longer commit to developing a Mac version as I no longer have a Mac that is compatible and cannot justify buying one.
