### ISSUE TITLE
Version 7.42.0 It looks like all dates such as 15 BC are problems.  It may be true of 15 AD also 

### ISSUE THREAD

**Issue by Rondahl** [ShammyLevva/FTAnalyzer#147]
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
Yes since there is zero documentation on anyone back this far I do not support pre year zero dates and have no plans to change this

**Comment by Rondahl** [comment]
I use Wikipedia as a source and have people such as https://en.wikipedia.org/wiki/Pacorus_I    entered.  I was putting in Parthian emperors.  No problem with ignoring it and keep up the good work.
    On Thursday, August 1, 2019, 04:03:26 PM CDT, Alexander Bisset <notifications@github.com> wrote:  
 
 
Yes since there is zero documentation on anyone back this far I do not support pre year zero dates and have no plans to change this
