### ISSUE TITLE
Installing FTAnalyzer

### ISSUE THREAD

**Issue by JanDickson** [ShammyLevva/FTAnalyzer#15]
Hi - trying to install FTAnalyzer but my anti virus (panda) says the setup.exe file is infected - Jan

**Comment by ShammyLevva** [comment]
What precisely is the error message? I suspect it’s something about the certificate not being trusted which suggests your machine is missing an update. 

Which version of Windows are you using?

**Comment by ShammyLevva** [comment]
Note that two of the major scanning sites that use dozens of different engines to scan the software all give the site a clean bill of health

https://www.virustotal.com/#/url/c8863dfd74a52c6c4e941ee28f83ea48d973912cc72ac24e21e2b7e53755c279/detection

http://www.urlvoid.com/scan/ftanalyzer.com/

**Comment by JanDickson** [comment]
OK - have told Panda to ignore it and it is now up and running. What a fantastic resource ! It will take me ages to sort through all the information it can provide. Thanks so much ! Regards Jan

**Comment by ShammyLevva** [comment]
No problem. You might want to like/follow the Facebook page for asking questions you have at www.facebook.com/ftanalyzer and/or follow me on twitter @ftanalyzer 

I'll close this issue as you have an answer ok.
