### ISSUE TITLE
FTA Crashes

### ISSUE THREAD

**Issue by nconway567** [ShammyLevva/FTAnalyzer#150]
FT Analyzer 7.4.2.0 Windows
Every time I try to click on the Locations tab, the program crashes.  It also crashed when I clicked Maps, Show Places.

[Unhandled exception.txt](https://github.com/ShammyLevva/FTAnalyzer/files/3536210/Unhandled.exception.txt)

**Comment by ShammyLevva** [comment]
Thanks for the exception trace I’ll investigate.

**Comment by nconway567** [comment]
No problem. It happened after I changed the applications's font size. The only way I got it to run and not crash on the Location tab was to run the Windows application compatibility tool - which made it run in Windows 8 mode.


________________________________

**Comment by ShammyLevva** [comment]
I've added extra exception trace handling to attempt to catch these errors I'll release v7.5.0.0 later please let me know if this has fixed the issue.

**Comment by ShammyLevva** [comment]
v7.5.0.0 released please advise if this fixes issues.

**Comment by ShammyLevva** [comment]
No further update for 4 months closing.
