### ISSUE TITLE
Relationship issue

### ISSUE THREAD

**Issue by HistoryDiver** [ShammyLevva/FTAnalyzer#151]
**Version Number problem appears in**
Version 1.3.0 (54) for Mac. 

**Describe the bug**
In Main Lists -> Facts  -> Relation  I'm getting a large number of unknowns, even though checking the entries on my Ancestry tree clearly shows the relationship to the root (i.e. myself). Sometimes the relations are quite distant, but often they are relatively close relations, well documented on the tree (1st cousins etc).

**Comment by HistoryDiver** [comment]
Here's what I'm seeing - a large number of 'Unknown's' in the [Relation] column, and nothing at all in [Relation to Root] column - the latter being the case with very many entries. Yet, checking the records on Ancestry the relationship is very clearly indicated (see visuals). 

![Screenshot 2019-09-29 at 15 14 01](https://user-images.githubusercontent.com/51875765/65833964-25649580-e2ce-11e9-961f-94a2dcc5c9ae.jpg)
![Screenshot 2019-09-29 at 15 16 05](https://user-images.githubusercontent.com/51875765/65833967-2c8ba380-e2ce-11e9-8d05-2f8474a43b55.jpg)
![Screenshot 2019-09-29 at 15 20 36](https://user-images.githubusercontent.com/51875765/65833970-331a1b00-e2ce-11e9-8532-1a37a9dff2f1.jpg)

**Comment by ShammyLevva** [comment]
I’d need a sample GEDCOM to determine why it’s missing a link.

**Comment by HistoryDiver** [comment]
Ok, thank you Alexander! should I upload one here, or is a direct email better?

**Comment by HistoryDiver** [comment]
Ah, github won't accept GED uploads, so mail it is - where should I send it?

**Comment by ShammyLevva** [comment]
FTAnalyzer@gmail.com. Headed on holiday tonight though so won’t be able to look at it for a couple of weeks

**Comment by ShammyLevva** [comment]
I'm having a look. On the front loading screen it should list who it thinks the root person is. Who is this set to?

**Comment by HistoryDiver** [comment]
That's very kind of you Alexander :) The root person is listed as "Calculating Relationships using P5: John Edwin Shelley as root person" (that's me of course).

**Comment by ShammyLevva** [comment]
I've loaded the GEDCOM supplied into Family Tree Maker and it shows no relationship between yourself and Edmund Ball and none between you and Charles Thomas Meadows. Is there something different between your online tree and the GEDCOM file?

**Comment by ShammyLevva** [comment]
ie: the program is working correctly there's just no link in the file provided.

**Comment by HistoryDiver** [comment]
Sorry for my slow response, my domain email is experiencing problems, I'm not receiving message updates from Github. Yes, the Online tree is clearly showing relationships between me and the entries, while the Gedcom uploaded to Family Tree Analyzer shows none. If it's an issue with the Gedcom, would the origin be with Ancestry, or with the software not recognising connections in the Gedcom correctly?

**Comment by ShammyLevva** [comment]
It’s because the data doesn’t exist in the GEDCOM file. I loaded the GEDCOM into Family Tree Maker and it showed no relationships. 

Try loading the GEDCOM into a family history program yourself. I don’t know why but the export missed some people that are the link to those who have blank relationships. 

You could force ancestry to generate a new GEDCOM for you. Although I’d hope you have your tree offline anyway as you should never rely on an online service as the only backup of your tree. 

To force an update clear the browser cache for ancestry website and it will think you’ve never downloaded before and give you a fresh clean copy.

**Comment by HistoryDiver** [comment]
Many thanks for checking! 

I’ve cleared the cache twice and downloaded fresh versions of the GEDCOM, but the issue persists, I’m wondering if there’s anything I can do with my Ancestry settings to fix things. Unfortunately I don’t have any desktop tree, the options for Mac users seemed quite limited so all my research was started on, and built on the Ancestry tree. With all the images and documents connected to my tree on Ancestry now it would be a big task to re-do it all with a desktop tree, so I’ve just stuck with Ancestry. 

Perhaps if I bought some software for a desktop tree it would get around the issue, but it would still entail downloading a GEDCOM from Ancestry. 

All the best!

John

On 27 Dec 2019, at 11:16, Alexander Bisset <notifications@github.com> wrote:

It’s because the data doesn’t exist in the GEDCOM file. I loaded the GEDCOM into Family Tree Maker and it showed no relationships.

Try loading the GEDCOM into a family history program yourself. I don’t know why but the export missed some people that are the link to those who have blank relationships.

You could force ancestry to generate a new GEDCOM for you. Although I’d hope you have your tree offline anyway as you should never rely on an online service as the only backup of your tree.

To force an update clear the browser cache for ancestry website and it will think you’ve never downloaded before and give you a fresh clean copy.

**Comment by ShammyLevva** [comment]
Did you try downloading your tree using a different browser (or Safari in private mode) so that it forced a new version of your tree does the error still exist?

**Comment by HistoryDiver** [comment]
His Alexander, 

Many thanks for following up with this. 

Yes I’m still encountering the same issue, but have tried a different browser to download - I’ll give that a go and report back. 

Hope you’re staying safe and healthy during this awful crisis. 

Warmest Wishes

John


On 12 Apr 2020, at 15:15, Alexander Bisset <notifications@github.com> wrote:


Did you try downloading your tree using a different browser (or Safari in private mode) so that it forced a new version of your tree does the error still exist?

**Comment by HistoryDiver** [comment]
Hi Alexander, 

I tried downloading with Safari (rather than my usual Firefox) and have a similar result, note the 90 unidentified relationships (these are not unlinked on my tree, only in this GEDcom):

I think I’m well overdue to invest in and start using a desktop Ancestry software for Macs, but I’m so used to just using the Ancestry online tree, it will be a great task to move focus away from that, and, despite the Covid lockdown, work deadlines loom!

All the best

John




On 12 Apr 2020, at 15:15, Alexander Bisset <notifications@github.com> wrote:


Did you try downloading your tree using a different browser (or Safari in private mode) so that it forced a new version of your tree does the error still exist?
