### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BobWhaley** [ShammyLevva/FTAnalyzer#152]
Family Tree Analyzer v7.4.2.0

When I export Locations to Excel, I find that the '.csv' file produced starts with three non-ASCII characters.  While Excel ignores these characters, it makes writing other analysis tools for the data difficult! The three characters are (in hex):
ef bb bf

**Comment by ShammyLevva** [comment]
That's not a bug that just means the file is a UTF-8 format file. ie: can contain text such as ć á é œ. If it wasn't an UTF-8 format then it would give erroneous data for people with non English letters in their names. ie: it would convert those characters into unreadable symbols. That annoys people who have such characters in their names or those who have ancestors with such characters.
