### ISSUE TITLE
[BUG] V 7.4.2.0

### ISSUE THREAD

**Issue by ThoThoMcNew** [ShammyLevva/FTAnalyzer#154]
**Version Number problem appears in** V 7.4.2.0
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug** I can't sign in to Lost Cousins to upload missing census data. I get error message "Unable to log in to Lost Cousins website. Check email/password and try again".

**To Reproduce**
1. Go to '...' Lost Cousins tab
2. Click on '....' Updates
3. Scroll down to '....' Lost Cousins Log in Details

**Expected behavior**
A clear and concise description of what you expected to happen. Not having used this program before I expect to see a method of uploading the census details found by FT Anlayzer which are not recorded on the Lost Cousins website 

**Screenshots**
![Lost Cousins FT Analyzer Problem](https://user-images.githubusercontent.com/59767964/72205570-95adb600-347c-11ea-8ece-c672ca66c116.JPG)

**Additional context**

**Comment by ShammyLevva** [comment]
If you go to www.lostcousins.com do those login details work?

The error is that the username or password is wrong. So you need to check on the lost cousins website that you are using the right login details.

**Comment by ThoThoMcNew** [comment]
Hello Alexander,

Thanks for the quick response. I am using the same login details as I 
use on the Lost Cousins website. I have just logged into that website 
and tried to connect FT Analyzer to it. I have tried this before but I 
still get the same error message i.e. check email/password and try 
again. Have you any other suggestions?

Regards,

Tom

------ Original Message ------

**Comment by ShammyLevva** [comment]
Very odd. I just tried logging in myself and could login to site and via FTAnalyzer using same username login details. Perhaps try cutting and pasting the login details from the login form on lost cousins website to make 100% sure they are correct both email and password.

Could it possibly be that something on your computer is preventing FTAnalyzer accessing the internet? It does of course need to do this to login to the lost cousins website. Perhaps a webfilter or firewall rule?

**Comment by ThoThoMcNew** [comment]
Hi Alexander,

I am 100% sure that I am using the correct Lost Cousins login details so 
I don't think that's the problem.

I have uninstalled and re-installed FTA just now. During this process 
(and initially in December) I had a security warning that the Publisher 
cannot be verified; I go ahead in any case. When I try to run the 
program Windows gives me warning to the effect that Windows Defender 
SmartScreen prevented the program from running. I over-ride this and 
obviously the program runs.

As an experienced pc user I know where to look for installed programs 
and FT Analyzer is in Programs and Features. The strange thing is I 
can't find where the program is actually installed so can't add it to my 
firewall allowed list. Can you suggest where I go from here? I assume it 
is installed somewhere.

------ Original Message ------

**Comment by ShammyLevva** [comment]
Microsoft Clickonce installs install in your personal profile in c:\users\<your user name here>\AppData\Local\Apps\2.0\<some random folder names>\ftan...<some random GUID>\

You might have multiple old versions Windows isn't very good about removing old ones.

**Comment by ThoThoMcNew** [comment]
Hi Alexander,

Ok. I've found FT analyzer down the path you gave. Hopefully the final 
problem is allowing it through Widows Firewall. In the firewall Allowed 
apps screen I can see there are numerous other applications there 
already but I've never had to add to this list as they all seem to be 
added automatically when installing. However my problem now is choosing 
which FT Analyzer file(s) to add. Which one(s) should I use?

------ Original Message ------

**Comment by ShammyLevva** [comment]
The executable file is the program that firewalls check so ftanalyzer.exe. 

If that fails try a trace using something like Fiddler 4 or WireShark to see what the program is doing and what response it's getting. You are using this on a home network not a corporate network?

**Comment by ThoThoMcNew** [comment]
Hi again,

I have added the exectuable file to Windows Defender but the Lost 
Cousins login still doesn't work and Fiddler 4 or WireShark are way 
above my head.

In desperation I have done a clean instal on another computer running w7 
but I still can't access Lost Cousins.

I appreciate your help but unless you have any other ideas we will have 
to leave this issue unresolved.

Thanks.

------ Original Message ------

**Comment by ShammyLevva** [comment]
Very odd. Unfortunately it's just working for me so it's very difficult to know what might be wrong if it's not working. Can I email you a test account details via private email that you can try to login just don't upload anything to it.

**Comment by ThoThoMcNew** [comment]
Test account a good idea to see if that works.

------ Original Message ------

**Comment by ShammyLevva** [comment]
Passwords in LC were restricted to 15 characters this caused the issue as users password was 20 characters long.
