### ISSUE TITLE
Potential Missing Children

### ISSUE THREAD

**Issue by brianyare** [ShammyLevva/FTAnalyzer#155]
May I suggest an additional report. If a couple marry but have no children for several years there could be a potential missing child. I would suggest that if the birth year of the oldest child is more than 3 years after the marriage date of the couple this could be flagged.

We have discussed this today on the FaceBook users' forum. 

I've extracted the following example from the families tab (extracted to Excel)

![FTA request](https://user-images.githubusercontent.com/60261801/73073837-e384de00-3ec0-11ea-91bb-7e7141345541.jpg)

**Comment by ShammyLevva** [comment]
Added in v7.6.4
