### ISSUE TITLE
FTA Analyzer Version 7.5.0.1

### ISSUE THREAD

**Issue by Chunky666** [ShammyLevva/FTAnalyzer#156]
Please help with the issue below:
Is there some sort of way of clearing the "cache"?  of the GEDCOM file as it keeps reporting back errors that no longer exist.

e.g I had an individual on the Lost Cousins website entered against the 1881 census.  I have since deleted their entry on the site as it was found to be wrong.  There is nothing against that individual in my Family Tree Maker file either - no fact entry or source.
They are still flagging up on the Report as a Lost Cousins w/bad census.
How would I clear these people as there appear to be a few people like that.

Many thanks

**Comment by ShammyLevva** [comment]
There isn’t a cache. The program loads whatever is in your GEDCOM.

Now that suggests two possible issues. 1) you are using a Ancestry and it has a habit of thinking you want the same file you last got even if you made changes in which case you need to clear browser cache for ancestry to force a fresh download or 2) you didn’t export a fresh GEDCOM file from Family Tree Maker for import into FTAnalyzer. 

Easiest way is to make sure your export file has a date stamp on it. Then import that file so you know it’s the right one.
