### ISSUE TITLE
[BUG] Leap Day crashed "On This Day"

### ISSUE THREAD

**Issue by Phantomsteve2001** [ShammyLevva/FTAnalyzer#157]
v7.6.1.0

**Describe the bug**
If you try to run the "On This Day" for a leap day (29th Feb 2020, 29th February 2016, etc) then an error occurs: "Unhandled exception has appeared in your application.
Year, Month, and Day parameters describe an un-representable DateTime"

**To Reproduce**
1. Go to 'On This Day'
2. Choose a Leap Day (29th Feb 2020/2016/2012/etc)
3. Keep the "Year Step" at the default 5 years
3. Click on 'Update list of Events'
4. Error above arises.

**Expected behavior**
For the software to be aware that if the date of 29th February is entered, the "Year Step" should be changed to 4, so it only checks leap years! (The issue doesn't arise if "Whole" month is selected rather than "Single Day")

**Screenshots**
See attached

**Additional context**
n/a
![Annotation 2020-02-29 221846](https://user-images.githubusercontent.com/46846498/75615968-7eb54700-5b42-11ea-9449-8c0dbb21dff5.png)

**Comment by ShammyLevva** [comment]
Good catch. The logic for leap year is even easier than that...

return DateTime.IsLeapYear(year)

Fixed in v7.6.1.1
