### ISSUE TITLE
[BUG]  Windows Size/Position Not Respected "Locations Geocoding Status Report"

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#158]
v7.6.1.0
**Bug Description**
The user defined window size/position of the "Locations Geocoding Status Report" is not respected.

Severity == Annoyance

**To Reproduce**
Goto Maps and sub menu item "Display Geocoded Locations".

Move and/or Resize the window.

Click the second button on the screen which, according to the mouse over, claims to just "Reset Column Sort Order to Default".  This moves the window to the top left corner of the desk top and resizes the window.

**Expected behavior**
Window size and position is respected. Just data sort order should change as per the tool tip for the button.

**Screenshots**

**Additional context**
The position/size of this window is also not preserved between uses of this wonderful program. If it could be, that would be a bonus :-)

**Comment by ShammyLevva** [comment]
Fixed in v7.6.4
