### ISSUE TITLE
FTA doesn't display surnames if they are in Brackets

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#159]
**Version Number problem appears in**
 v7.6.1.0

**Describe the bug**
When a mother's surname is unknown, I use the husbands surname in brackets, i.e. Jackie (Hardman).
Ancestry is happy with this and still searches for Jackie (Hardman) for records after they were married.
However FTA ignores the surname completely and reports the person as Jackie UNKNOWN

**To Reproduce**
Put brackets around a surname and export to FTA.

**Expected behavior**
I would like FTA to list this person as Jackie (Hardman).

**Screenshots**
From FTA
![image](https://user-images.githubusercontent.com/29726075/76092175-de827680-5fb6-11ea-9529-b818a46b48e0.png)

From FTM19
![image](https://user-images.githubusercontent.com/29726075/76092258-05d94380-5fb7-11ea-9afc-f0191522d23f.png)

From Ancestry
![image](https://user-images.githubusercontent.com/29726075/76092325-20132180-5fb7-11ea-831f-fefdfb3ed8e2.png)

**Comment by ShammyLevva** [comment]
Probably easiest to store a display surname and have an option to use display surname. The UNKNOWN has various meanings in the code.

**Comment by ShammyLevva** [comment]
Option was added in July 2015 :)
