### ISSUE TITLE
[BUG] Source list doesn't display correct # of citations

### ISSUE THREAD

**Issue by nconway567** [ShammyLevva/FTAnalyzer#160]
Version 7.6.1.1 - Windows version. Using the Main Lists, Sources Tab. Several sources display 0 facts. Some display a # of facts. The counts are all wrong - even in cases where it shows 0.  There are often source citations attached to the Person - not only facts such as birth, death etc.  I just went and updated a source that FTA shows I had attached to three people.  In reality, it was attached to a total of 15 people - but I had to manually search for them in roots magic.

Can this be fixed?  It's sort of misleading.

**Comment by ShammyLevva** [comment]
I’ve not seen this myself can you create a small test file that demonstrates the issue so I can narrow down what’s happening please. If you upload the test GEDCOM file here or email it.

**Comment by nconway567** [comment]
Attached is the Gedcom.  There's 4 individuals. FTA lists 38 Sources.  I specifically noticed one Ogle and Bothal (S325) is attached to King Edward III of England.  It's attached as a Person source and a Marriage source (to Phillipa of Hainault), but FTA shows zero count. In fact, 23 out of 38 sources are listed with a zero count.

Roots Magic doesn't have a function to show who each source is attached to yet, so the only way to figure it out is to use your program or manually search - in other words - manually search and pray you find 'em all.

Thanks
Nicole
________________________________

**Comment by ShammyLevva** [comment]
Thanks I’ll have a look after work tomorrow.

**Comment by ShammyLevva** [comment]
I'm ready to have a look but see no GEDCOM. I suspect you attached it in an email (which gets stripped by GitHub) rather than uploading to the issue page.

**Comment by nconway567** [comment]
Didnt realize that.  Here's the file!
[test export FTA.zip](https://github.com/ShammyLevva/FTAnalyzer/files/4394061/test.export.FTA.zip)

**Comment by ShammyLevva** [comment]
File received I'll have a look now.

**Comment by ShammyLevva** [comment]
Initial investigation suggests that all FACTS that have sources are working. RECORDS (ie: individuals and families) that have sources are not. This is because there isn't a "fact" to say a person or a family exists in the GEDCOM. So I think I'll need to create an "Individual" Fact and a "Family" fact to attach to records so that the sources can be tracked.

**Comment by nconway567** [comment]
It also appears that FTA doesn't recognize "shared" facts. I'll upload another small gedcom - in this one, I have a shared fact named "kinship" that I use to tie a direct line together, such as someone who's a descendant of a king, magna carta descendant, etc.  That fact is setup on most of the people in this gedcom - but it doesn't show up anywhere, even on the Stats page when it reads the file. I've also attached a 'test source' to this shared fact and that doesn't appear in the list of sources
[shared fact export.zip](https://github.com/ShammyLevva/FTAnalyzer/files/4394864/shared.fact.export.zip)

.
It seems like shared facts need to be added too?

**Comment by ShammyLevva** [comment]
It's that it doesn't recognise non standard fact types. Kinship is not a GEDCOM standard fact type so the likelihood is it's simply ignored.

**Comment by ShammyLevva** [comment]
I don't have RootMagic so if it load it to FTM it's likely to strip out exactly what we are trying to see. Can you give me a specific example from the shared fact export file of what you mean please.

**Comment by ShammyLevva** [comment]
Hmm it seems that Roots Magic is making stuff up out of whole cloth - it's almost as bad as Legacy in that regard. It's created a completely non-standard format that isn't supported called _EVDEF.

These are random extra tags dumped into the the GEDCOM that don't follow the GEDCOM standard at all. In fact the format explicitly breaks the GEDCOM standard for creating additional tags.

Not sure how I feel about that other than initial anger. My gut feeling just now is well if Legacy and Roots Magic creates crap and tries to tie there users into their program I should be actively working to prevent that and NOT support such blatant lock-ins. 

I've added the support for the standardised source records. I may NEVER add support for these deliberately standard breaking codes. I'm just not motivated to add these at present. Sorry.

**Comment by ShammyLevva** [comment]
Name sources added in v7.6.2

**Comment by nconway567** [comment]
Ha! Why am I not surprised.  Most of the bigger programs are using so much non standard stuff because the GEDCOM specs haven't been updated in years.  Lots of programs are supporting shared Facts nowadays. I believe you can "share" any of their pre-programmed facts, not just the ones I created,  because I've shared the residence fact and that's built in.

No worries on adding my custom built facts - I totally get your point of view.
________________________________

**Comment by ShammyLevva** [comment]
Most programs eg: FTM/Family Historian/GenoPro/Family Tree Builder/Reunion(Mac)/TreeView support custom facts and custom shared facts. ALL of those programs adhere to the GEDCOM standard and use a type of EVEN - to create a custom event. 

Legacy uses _EVENT_DEFN and _PLACE_DEFN and RootsMagic it seems uses _EVDEF as a custom tag.

The problem is these don't appear to be simple variants of the standard EVEN tag. They seem to be defining types of events the adding these custom fact definitions. So the normal GEDCOM would be:

1 EVEN Earl of Chester
2 TYPE Noble Title
2 DATE BET 24 NOV 1312 AND 1327

Which is a custom type of Noble Title with a description of Earl of Chester. Where as the custom events seem to define the structure of the event as in...

0 _EVDEF Kinship
1 TYPE P
1 TITL Kinship
1 ABBR Kinship
1 SENT [NEED TO DEFINE SENTENCE: Kinship]
1 ROLE Witness
1 PLAC N
1 DATE N
1 DESC Y

This isn't a "Kinship" event this is a definition of how to store Kinship data. This means it's describing a NEW data structure not just a standard fact. 

What I couldn't see in the file was where it applied this structure and how that was recorded. From the shared file who might have this fact applied and how does it look.

**Comment by nconway567** [comment]
Oddly, Noble Title is a custom fact I created.  RM's built in version is Title (Nobility).  But the code starting with 0 _EVDEF Kinship looks a lot like the Fact definition screen.  All the facts - built in or custom have those properties available.  Where the difference may lie is in the Role - Principal or Witness.  It may be that 'shared' facts are nothing more than a copy of a fact with a flag of Witness.



________________________________

**Comment by ShammyLevva** [comment]
So from the shared fact file you sent - what is an example of a shared fact - which Individuals (family group) has a specific fact so I can find it in the GEDCOM. I'm not yet aware of any specific example of a shared fact so I don't know what to look for.

**Comment by nconway567** [comment]
Kinship is a shared fact, in this case the description reads Magna Carta Descendants.  When I shared Kinship, I started with William Malet (b 1173) and copied it to all his direct line descendants until I reached Mark Hamill.  Not all those ppl are in the gedcom - Mark Richard Hamill has it, as well as his father, gfather, ggfather and GGGfather.

In the RM database, there is in fact a Witness table, with structure of WitnessID, EventID, PersonID, WitnessOrder, Role, Sentence, Note (blob), so I would bet shared facts are really just a copy operation with keys pointing to the Originating person and each witness of that fact.

________________________________

**Comment by ShammyLevva** [comment]
Mark Richard Hamill has...

0 @I69309@ INDI
1 NAME Mark Richard /Hamill/
2 GIVN Mark Richard
2 SURN Hamill
1 SEX M
1 _UID 432377DD4DE94DDC9CFC438CE659496B7307
1 CHAN
2 DATE 9 MAR 2020
1 BIRT
2 DATE 25 SEP 1951
2 PLAC Oakland, Alameda, California, United States
1 EVEN Actor
2 TYPE Celebrity
1 EVEN King Henry II of England
2 TYPE Notable Relations
1 FAMC @F22872@

So he appears in a single Family as a child that family has...

0 @F22872@ FAM
1 HUSB @I69307@
1 WIFE @I69308@
1 CHIL @I69309@
1 DIV
2 DATE JUN 1973
2 PLAC San Diego, California, United States
2 SOUR @S1222@
3 PAGE https://familysearch.org/ark:/61903/1:1:VPBD-5DN; Virginia S Johnson and William T Hamill, Jun 1973
3 _TMPLT
4 FIELD
5 NAME BookID
4 FIELD
5 NAME Page
4 FIELD
5 NAME EntryNo
5 VALUE https://familysearch.org/ark:/61903/1:1:VPBD-5DN
4 FIELD
5 NAME PersonID
5 VALUE Virginia S Johnson and William T Hamill, Jun 1973
4 FIELD
5 NAME Date

So it doesn't look like the shared fact appears anywhere in the standard GEDCOM - can you confirm that the fact definitely appears in that small sample file?

**Comment by ShammyLevva** [comment]
He's got two custom facts one of type Actor and one of type Notable Relations. However no Kinship fact I can see.

**Comment by nconway567** [comment]
Holy cow - Rootsmagic won't export out its own custom shared fact.  It strips it out of the gedcom on export or when you import it.  I just took that file I sent you and imported into a new RM database and the shared fact is not there.  Bastards!
Sorry to waste your time!!

[cid:e38b5791-47d4-41d8-8f54-0c94d34828a0]
________________________________

**Comment by ShammyLevva** [comment]
Lol ok that's bizarre. Sounds like you need to raise that with RootsMagic that's a bug if ever I heard one.

No time wasted it was interesting. I'll release v7.6.2 soon to fix the original issue of lacking source records.

**Comment by ShammyLevva** [comment]
Sadly if RootsMagic isn't going to write out the data there's no Jedi mind tricks I can add to the code to extract the data by FORCE. So unfortunately this is not the fix you are looking for.

**Comment by nconway567** [comment]
haha - I see what you did there.

I submitted a bug report. They are getting ready to release a new version so who knows if it's addressed already.  Having the Person sources in FTA will be a big help. Thanks for that.  Now if anyone knows of a utility that can fix all the random spaces in my notes that got broken when I imported that would be wonderful!

________________________________

**Comment by ShammyLevva** [comment]
Textpad is useful for that https://www.textpad.com/download/

It can do complex search and replaces to fix such things. You would need to copy and paste the text - fix it then copy and paste it back though.
