### ISSUE TITLE
Colour Census Report

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#163]
This is more of a question but could be a feature request. Using v7.6.3.0

On the Colour Census Report, when doing a double click on the 1881 census with FMP as the search source, the page that opens is the high level "Results for Census, land & surveys".

There is a specific one just for 1881 https://search.findmypast.co.uk/search-world-Records/1881-england-wales-and-scotland-census

Using William Ball b1862 in Lancashire, gets 1,161 search results and using the 1881 census gets 196 results.  

But the most significant difference between the 2 searches is when you go to the advance search section, to try and home in on your relative.  There are so many more fields to use to help narrow it down on the 1881 search compared to the other high level search where these fields are not available.

Was there a specific reason for not using the 1881 search for FMP (when selecting Ancestry it does go to the 1881 specific search page).

Maybe it was for ease of programming?  I notice you use the same high level search page for all census searches for FMP, just changing the census year.

Would you consider using the direct census searches rather than the general search?

Thanks.

**Comment by ShammyLevva** [comment]
Yup I can change this. I'm not sure if that link is changed when I originally created the auto linking. I'm aware some have changed over time. As you say I'd checked Ancestry as it has a different link.

Did you check the URL to see it takes the same parameters?

**Comment by Nichotj** [comment]
Yes it takes the same fields, but you won't need 1881 in the year field as the link only shows 1881 census.  This is for William Ball b1862.

Here's the url for the direct 1881 census search:
https://search.findmypast.co.uk/search-world-records/1881-england-wales-and-scotland-census?firstname=william&firstname_variants=true&lastname=ball&yearofbirth=1862&yearofbirth_offset=2

and here's the url for the general search:
https://www.findmypast.co.uk/search/results?sourcecategory=census%2c+land+%26+surveys&eventyear=1881&eventyear_offset=0&firstname=william&firstname_variants=true&lastname=ball+&lastname_variants=true&yearofbirth=1862+&yearofbirth_offset=2&sourcecountry=great+britain

**Comment by ShammyLevva** [comment]
Fixed in v7.6.5
