### ISSUE TITLE
Incompatible Census Ref errors upload to Lost Cousins

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#164]
v7.6.3.0

Before uploading to Lost Cousins I always check to see if there are records that won't load and can be fixed.
I now have some records that won't load and have been identified as incomplete. The issue could be on Ancestry's side (as seen all to often in the 1911 census) but just in case it's a data string format issue I thought I would raise it here.

Please ignore the 1911 line.
![image](https://user-images.githubusercontent.com/29726075/79213686-7fc7dc80-7e41-11ea-871c-6409a632f1ba.png)

I'll attempt to attach a gedcom with just these people in it.
[Incompatible census ref examples.txt](https://github.com/ShammyLevva/FTAnalyzer/files/4474673/Incompatible.census.ref.examples.txt)

Thanks

**Comment by ShammyLevva** [comment]
I am not currently aware of what a proper Canadian census looks like it seems to vary a lot.

**Comment by Nichotj** [comment]
Did the examples in the attached gedcom help?

**Comment by ShammyLevva** [comment]
Not really as they don't tell me what the numbers mean. What I need is some sort of documentation on a website that says here are examples of Canadian census records. Or a site that you can search for the census so I can do searches for John Smiths to get various references I can cut n paste to see formatting.

**Comment by ShammyLevva** [comment]
Fixed in v8.0.1
