### ISSUE TITLE
Unable to save config to file 

### ISSUE THREAD

**Issue by tbksoft** [ShammyLevva/FTAnalyzer#165]
Version 7.6.5.0

**Describe the bug**
FT Analyzer loads gedcom file then comes up with ==> Error was Failed to save settings; Unable to save config to file.
Pressing OK produces unhandled exception per screenshot 

![image](https://user-images.githubusercontent.com/63781341/79437483-263ee980-7fca-11ea-93d9-bedd50860d13.png)

This then exits the program, so I'm unable to use FTAnalyzer at all.

**Comment by tbksoft** [comment]
Hello,
I did have permissions for app to access file system turned off - but
unfortunately turning it on did not make any difference, same error occurs.
Incidentally, I do not have anything under the "Choose which apps can
access your file system" - no App Installer ON/OFF option, it is just blank.
Regards, Trevor

**Comment by tbksoft** [comment]
Further update - previous update was on my desktop - with no App Installer
on/off - and this failed, even with permission for app to access file
system turned on.
However, on my laptop, FTAnalyzer works fine - and it has App Installer ON
in settings, as well as permission for app to access file system turned on.
Regards, Trevor

**Comment by ShammyLevva** [comment]
Version 7.6.6 just published on App Store - worldwide roll out should be soon. Hopefully that's at least a fix enough to stop the crash.

**Comment by ShammyLevva** [comment]
Ah your update overlapped my comment. Interesting difference between laptop and PC. It looks like there might be some default Microsoft settings regarding the installer that's different on some machines. I'll need to see if I can read up on that.

**Comment by ShammyLevva** [comment]
Application cannot change permissions on user's machine. Crash fixed now warns.
