### ISSUE TITLE
Selecting Locations terminates program

### ISSUE THREAD

**Issue by gsinkinson** [ShammyLevva/FTAnalyzer#166]
Just installed 7.6.5.0
Loaded gedcom successfully - 25715 individuals
Clicked on Locations tab, it processed for a few seconds, then program terminated.

![Sinkinson_20200416](https://user-images.githubusercontent.com/32678943/79488369-a0319b80-7fe7-11ea-8040-f5e019895bf9.GIF)

Running Windows 10 Home 64-bit v1909 build 18363.720
Lenovo A530 Ideacentre Intel i3-4000M 2.40 GHz 6.00 GB ram

Any idea what I should check to determine the problem?

**Comment by ShammyLevva** [comment]
usually when the program terminates it pops up a dialog box with an exception warning. That box has a "details" button. It's the contents of the details button I need to determine the problem.

**Comment by ShammyLevva** [comment]
This was the windows store version? There's a newer version v7.6.6, with Microsoft and should be published within next 2 hours. That didn't look at locations tab though. 

I suspect there's a crash happening and just need the crash log to see what it says to determine the fix.

**Comment by ShammyLevva** [comment]
Just tried and failed to replicate the issue with my file. It is possible it's down to some location specific thing in your GEDCOM file. More likely it's some coding issue.

PS. Your dates that are of type "1993 1994 1995 1996" the standard GEDCOM format for those dates would be "BET 1993 AND 1996". To indicate between 1993 and 1996.

**Comment by gsinkinson** [comment]
This is coming from my iPad ...

Your response time, content, and application are FANTASTIC !!!

I was so terrified that I wouldn’t be able to use FTAnalyzer that I panicked.

I calmed down and checked the Event Viewer and found an application error relating to KERNELBASE.dll version 10.0.18362.719. Tried re-registering but that failed.

Currently running sfc /scannow to look for corruption. Will check back when that completes.

And thank you for the note about the date format. I believe they came from some old Ancestry items for phone directories. I did not know about using between. Will try to clean it all up when I get FTA back and working.

George E Sinkinson, III
gsinkinson@att.net
(330) 864-3430

**Comment by ShammyLevva** [comment]
I've released a possible patch to the Windows Store that should hopefully fix the issue. As I say I'm unable to replicate it at my end so it's difficult to tell if my fix caught every possible version of this problem. From reading up stuff it seems there are occasions when the font tries to get disposed of twice and that crashes the program.

So fingers crossed this patch v7.6.6 fixes the problem.

**Comment by gsinkinson** [comment]
Will try the new patch momentarily.

Do I need to uninstall the existing version and then attempt to download the new version from the Microsoft Store? I seem to remember it telling me it was already installed.

I’m waiting for my PC to reboot - it apparently was downloading and installing KB4559951 in the background.

The sfc /scannow turned up warnings about directories but indicated that errors were found and fixed. I can send the actual text if that helps, but to me it doesn’t seem to relate to my current problems.

After the sfc fixes, it threw a .NET exception. I can send the Details file if it helps.
Also have the Event Viewer note and will send it when my PC finally comes back.

If all else fails, and after I try the new fix, I’d be happy to send the GEDCOM file for you to beat up on. At least that way we find out if the error is in the file or on my machine

George E Sinkinson, III
gsinkinson@att.net
(330) 864-3430

**Comment by gsinkinson** [comment]
Alexander,

 

sfc /scannow finished with 13 Warnings about Directory Overlaps - owned twice or has its security set twice.
Windows Resource Protection found corrupt files and successfully repaired them.

rebooted PC and launched FTAnalyzer 7.6.5.0 and loaded GEDCOM
Used the Open GEDCOM option rather than the Recent files option

FTAnalyzer used about 26% of the CPU while loading then dropped to 0%

Ran export Errors/Fixes > Duplicates? 
Half way through got a Microsoft .NET Framework error


Details in FTA_NET_Notes file.
Selected Quit to close application



Re-launched FTAnalyzer
Clicked on Locations tab
Window closed - no error message

Event Viewer shows Application Error:

Faulting application name: FTAnalyzer.exe, version: 1.0.0.0, time stamp: 0x5e976cda

Faulting module name: KERNELBASE.dll, version: 10.0.18362.719, time stamp: 0xb31987d3

Exception code: 0xe0434352

Fault offset: 0x000000000003a859

Faulting process id: 0x1f70

Faulting application start time: 0x01d61451f4ceee41

Faulting application path: C:\Program Files\WindowsApps\26245AlexanderBisset.56195460DD6F1_7.6.5.0_x64__zhq5m3qz969ym\VFS\ProgramFilesX64\FTAnalyzer\FTAnalyzer\FTAnalyzer.exe

Faulting module path: C:\Windows\System32\KERNELBASE.dll

Report Id: 62279f99-ac7a-4e3b-b581-48ef641e52b3

Faulting package full name: 26245AlexanderBisset.56195460DD6F1_7.6.5.0_x64__zhq5m3qz969ym

Faulting package-relative application ID: FTANALYZER

Noticed Windows Modules Installer Working intermittently showing high (25%) CPU and Disk usage about the same time.
Confirmed 2020-04 Cumulative Update for Windows 10 Version 1909 for x64-based Systems (KB4549951) installing.

Rebooted PC several times to make sure everything was complete.

Uninstalled FTAnalyzer 7.6.5.0
Rebooted
Installed FTAnalyzer from Microsoft Store – shows version 7.6.5.0, not 7.6.6
Guess I’ll try for it tomorrow.

George

**Comment by ShammyLevva** [comment]
Yup Microsoft still have yet to release the new version. It's now middle of night in US (1:30am PDT vs 9:30am UK) So I don't expect them to look at this for another few hours at least.

**Comment by ShammyLevva** [comment]
It now says publishing to app store
![image](https://user-images.githubusercontent.com/29687786/79569058-d8e87800-80ae-11ea-9e78-a88a43430712.png)

**Comment by gsinkinson** [comment]
7.6.6.0 up and running.

No longer throwing exceptions in Duplicates?

 

Unfortunately, still problems with Locations.

Window closes without warning.

 

Event Viewer shows:
Faulting application name: FTAnalyzer.exe, version: 1.0.0.0, time stamp: 0x5e98e4da

Faulting module name: KERNELBASE.dll, version: 10.0.18362.778, time stamp: 0xafa78a6a

Exception code: 0xe0434352

Fault offset: 0x000000000003a799

Faulting process id: 0x181c

Faulting application start time: 0x01d614d08c829a05

Faulting application path: C:\Program Files\WindowsApps\26245AlexanderBisset.56195460DD6F1_7.6.6.0_x64__zhq5m3qz969ym\VFS\ProgramFilesX64\FTAnalyzer\FTAnalyzer\FTAnalyzer.exe

Faulting module path: C:\Windows\System32\KERNELBASE.dll

Report Id: 869142fb-4363-4108-929f-8736fbba2b5a

Faulting package full name: 26245AlexanderBisset.56195460DD6F1_7.6.6.0_x64__zhq5m3qz969ym

Faulting package-relative application ID: FTANALYZER

 

Is there an FTA log I can send you?
Or maybe my .ged file?

 

George

 

George E Sinkinson III

 <mailto:gsinkinson@att.net> gsinkinson@att.net

(330) 864-3430 home

(330) 573-8545 cell

**Comment by gsinkinson** [comment]
Also a .NET entry in Event Viewer:

 

Description: The process was terminated due to an unhandled exception.

Exception Info: System.OutOfMemoryException

   at System.Drawing.Graphics.FromHdcInternal(IntPtr)

   at System.Drawing.Font.GetHeight()

   at System.Drawing.Font.get_Height()

   at System.Windows.Forms.Control.get_FontHeight()

   at System.Windows.Forms.TextBoxBase.get_PreferredHeight()

   at System.Windows.Forms.TextBoxBase.get_DefaultSize()

   at System.Windows.Forms.Control..ctor(Boolean)

   at System.Windows.Forms.TextBoxBase..ctor()

   at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception)

   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)

   at System.Windows.Forms.Control.WndProcException(System.Exception)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG ByRef)

   at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32)

   at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext)

   at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext)

   at FTAnalyzer.Program.Main()

 

which I find a little odd – will try again with Task Manager active.

 

George E Sinkinson III

 <mailto:gsinkinson@att.net> gsinkinson@att.net

(330) 864-3430 home

(330) 573-8545 cell

**Comment by ShammyLevva** [comment]
When the program closes does it pop up a warning box about an unhandled exception? Or does it just close?

What's the steps to replicate this please? It will be something to do with the high res monitor needing fonts to scale. I've got a hi res monitor at work so I can potentially reproduce the error but it's not 4k so might not be able to reproduce. The key is step by step what happens to reproduce the error.

The gedcom may be useful to reproduce in case it's some oddity like a normally unprintable character (or one that doesn't exist in a font) that's causing the issue. I've seen such things with names/places with accents and things like that.

email file to ftanalyzer@gmail.com if you wish.

**Comment by gsinkinson** [comment]
It appears the .NET error precedes the Application error.



 

Is there anything I can send that might help?

**Comment by ShammyLevva** [comment]
Fixed in v7.7.0
