### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SPRSW** [ShammyLevva/FTAnalyzer#167]
Version 7.7.1.0
Description:
On Facts tab.  In the Fact Selection box, the 1st field in list (mine is Alternate names ) does not seem to be Selectable/De-Selectable. The others in list are.  Is this correct?  I know I can De-Select All and manually re-select all the others as a work 

**To Reproduce**
1. Go to 'Facts Tab).
2. Go to the Fact Selection Box
3. Try to De-Select First field in Fact Selection list

**Expected behavior**
Should be able to De-Select 1st field (Alternate names) before submitting report.

**Comment by Nichotj** [comment]
The 1st in the list for me is Adoption, I can't select it i.e. 1st line either.

**Comment by ShammyLevva** [comment]
Thanks for the report looks like a zero indexing bug. I’ll investigate.

**Comment by ShammyLevva** [comment]
Fixed in v7.7.2

**Comment by SPRSW** [comment]
Thanks

     On Friday, April 24, 2020, 01:03:51 PM EDT, Alexander Bisset <notifications@github.com> wrote:  
 
 


Fixed in v7.7.2
