### ISSUE TITLE
Baptism before Birth

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#169]
Quite often Baptism records are found after the initial person record is created. Sometimes you forget to update the birth date fact and so a report in the Error/Fixes tab would be useful to highlight all your entries which have a birthdate year greater than the baptism year.

![image](https://user-images.githubusercontent.com/29726075/81057837-1d548000-8ec5-11ea-9c73-9ade579c3f72.png)

**Comment by ShammyLevva** [comment]
Try this beta version - can you check other error facts haven't got wrong type as I added this at start as it makes sense to be in with other birth fact errors and nicely completes the suite - just missed as already have death after burial/cremation. Although I guess it would be possible if somewhat gruesome to have recorded a death after burial (Victorian grave watching and coffins with bells come to mind).

**Comment by ShammyLevva** [comment]
fixed in v7.8.1
