### ISSUE TITLE
FT Analyzer version v7.8.5.0.   I installed the program, imported a GEDCOM, and the tool went to work analyzing my file.  At the end of the analysis, I get the error message "failed to save settings.  Unable to save config to file"   It provide a path, which didn't exist initially, but I created it, still the same problem.

### ISSUE THREAD

**Issue by jonsmith1234** [ShammyLevva/FTAnalyzer#181]
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jonsmith1234** [comment]
![FT Analyzer error](https://user-images.githubusercontent.com/69653902/90193778-a831fa00-dd93-11ea-9179-e6e851d76310.png)

**Comment by jonsmith1234** [comment]
New to Github, must have clicked on something accidentally, issue is not resolved.

**Comment by ShammyLevva** [comment]
Yup known issue there is a Microsoft store repair tool see article on front page of website www.ftanalyzer.com for link. 

If that doesn’t work you will need to use the release version. It’s something to do with the Microsoft store installer not giving you permission to update settings on your own machine. However unfortunately I’ve never been able to reproduce the problem on any of my machines so cannot discover a fix, other than trying Microsofts own store repair tool, which various articles suggest will fix it.

**Comment by ShammyLevva** [comment]
The release version is at www.ftanalyzer.com is exactly the same program but is a manual install/update rather than using store install.

**Comment by jonsmith1234** [comment]
The repair tool did not work, but the manual release did, so I'm up and working!   This is a very cool program, thanks for creating.
