### ISSUE TITLE
Error listing duplicates and"bad pointer value"

### ISSUE THREAD

**Issue by lshep0921** [ShammyLevva/FTAnalyzer#182]
Not sure how to go about fixing this:
---------------------------------------------------------------------------
Loading file C:\Users\lshep\Documents\shepherd04.ged
Invalid GEDCOM, Line: 2026252: '@992'. Error was: Bad pointer value
---------------------------------------------------------------------------
Also, after 2 times of identifying duplicates, and fixing them in RootsMagic, I am getting the "unhandled exception" dialog.
and no possible duplicates are listed. Any ideas as to how to get around this?

Thanks,
Lou

**Comment by ShammyLevva** [comment]
Bad pointer is a line that has a @something in it that the GEDCOM mistakes for a link to another record. The line number tells you which line in the file it is. From that you can see who the individual is. 

An unhandled exception in duplicates shouldn’t happen. Can you confirm the version number and send me the file to ftanalyzer@gmail.com for analysis.

**Comment by lshep0921** [comment]
Hi Alexander,
It turns out that there was a marriage date of @992 in the offending line which I corrected in RootsMagic to 992. That little bit has corrected everything including the error on duplicates.
Thanks for your help.
Lou

    On Sunday, August 16, 2020, 09:07:53 PM EDT, Alexander Bisset <notifications@github.com> wrote:  
 
 


Bad pointer is a line that has a @something in it that the GEDCOM mistakes for a link to another record. The line number tells you which line in the file it is. From that you can see who the individual is.

An unhandled exception in duplicates shouldn’t happen. Can you confirm the version number and send me the file to ftanalyzer@gmail.com for analysis.

**Comment by ShammyLevva** [comment]
send to ftanalyzer@gmail.com if you could please.
