### ISSUE TITLE
Microsoft Font Error - Opening Errors/Fixes tab causes unhandled exception [BUG] 

### ISSUE THREAD

**Issue by SeekerFTA** [ShammyLevva/FTAnalyzer#186]
Version No v8.0.1.0

Load the gedcom file, click on Errors/Fixes tab and error message appears:
![image](https://user-images.githubusercontent.com/65892379/93060051-84e7bc80-f669-11ea-87c9-6195d73c67f0.png)

**Expected behavior**
List of errors and possible fixes

Have to click Quit. Clicking on Continue just brings the same screen up.
Are there any log files? The error message is long, and the window won't expand to allow a bigger screen shot.

**Comment by SeekerFTA** [comment]
Just tried again and it's worked!
I don't know what the difference was.

**Comment by ShammyLevva** [comment]
Unfortunately this is a Microsoft bug that is what is known as a "race" condition, something happens during the time it's trying to draw the window that causes it to get rid of the font used to draw the text in bold before it's finished drawing all the text. The result is this exception. As you noted the weird thing is it can work find 99 times in a row then one time it will error.

**Comment by ShammyLevva** [comment]
Reworked font handling in v8.4 hopefully fixes this.
