### ISSUE TITLE
Gedcom doesn't transferr correctly to FTA

### ISSUE THREAD

**Issue by Marykf** [ShammyLevva/FTAnalyzer#189]
I did a Gedcom and discovered a lot of unconnected people.  I worked at attaching these people as best I could and then wanted to see how I was progressing.  FTA keeps telling me that several of the people are still unattached when the gedcom says they are related to me.  I have done at least 3 gedcoms, saved them in different areas, discontinued the program and reinstalled it--all to no avail.  I did the above after shutting down completely and then restarting--hopefully to clear up the old gedcom.  It just keeps reusing the first one.  Any suggestions?   sunbeamf@att.net

**Comment by ShammyLevva** [comment]
Sorry I don’t understand why why WHY would you uninstall a program and expect the loading of a file to change that is simply nonsensical. It does not and CANNOT work with ANY program that exists. Uninstalling should be the absolute resort when the application itself isn’t loading it should NEVER EVER be the first thing you try. Indeed it shouldn’t even be in the first 100 things you try. 

Ok so now that is out of the way (a top ten hate of mine users uninstalling thinking that helps, when it absolutely does not) what exactly is the problem?

It sounds like you didn’t generate a new GEDCOM file so my guess is you use Ancestry and didn’t know they Ancestry needs to be told to delete the old version before they create a new one. Is this the case is it Ancestry you use to edit your tree?

If so you need to tell Ancestry to regenerate the file. Ancestry GEDCOM production is a two step process, step 1 you generate the file, step 2 you download it. If you just go back to the page after making changes it will only offer you step two which downloads the original file again. I know this is REALLY bad design by Ancestry but yes they are that bad at writing software.

The easiest way to create a new GEDCOM from Ancestry is to clear the browser cookies or to use incognito mode. 

If you aren’t an Ancestry user can you explain what software you use and how you generate the GEDCOM file. The solution is in how the GEDCOM is generated as if the file doesn’t change then it doesn’t matter how many times you load it or how many times you uninstall NOTHING will change the result.

**Comment by Marykf** [comment]
I do use Ancestry.  I did the new gedcom and opened it separately to see if the family that I attached was attached in the new gedcom.  According to Ancestry they were attached.  But when I ran FTA they popped up as unattached.  I also generated a gedcom from anew version of the same tree and again FTA said unattached.  The reason I uninstalled and reinstalled was an attempt to start fresh.  I am sorry that made you mad.  Should I delete all the gedcoms that I have saved on my computer and start fresh?
Mary K

**Comment by Marykf** [comment]
I’m sorry I misspoke.  I used FTM 2019 to make the gedcoms.  Do you think I need to delete the saved gedcoms?  I tried using the FTM kinship report to find the unattached using their instructional but according to that I don’t have any unattached.  Very very strange.
Mary K

**Comment by ShammyLevva** [comment]
A GEDCOM file is just a text file like any text file it can't do anything if you don't use it so it can have no effect on anything if it's not the GEDCOM you are loading in.

So the key is you export a file from FTM and make careful note of the location and the date and time you saved the file. Then when you click in FTAnalyzer to open the file you can make 100% sure you are loading the file you just created. 

From what you describe it sounds like you are not loading the file you just saved if you aren't checking the date on the file this will happen. By default FTM puts the date and time in the file name so just use the default filename to make sure you know you have the latest version.

**Comment by Marykf** [comment]
I give them separate file names so that I know I am using the latest version.  It still does it.

**Comment by ShammyLevva** [comment]
Can you send a GEDCOM to ftanalyzer@gmail.com so I can have a look and let me know what people are attached in FTM that are not attached in the GEDCOM file.

I've got FTM 2019 so will be able to check in FTM and FTAnalyzer.

**Comment by ShammyLevva** [comment]
Discussed via email. Issue related to terminology.
