### ISSUE TITLE
World Wars Tab

### ISSUE THREAD

**Issue by BobWhaley** [ShammyLevva/FTAnalyzer#192]
I tried to use the World Wars tab.  It works fine until I tick the 'Limit Results to only those men with Military Facts'. At this point, the number of results decreases to zero.  That probably means that I do not know the fact name that I have to type into my family tree.
Please advise me!

Also, that tick box refers to 'men'.  What about women who served, for example in the Womens Royal Air Force?

**Comment by ShammyLevva** [comment]
A Military fact is one with a standard GEDCOM military fact (has the tag _MILT) or has a standard GEDCOM military service number (has the tag _MILTID). So It may be your software hasn't got those specific tags as whilst they are part of the standard their use is not widespread.

The point of the report is to show possible candidates for searching for military records in those periods. Whilst there are of course women who served, and of course they should be researched and recognised, it would defeat the usefulness of the report to include women as it would make the number of false matches too high.

**Comment by EmmArrBee** [comment]
Alexander, 

Surely a GEDCOM tag beginning with an underscore is only standard in as far as it complies with the convention for NON standard tags.

Martin

**Comment by ShammyLevva** [comment]
Indeed it's part of the extended standard - used by Ancestry/FTM/Family Historian/Legacy and others.

**Comment by BobWhaley** [comment]
Thanks for the information.  After blundering around for a while, I found what I needed to do to make GEDCOM military facts appear in my tree.

 

Regards

Bob Whaley
