### ISSUE TITLE
Thinking ahead....1921 Census

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#193]
In just over a year (2022), they will be making the 1921 census available to the public.
Some of the reports will be needed to be updated, I believe the ref is RG15
:)

**Comment by ShammyLevva** [comment]
Added support for 1921 in v8.1.0

**Comment by PatReynolds** [comment]
Hi @ShammyLevva have you got the geographic hierachy for the 1921 census - before we build one ourselves - thanks, Pat

**Comment by ShammyLevva** [comment]
Geographic hierarchy? Not sure I know what you are referring to. There was a 4 character district code for the 1911 but I didn’t notice that it was hierarchical.

**Comment by PatReynolds** [comment]
e.g. for the 1841 census it is hundreds > parishes, but for later 19th century it is Registration Districts > Registration Sub-districts > Civil and Ecclesiastical Parishes.

**Comment by ShammyLevva** [comment]
Yes but I don’t understand where FTAnalyzer would actively use the information and how it would present it. In the past I’ve used the 1911 codes to identify areas but I don’t recall doing much with that information other than for census reference links.
