### ISSUE TITLE
Adopted children

### ISSUE THREAD

**Issue by Mezentia** [ShammyLevva/FTAnalyzer#194]
An adopted child may be reported as having a birth before mother aged 13. Is it possible to check if a child is adopted before reporting this error?

**Comment by ShammyLevva** [comment]
Surely it’s still an error the adoption cannot have taken place when the mother was just 13?

**Comment by Mezentia** [comment]
Hello Alexander

The only facts we have at the moment (and these need still to be confirmed) is that the difference in the ages of the adoptive mother and adopted child is 12 years.  We have neither the date of the adoption or the age of the child when adopted. The child may well have been adopted when she was 7 or 8 years old. The circumstances behind the adoption are not known, and it may well be that the parents of the adopted child had both died or suffered some other misfortune. All we know otherwise is that the child appears on the 1851 census age 9 as an adopted daughter. Hence my suggestion that the “birth before mother aged 13” error when the child is adopted is perhaps not always correct. Adoptions were certainly not as formal in the mid-1800s as they are today, so there is probably no formal evidence of the adoption anyway.

Out of interest, are you related to the Margaret Elizabeth Bissett, who married Herbert Mortimer Stonter in New Zealand?

Kind regards

David Dewick

**Comment by ShammyLevva** [comment]
I'm going to close this as a valid warning to check the data. It sounds highly suspect that an adoption could take place when the adoptive mother is 12. So it's perfectly valid to warn you to check that. As with all warnings there are exceptions to the rule, and you can and should choose to ignore the warning where there is such an exception. 

This is an example of precisely why the program only ever recommends a course of action it never takes action as it must always be the tree owner that decides if the warning is valid or not.


Re: Margaret Bisset, I'm not aware of any links to family in New Zealand sorry.
