### ISSUE TITLE
Add an excel export button on Surnames page/Tab.

### ISSUE THREAD

**Issue by petrolhead276** [ShammyLevva/FTAnalyzer#196]
I would like to export to Excel the surnames list from FTA, however I see no excel export button.

Ideally I would like to be able export all names either for a given type or all types and have the relationship type in the exported list, which I can then create a pivot table of to analyse the data in different ways.

is it possible to add one of your handy little excel export buttons to this page please.

thanks Dave

**Comment by ShammyLevva** [comment]
Added in v8.1.0
