### ISSUE TITLE
Missing Facts?

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#199]
I'm not sure if this a bug or not, it might be deliberate.

Not all the facts I have in my tree appear in the Facts Tab in FTA.
example:
I use the fact "Also Known As"

In the gedcom as:
1 NAME Max
2 TYPE aka

I think all Fact Types used in the tree should be displayed in the Facts List.

**Comment by ShammyLevva** [comment]
A name fact is special it provides the persons name so isn’t usually listed as a fact. 

An alias normally uses a ALIA fact type although I added support for recognition of the type appearing after a name fact. I can’t remember what options were permitted though.

**Comment by ShammyLevva** [comment]
Hmm I realised I'd never actually dealt with alternate facts. There is a checkbox in the reports to say if a fact is preferred or not however for every single old build up to v8.2.0.0 it's only ever allowed you to see preferred facts. Name was always a preferred fact.

There is a new option in v8.2.0 to show alternate facts. In your tree that goes from 37k facts to 64k facts. Bye bye life, as you check the alternates. LOL.
