### ISSUE TITLE
"Solo" families won't show details

### ISSUE THREAD

**Issue by ShammyLevva** [ShammyLevva/FTAnalyzer#2]
Double-clicking on a "Solo" family in the family tab doesn't show any Facts for the person.

**Comment by fire-eggs** [comment]
Doesn't fail if only one "Solo" family. If there is more than one Solo family, always shows facts from the first listed family.

So I must have reported this when I had more than one Solo "family", and the first "family" had no facts.

**Comment by ShammyLevva** [comment]
Fixed in v6.1.0.0
