### ISSUE TITLE
On This Day Stopped Working

### ISSUE THREAD

**Issue by JeffreyMGeorge** [ShammyLevva/FTAnalyzer#20]
As of yesterday (20-Feb-18) the On This Day tool stopped listing any events for me. The screen header comes up but no details are listed.

**Comment by ShammyLevva** [comment]
That’s with the update to v6.2.0.0?

**Comment by JeffreyMGeorge** [comment]
Correct. I'm not sure when it updated to that version, but that's the version I'm running.

**Comment by ShammyLevva** [comment]
Fixed in v6.2.1

**Comment by JeffreyMGeorge** [comment]
Thank you!
