### ISSUE TITLE
Missing Children Status report

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#201]
Ver 8.1.1

The report displays people who were alive on the 1911 census but who got married after 1911

![image](https://user-images.githubusercontent.com/29726075/106618327-3dee5b00-6567-11eb-9ea4-8c9064d6c284.png)

As they're not married in 1911, there is no Children Status to record, and therefore shouldn't be displayed on the report.

**Comment by ShammyLevva** [comment]
Updated for v8.1.2
