### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by philphil61** [ShammyLevva/FTAnalyzer#202]
**Version Number problem appears in v8.1.2.0**

**Describe the bug**
According to Microsoft Store v8.1.2.3 is the latest / updated version - I can't get the update 

**To Reproduce**
I tried uninstalling 
Right click select uninstall 
Go to Microsoft Store
Install FTAnalyzer
Still showing v8.1.2.0 (as previously installed 

**Expected behavior**
Not a major problem - just posting to make you aware.

**Screenshots**
None

**Additional context**
This is for information only.

**Comment by ShammyLevva** [comment]
Current version is v8.1.2 released yesterday 3rd February. There is no version v8.1.2.3.
