### ISSUE TITLE
Error loading previously submitted Lost Cousins data.

### ISSUE THREAD

**Issue by BrymanNZ** [ShammyLevva/FTAnalyzer#204]
Loading a newly generated Gedcom file to v8.3.0.0 I get SQL logic error for no such column: FullName

This is a reopen of issue #143 which was not resolved.

**Comment by ShammyLevva** [comment]
Hmm I could have sworn I added a check for that. I suspect the issue is to do with your database version being different from what the file says.

Can you send me the current database file - file menu and backup database - email to ftanalyzer@gmail.com and I can see what's going on.

**Comment by ShammyLevva** [comment]
Fixed for v8.3.1
