### ISSUE TITLE
1939 register and death dates

### ISSUE THREAD

**Issue by Scottishrod** [ShammyLevva/FTAnalyzer#206]
Version Number 8.3.0.
On errors/fixes I have 3 individuals who have "On the 1939 National Register but birth date is not exact" under description. For all 3 entries the "Fact created by FTAnalyzer" is recorded. Two of the individuals died before 29 Sep 1939 started as indicated in death dates below?

On 1939 Register no precise birthdate 
William Edward Rowling 
On the 1939 National Register but birth date is not exact 
SEP 1880 (Born) 
20 MAY 1910 (Died) 
On 1939 Register no precise birthdate 

Albert Banks 
On the 1939 National Register but birth date is not exact
1897 (Born)
29 APR 1938 (Died)
Albert Banks

If a death date is before 29 Sep 1939, when the register started, the 1939 register entry should not be added to FTA file.
GEDCOM from TMG in which all dates are either dd Mmm YYYY, Mmm YYYY or YYYY format.

**Comment by ShammyLevva** [comment]
It must be creating the facts in error for some reason. If you can supply a sample GEDCOM for a couple of individuals that will help. I note you emailed but there was no attachment.

**Comment by Scottishrod** [comment]
Apologies, my errors.

Rod
------ Original Message ------

**Comment by ShammyLevva** [comment]
No problem if you could email me the test file that would be very useful.

**Comment by ShammyLevva** [comment]
Hi Rod, Any chance of getting that file?

**Comment by Scottishrod** [comment]
Not sure what is happening but I sent the repeat file on 2 Mar.

Rod
------ Original Message ------

**Comment by ShammyLevva** [comment]
Nope no email on 2nd March sent to ftanalyzer@gmail.com - did you send it somewhere else?

**Comment by ShammyLevva** [comment]
File now received thanks.

**Comment by ShammyLevva** [comment]
It seems that Alfred has a source record in his name that has a 1939 census ref so I was creating a census record for him.

I've added a fix so that created records don't get added if person dead by that census. Fixed in v8.3.1
