### ISSUE TITLE
Colour Census Report

### ISSUE THREAD

**Issue by BobWhaley** [ShammyLevva/FTAnalyzer#207]
In FTA version v8.3.0.0, the Colour Census Report appears to produce odd results. In some cases it gives one non-red coloured block for a person and only red blocks for other people even if the GEDCOM has census entries.

I have checked the GEDCOM file and the census entries are in the form:
2 TYPE Census 1901
2 DATE 1901
2 PLAC 41 Penrhyn Road, Kingston upon Thames, Surrey, England
1 EVEN Retired Auctioneer

**Comment by ShammyLevva** [comment]
Are you able to produce a sample GEDCOM for a couple of individuals that demonstrate the issue. That way I can load the file see the issue and understand where the problem may lie. Note GitHub won’t allow a .ged file so you can email it to ftanalyzer@gmail.com

**Comment by ShammyLevva** [comment]
Hi Bob, any chance of getting that file?

**Comment by ShammyLevva** [comment]
Thanks but the provided file doesn't show the issue

![image](https://user-images.githubusercontent.com/29687786/110967528-616aa980-834e-11eb-86b5-bbfc463936df.png)

**Comment by BobWhaley** [comment]
I have uninstalled v8.3.0.0 and then installed it again from the Microsoft store.

 

The options on load are:

The current file handling options are set :

    Retry failed lines by looking for bad line breaks: False

    Convert Diacritics on load True

The current general options are set:

    Use Baptism/Christening Date If No Birth Date: True

    Use Burial/Cremation Date If No Death Date: True

    Allow Empty Values In Locations: False

    Show Multiple Fact Forms When Viewing Duplicates: True

    Loose Birth Minimum Parental Age: 16

    Show Alias In Name Displays: False

    Files use Country First Locations: False

    Show World Events on the 'On This Day' tab: True

    Ignore Unknown/Custom Fact Type Warnings: False

    Treat Female Surnames as Unknown: True

    Show Ancestors that are muliple directs: False

    Hide Ignored Duplicates: True

The current census options are set:

    Treat Residence Facts As Census Facts: True

    Convert Residences with valid census reference to Census Facts: True

    Tolerate Slightly Inaccurate Census Dates: True

    Family Census Facts Apply To Only Parents: False

    Use Compact Census References: False

    Auto Create Census Events from Notes & Sources: True

    Add Auto Created Census Locations to Locations List: True

    Hide People Tagged As Missing From Census: True

    Skip Checking for Census References: False

The current mapping options are set:

    Custom Maps Location: 

    Display British Parish Boundaries: False

    Hide Scale Bar: False

    Include Locations with Partial Match Status: True

 

 

However loading the sample .ged shows the following:

 



Regards

Bob Whaley

**Comment by ShammyLevva** [comment]
Fixed in v8.3.1.
