### ISSUE TITLE
Suggestion - Facts Tab Reporting

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#21]
Hi Shammy,

On the Facts tab, is it possible to have a tick box to show the opposite of the current reports?
What I was thinking of doing was creating a custom fact along the lines Completed or End of Tree, and add it to those people that died, or married people with no children etc.  Running the report and showing me the people who **didn't** have this custom fact would then be very useful to identify people who need further research.  It would also lend itself to other Facts, such as Direct Ancestors where occupation hasn't been added etc.

Thanks,

Tim

**Comment by ShammyLevva** [comment]
Again not sure when I added this but I just tried and was able to tick Lost Cousins facts in include and Census in Exclude to get list of people with a Lost Cousins fact but no census fact.
