### ISSUE TITLE
Data not loaded correctly from csv export file[BUG] 

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#216]
v8.3.1.0 Win 10

When importing the .csv file into Excel, not all data is imported into the correct column. Some bits of data are missing an end " and this forces the reminder of the data to be entered on a new row.

This is an example of a bad line from NotePad+

"I01971","Charnock","Alice","BEF 23 JUN 1771","Charnock","Baptism","23 JUN 1771","Blood Relation","4th great grandaunt","Rivington, Lancashire, England","Unknown","GEDCOM/User Data","","","","","","3","England, Select Births and Christenings, 1538-1975
Lancashire, England, Baptisms, Marriages and Burials, 1538-1812
Manchester, England, Baptisms, Marriages and Burials, 1541-1812","53.6239","-2.5635","True","False",""

Another one

"I02067","Charnock","James","BEF 21 JUN 1799","Charnock","Birth","BEF 21 JUN 1799","Blood Relation","1st cousin 5 times removed","Lathom, Lancashire, England","0","GEDCOM/User Data","","","","","","6","1841 England Census
1851 England Census
1861 England Census
1871 England Census
England & Wales, FreeBMD Death Index, 1837-1915
Lancashire, England, Deaths and Burials, 1813-1986","53.5883","-2.8233","True","False",""

How it loads in Excel
![image](https://user-images.githubusercontent.com/29726075/112727591-168a8d80-8f1b-11eb-948a-66f09c62e29a.png)

An example of a good line:

"I08067","Kirby","Elizabeth Ann","25 JAN 1863","Kirby","Baptism","24 FEB 1863","Blood Relation","2nd cousin 3 times removed","Wesleyan, Garston, Lancashire, England","< 1","Not Searched","","","","","","1","England, Select Births and Christenings, 1538-1975","0","0","True","False",""

In the bad line, it's like it's missing a " after 1538-1975, again after 1538-1812

The commas can't be throwing it as they also appear in the good line.

I'll email you the file.

**Comment by ShammyLevva** [comment]
The 

"1841 England Census
1851 England Census
1861 England Census
1871 England Census
England & Wales, FreeBMD Death Index, 1837-1915
Lancashire, England, Deaths and Burials, 1813-1986"

For example is the sources splitting over several lines. - looks like the sources needs any line breaks removes and an alternate character put in.

**Comment by Nichotj** [comment]
Good spot,  it looks like anywhere where the sources count is greater than 1 gets this issue
![image](https://user-images.githubusercontent.com/29726075/112751598-c5d06e80-8fc6-11eb-946e-a8c5dab2a108.png)

**Comment by Nichotj** [comment]
For the sake of clarity, this export is from the Facts Tab, Select all Fact Types, run the report, and then download that report as a .csv via the icon on the report.

This is **not** the report from the Export Menu option, Facts to Excel

**Comment by ShammyLevva** [comment]
Fixed for v8.4.0
