### ISSUE TITLE
[BUG] Cannot build, because of missing FTAnalyser/Mapping/GoogleAPIKey.cs

### ISSUE THREAD

**Issue by ennoborg** [ShammyLevva/FTAnalyzer#218]
** master **

**Describe the bug**
When I rebuild, Visual Studio tells me that source file FTAnalyser/Mapping/GoogleAPIKey.cs is missing.

**To Reproduce**
1. Rebuild solution,
2. See error

**Expected behavior**
A working build.

**Additional context**
Other code is still referencing the GoogleAPIKey class, and so is the project file.

**Comment by ShammyLevva** [comment]
File had my private key in it. I added a version without my private key that then broke the code for users. 

Developers can access the code via deleted version https://github.com/ShammyLevva/FTAnalyzer/commit/e647a00247ad8fee7b6c5647b10ec0ae38256798
