### ISSUE TITLE
Update documentation showing how to setup GRAMPS for the Lost Cousins feature

### ISSUE THREAD

**Issue by redMGB** [ShammyLevva/FTAnalyzer#22]
Please update the documentation showing how to set the 'Lost Cousins' flag within the GRAMPS genealogy software.  The following suggested text describes how this can be achieved:

In GRAMPS select the required person record.  Add a new 'EVENT' record for this person.  In EVENT there is an 'Event Type' field with predefined types accessed using a drop-down button.  You can override the predefined items by simply typing a new type into the field.  Type 'Lost Cousins' (without the quotes) into this field ignoring the audible warnings when you type.  Then enter the relevant census year into the date field for this new Event.  Click OK, and then OK again to update the person record with this new 'Lost Cousins entry.  GRAMPS also adds  'Lost Cousins'  to the valid Event Types, so from this point onward you can access it by starting to type 'Lost Cousins' into the field and selecting 'Lost Cousins', or you can access it from the drop-down and selecting CUSTOM, then 'Lost Cousins'.

**Comment by ShammyLevva** [comment]
added
