### ISSUE TITLE
RD interpreted as Rd

### ISSUE THREAD

**Issue by tamlla** [ShammyLevva/FTAnalyzer#222]
I’ve used FTA against a Gedcom from FamilyTreeMaker in which I have lots of entries in ‘place’ which hold the name of an English Registration District – e.g. for a marriage fact  “Date: 1987; Place: Bethnal Green RD; Description; [blank]” because I don’t know the exact date nor the actual place; the only information is an entry in the General Register Office index. FTA shows this in the list of places as if it were a road – “Bethnal Green Rd”. But perhaps that’s something that the export to Gedcom from FTM does?

**Comment by ShammyLevva** [comment]
That might be how FTM exports as it does look awfully like road to the untrained eye. 

How exactly does it appear in the GEDCOM file. I'm assuming it's something like

1 MARR
2 DATE 1987
2 PLAC Bethnal Green RD

ie: it's got nothing else to go on?

A more precise entry would be 

2 PLAC Bethnal Green RD, London, England

or more natrually

2 PLAC Bethnal Green, London, England

There is nothing more that I can imagine FTAnalyzer could do to the place as if it does appear without any additional information as there's nothing to go on to assist the fix, especially as Bethnal Green Road exists. So that could have been what the user meant. I appreciate it wasn't in this case but how could the program tell with nothing to go on?

**Comment by ShammyLevva** [comment]
Note in FTM it would be trivial to fix this problem by doing a replace of one location changing Bethnal Green RD to Bethnal Green, London, England and FTM will popup and say you have X number of records at that location do you want to change them all, say yes and hey presto you fixed them all.

**Comment by EmmArrBee** [comment]
That may work in this instance. But it might be safer to replace RD by
"Reg.Dist." or some other abbreviation if the OP doesn't want Registration
District spelt out in full.
 
Whilst those districts in cities cover relatively small, but densely
populated areas, so they are closely tied to one locality that is not true
of those districts covering more rural places.
 
M

  _____

**Comment by ShammyLevva** [comment]
Yes but even in rural areas a RD is always within the bounds of a county. eg: Lexden, Essex, England is far better than just Lexden RD. It also achieves exactly what is required to classify where the place is to the only level it is known ie: RD level. More precise would be town or even house name within the district. However for a very large number of English records the best you will do is RD level so adding , county name, England is always better than leaving it off. It would also allow the geocoding and mapping features to work which won't work with just the name of the RD.

**Comment by EmmArrBee** [comment]
Firstly, I totally agree that recording Registration District, County and
Country is probably safer.
 
I also agree with you that any one Reg.Dist. is only within a single County
at any one point in time, but is a REGISTRATION County and for the benefit
of those who may be less familiar with English records it is important to
acknowledge that Registration Counties do NOT always coincide with
Administrative Counties.
 
The most obvious and geographically largest example is the London
Registration County which was created at the time civil registration was
introduced on 1 July 1837.  The administrative London County Council wasn't
created until 1889. But even here we have multiple Ecclesiastical Parishes
which span administrative county boundaries. One ancestor may have been born
at one end of a street in Surrey and a sibling born at the other end of the
same street in Kent. But both should have been registered in the Greenwich
Reg. Dist. in the London Reg. County.
 
There are many other examples beyond London of parishes spanning
administrative county boundaries, but the whole parish being include in a
single Reg Dist. and therefore Reg. County. 
 
One of the more extreme examples I'm aware of, is the town of Dudley which
was part of Worcestershire and was surrounded by parishes in Staffordshire.
The Registration District of Dudley, which includes both Worcestershire and
Staffordshire parishes, was originally part of the Registration County of
Staffordshire (until 1912) and subsequently Worcestershire before returning
to Staffordshire and is now West Midlands.  
 
The border between England and Wales is another challenging area. The Hay
Registration District is in the Breconshire Reg. County, so Wales, but
includes parishes in Herefordshire, England.
 
All part of the fun of genealogy and accurately recording what we find.
 
M
 
  _____

**Comment by ShammyLevva** [comment]
Yup understand but not at all sure what the program can do to recognise registrations districts from roads when no other info is given. If the original poster can clarify what they think should be done that may help as at present I'm struggling to see what "fix" could be implemented.

**Comment by ShammyLevva** [comment]
I don't believe a fix is possible. Rd is commonly both Road and Registration District guessing is likely to cause issues.
