### ISSUE TITLE
Non-Census Residence Results in Warning [BUG] 

### ISSUE THREAD

**Issue by swiftjgs** [ShammyLevva/FTAnalyzer#223]
**Version Number problem appears in**
v8.3.1.0
**Describe the bug**
In the Errors / Fixes tab, I get this warning...Residence census date warnings    Warning : Residence date 18 APR 1931 is in a census year but doesn't overlap census date.
   This residence is from the address on an envelope. It doesn't have anything to do with the census.

**To Reproduce**
I think this will do it...
1. Include a Residence fact in Family Tree Maker 2019, where the source is not the census, but the timeframe is the census
2. Export as GEDCOM
3. Load the result in FTAnalyzer
4. Open Errors/ Fixes tab
5. Check residence / census date warnings

**Expected behavior**
No warning is created.

**Screenshots**
NA

**Comment by ShammyLevva** [comment]
This will happen when the option to treat residence facts as census facts is ticked. 

Ancestry are truly awful about merging census records and despite showing them as census records they appear in a GEDCOM as a residence fact. Thus the option to treat residence facts as census records was added. 

Note it is showing a warning not an error it’s warning you of a possible issue thus the program is working as designed. Thanks for taking the time to report this though.
