### ISSUE TITLE
1935 Residence Data Not Recognized [BUG] 

### ISSUE THREAD

**Issue by swiftjgs** [ShammyLevva/FTAnalyzer#224]
**Version Number problem appears in**
v8.3.1.0

**Describe the bug**
In the Errors / Fixes tab, I get this error... Uncategorised error    Census Fact dated BET 1930 AND JAN 1938 doesn't match census reference Roll: 02120, ED: 51-24, Page: 13A date of US Federal Census 1940.

    The 1940 census is included in the sources for this fact, because it reports the residence as of 1935.

**To Reproduce**
1. In Family Tree Maker 2019, create a Residence fact for 1935 that uses the 1940 census as a source
2. Export as GEDCOM
3. Load result into FTAnalyzer
4. Open Errors / Fixes tab
5. Check 'Uncategorised Errors' selection

**Expected behavior**
No error is recorded

**Screenshots**
NA

**Comment by ShammyLevva** [comment]
Interesting one. I’m not familiar with this form of record. How was the residence sourced from the 1940 census? Do you have an image for me to see? Or the GEDCOM snippet of this record. 

I may need to add some form of exception to ignore residence facts with different years that have a 1940 census source. Seeing an example would help enormously if you could please. If you prefer to email the file send it to ftanalyzer@gmail.com

**Comment by swiftjgs** [comment]
Hi, 
Here's a page from the US Census data from 1940. If you look in the middle (which is a bit blurry, sorry), you'll see that the residence of each person as of 1 April 1935 was reported.

![1935 data in 1940 census](https://user-images.githubusercontent.com/71048622/123495104-4e73a080-d5f0-11eb-8841-5fe480bf50a0.jpg)

**Comment by ShammyLevva** [comment]
Thanks I’ll have a think how best to tackle this one.

**Comment by Nichotj** [comment]
I have US 1940 census records and I don't have any errors listed.
This is how it records it in Ancestry.
![image](https://user-images.githubusercontent.com/29726075/123509954-8d493b00-d670-11eb-8a27-9a08861db2d2.png)
Looking at the 1935 fact in FTA, it shows the source as being the US 1940 Census.

**Comment by swiftjgs** [comment]
Yesterday, in response to guidance about another issue from ShammyLevva, I turned off two checkboxes in Tools/Options/Census Settings. These are 'Treat Residence Facts as Census Facts' and 'Convert Residence Facts w/census ref to Census Facts'. After making this change, this error disappeared also. I expect this is because my Residence Fact is no longer being checked as a Census Fact. However, because the 1940 US Census reported 1935 Residence information, there would be some validity in citing the 1940 Census as the source for a Census fact with a 1935 date.

**Comment by ShammyLevva** [comment]
Yes given it's a field in the 1940 census then Ancestry will create two facts. The issue will be how does it appear in the GEDCOM and thus how can it be treated as a normal residence fact even if the option is turned on. An example would help.

**Comment by swiftjgs** [comment]
I think Ancestry ignores the 1935 data and only creates a fact for 1940. When I've used the data, I've created the 1935 fact and copied the citation from the 1940 fact to the 1935 fact manually. Looking at my file now, I have many such 1935 entries that seem to create no erro. Here's the one that produced the uncategorized error (let me know if you need more of the file than this)...

1 RESI 300 Sheldon ST
2 DATE BET 1930 AND JAN 1938
2 PLAC Clovis, Curry, New Mexico
3 MAP
4 LATI N34.4048
4 LONG W103.2052
2 SOUR @S15@
3 DATA
4 TEXT Online publication - Ancestry.com. 1930 United States Federal Census [
5 CONC database on-line]. Provo, UT: The Generations Network, Inc., 2002.Orig
5 CONC inal data - United States of America, Bureau of the Census. Fifteent
5 CONC h Census of the United States, 1930. Washington, D.C.: National Archiv
5 CONC es and Records Administration, 1930.T626, 2,667 rolls. Clovis, Curry
5 CONC , New Mexico, ED 1, roll 1394, page , image 37.0.
2 SOUR @S265@
3 DATA
4 TEXT Record for xxxx
3 _LINK http://search.ancestry.com/cgi-bin/sse.dll?db=1030&h=150147977350&indiv=try
2 SOUR @S453@
3 PAGE Year: 1940; Census Place: Warrensburg, Johnson, Missouri; Roll: m-t0627-02120; Page: 13A; Enumeration District: 51-24

**Comment by ShammyLevva** [comment]
Fixed in v8.4.0
