### ISSUE TITLE
Sequence of individuals in .ged 

### ISSUE THREAD

**Issue by ralfswan** [ShammyLevva/FTAnalyzer#226]
I have exported a .ged file from Legacy Family Tree. The individual (INDI) records are not in order by the individual ID, so the first individual is not the correct FTA root person. Is there a way I can overcome this problem?

**Comment by ShammyLevva** [comment]
Yes in the main list of individuals select the person who is the real root person and right click on them and select set as root person.

There might be a way to set the root person in Legacy too but I've never used it. However the set root person option in FTAnalyzer is there for programs that don't have the option.
