### ISSUE TITLE
Create non-admin portable version

### ISSUE THREAD

**Issue by davejbur** [ShammyLevva/FTAnalyzer#227]
At present there are two installation choices: via Windows Store or "manual" from Github. Unfortunately, on a corporate PC (i.e. I have no admin rights), both of these options fail, since both require admin rights.

It would be really useful to have a "portable" version, i.e. a zipfile that can just be extracted to a folder and then just run. Many other applications can do this - indeed, on occasions, for older versions of FTA, I've been able to install it on another PC, then copy it onto this laptop and it's worked fine.

Thanks!

**Comment by ShammyLevva** [comment]
No sorry this will not happen. This is a hobby program as an IT Manager myself I fully agree with your company's policy to lock down installation of applications to known programs that are for business use.

I used to manually go through the chore of creating a zip file and trying to make sure I'd included every updated included library file. It would take me 15-20 minutes each time there was an update it was an annoying pain to do. I won't go back to doing that now there is a smoother more efficient method based on using a MIcrosoft installer.

**Comment by ags1234** [comment]
I also want exactly what @davejbur asked above. I don't want to mess up my system with a msi file.

@ShammyLevva You say you did the zip file manually. I am sure the thousands of developers that are here on Github that release portable or zip versions do not do that manually. The creation of a zip archive can probably be automated, if one knows how.
