### ISSUE TITLE
Extra functionality request

### ISSUE THREAD

**Issue by Dig5** [ShammyLevva/FTAnalyzer#229]
Currently I use Ancestry.com which I then export the GEDCOM before import to MacFamilyTree.  I have just come across your Windows version before downloading on the Mac.

My issue is that every time I want to consolidate the most current Ancestry export it creates a duplicate entry for events/sources already in MacFamilyTree.  This is not a problem with a few people but my tree is over 4500 people at present.

Wouldn't it be nice to be able to merge the duplicate events by merging the same attributes with the preferred one.  I have asked if this functionality could be implemented in MacFamilyTree but Synium Software do not see the usefulness (When synchronising events with FamilySearch).

I also would like to see some additional attributes populated:-

1.  The PC  version has FamilySearchID (_FID) which is not populated whereas it is not available on the Mac.

2.  Adding/viewing the User Reference Number (REFN) from MacFamilyTree in the Individuals list.

3.  It is nice to see you have links to Findmypast on the PC version, could other links be made for other websites (UK FreeBMD, FamilySearch, etc).  This functionality would be useful on the Mac version as well. 

4.  The Options on the PC for "Non GEDCOM Data Settings" to 'allow non GEDCOM date formats is useful for some of the dates in my files (export/sync from FamilySearch wrt format 21/08/2021 rather than 21 Aug 2021).   

I am adding the latest version of my MacFamilyTree export to this for you to see (I also used labels for sorting)
[My Updated Tree 21 Aug 2021.txt](https://github.com/ShammyLevva/FTAnalyzer/files/7025684/My.Updated.Tree.21.Aug.2021.txt)

Please contact me if you want more information about any of the above requests

**Comment by ShammyLevva** [comment]
Development on the Mac version has paused for a while whilst my machine I used was pressed into service to work from home. I do plan to return to it at some point.

**Comment by ShammyLevva** [comment]
Development of Mac version has ceased due to increased licencsing costs from Apple and the fact I no longer have a Mac capable of developing the Mac version on.
