### ISSUE TITLE
Multiple dates for an event

### ISSUE THREAD

**Issue by medows1** [ShammyLevva/FTAnalyzer#230]
I exported GED from TMG and some of the individuals have multiple dates for an event. For example one individual had 3 separate dates for a birth date. When I import these records it only shows the first date and this is not even the primary date for this birth.  On top of this I have checked the CSV file and birth dates written the same way are interpreted by Excel differently so this must be a Microsoft problem.
![FTAnalyzer - multiple TMG birth date error](https://user-images.githubusercontent.com/57760213/130349539-01f44cbf-83a4-4aa6-83a6-eaa2b56f6836.jpg)
![FTAnalyzer - import multiple birth date error](https://user-images.githubusercontent.com/57760213/130349541-7d598134-254c-4487-b43e-75457d5c9c90.jpg)

**Comment by ShammyLevva** [comment]
This will be down to how TMG creates it's GEDCOM file. The standard dictates how the file should be written but so many programs just do their own thing and ignore the standard. If you have alternate facts like this that aren't showing due to the way the GEDCOM has been written then you can display them by turning on View Alternative Facts option in the general options. 

I've not used TMG so I don't know what options are available but it may be that it's not marking specific events as the "preferred" event which would then export to GEDCOM as a preferred event, this would then be the event that is picked up as the preferred event by FTAnalyzer. If TMG is ignoring preferred events then the best that FTAnalyzer can do is to use the first event as the preferred one in the absence of a flag to say otherwise. 

Excel by default only understands dates from 1900 onwards. I believe there are addins that can adjust this but I've never used them.

**Comment by ShammyLevva** [comment]
Do note that TMG was last updated 7 years ago and is no longer supported by it's manufacturer. It would be wise to consider migrating to a supported product to avoid risks to your data longer term.

**Comment by EmmArrBee** [comment]
Hi Alexander,
 
Whilst you are factually correct about the author having stopped supporting
the product, there is a very active support community for TMG.  It's already
been established that TMG runs under the early beta versions of Windows 11,
for example.
 
There are also a number of third party products which can read the database
which underpins TMG. One produces a richer (and faster) GEDCOM dump than the
native export to GEDCOM feature.
 
And there is also an ongoing activity to create a successor product.
 
So many of TMG's users (myself included) feel no urgent need to migrate.....
 
M

  _____

**Comment by medows1** [comment]
I agree that TMG was the best product in 2014 but the world has moved on since then. I could wait for HRE but there is no indication when that will be ready. I offered my services and got no reply. So if I were to move then I would pick one of the following and I have licences for all of them...

Family Historian 7
Roots Magic 7/8
Family Tree Maker 2019
Legacy 9

I have subscriptions to Ancestry and Findmypast and with direct imports for FTM and RM really makes you lazy. I  no slouch as I was an IT professional and I have been doing family history for nearly 30 years

John Cardinal has released his TMG to GEDCOM product and as he had many years of experience with his product Second Site for TMG he is well placed to produce an appropriate GEDCOM file for one of the above products.

All products would be good if you have a decent reporting tool. I looked at FTAnalyzer so I could bring the CSV output into power query and manipulate data that way.

I even used odbc drives to read TMG's FoxPro database.

I agree that many developers manipulate their data and do not follow the GEDCOM standards strictly. However, GEDCOM has stagnated for a long time and there is a need for a better solution because there is so much more online. Dating that there is still a need to visit local history places all of the country. I live in Tyne and Wear/Northumberland and thereis not much digitised compared to Lancashire, London, Yorkshire, etc.

This gives you an idea where I am coming from.


Kind Regards,

Alan Medows

Mobile: 0781 2000 968
Email: ***@***.***
________________________________

**Comment by ShammyLevva** [comment]
Hi Alan,

Did you manage to try the option to include preferred facts? It's a work around though. I'm happy to look at a snippet of a TMG file with multiple facts to see how they are structured. However I suspect they are being exported in the order they were created not necessary the order that marks the preferred fact. If I recall correctly by default the first fact in a GEDCOM file is treated as the preferred fact in the absence of a marker to the contrary.

**Comment by medows1** [comment]
Thanks for the update. I am still playing/testing various routes but at the moment the product is meeting some of my goals. As I said I have been a TMG for many years and over the years I tried out many of the online genealogy trees especially those that interacted with other genealogy programs. So I have data in TMG, Ancestry and Findmypast and I am using FTAnalyzer to import GED files from all 3 products to validate individual, family and source records. I then use output of FTA to bring data into Excels power query tool for validation. Here I can determine the way forward.
I appreciate your help to date.

Kind regards,
Alan


Kind Regards,

Alan Medows

Mobile: 0781 2000 968
Email: ***@***.***
________________________________

**Comment by ShammyLevva** [comment]
I'm going to close this issue as I suspect it's down to how TMG writes a file. If you wish to reopen it with additional info please do so.
