### ISSUE TITLE
Request for FTAnalyzer title on the Windows Start Tile

### ISSUE THREAD

**Issue by tadzilla55** [ShammyLevva/FTAnalyzer#235]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
In order to distinguish FTAnalyzer from other family tree software, I'd like the software name to appear underneath the tree picture on Windows tiles in Start.

**Describe alternatives you've considered**
I searched the file structure and the registry for a place to add the title, but didn't find one.

**Comment by ShammyLevva** [comment]
Sorry this is no longer encouraged by Microsoft and would fail their guidelines for support on the Windows store going forward so I cannot add this. Windows 11 removed support for named tiles for instance.
