### ISSUE TITLE
Request ability in settings to change grey and red colors on the census bar chart

### ISSUE THREAD

**Issue by tadzilla55** [ShammyLevva/FTAnalyzer#236]
**Is your feature request related to a problem? No

**Describe the solution you'd like**
I would like the ability to change the census bar chart colors as they hurt my eyes.

**Describe alternatives you've considered**
I checked setting and maybe I missed it, but I don't think so.

**Comment by ShammyLevva** [comment]
Should be easily possible to implement for a future version. Not immediately likely however given my current workload. Sorry about that. There are options in window to use different colour schemes maybe that could help as an interim option?

**Comment by ShammyLevva** [comment]
See issue #264 for how this is progressing. Plan is to implement via options panel colour selectors.
