### ISSUE TITLE
Problem Census Facts - 1941 Census

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#237]
FTAnalyzer version 8.3.1.0 running on a native install of 64-bit Windows 10 Home version 21H1 OS Build 19043.1237
GEDCOM file created by TMG to GEDCOM from a TMG v9.05 UK Edition database. 

On the Problem Census Facts report, I'm seeing a message "Warning: Residence date 23 FEB 1941 is in a census year but doesn't overlap census date" when I hover over one of the warning triangles.  This residence fact was created based on information gleaned from a marriage certificate.

According to The National Archives in Section 4.3 at https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/census-records/   ".....and no census was taken in 1941 because of the Second World War".

I'm struggling to understand what benefit I should expect to get from this warning.  I suspect its been generated in error, but I may be missing something.

MartinB

**Comment by ShammyLevva** [comment]
Do you have a sample file of a single user with this issue so I can see it during debug as I don't have someone with that problem myself and cannot see any references to an 1941 census in the program. If you can email to ftanalyzer@gmail.com please.

**Comment by EmmArrBee** [comment]
I've sent you the requested GEDCOM file.

The cautionary message seems to be generic, that is year independent. I see identical text for other decades, the date shown comes from the user data. Beyond that, the message text does not include the census year, it simply says "...  is in a census year ..."

Might your code be more generic. along the lines of "is county = England or Wales or Scotland or Northern Ireland, if yes, is year greater than 1841, if yes does year end in 1, if yes is day/month within (say) 45 days of 1 April ...."?

Having seen this issue, I'm wondering how FTAnalyzer should best handle Residence facts close to 26/7 April 1931.  For those of us with family south of the Scottish border at that time, the records were destroyed by fire in December 1942, so we're never going to benefit from them. (For those wanting more info, see https://en.wikipedia.org/wiki/1931_United_Kingdom_census)

At the moment your code is generating the same cautionary message.  My personal preference would be not to see a Problem Census Fact report for events close to the destroyed 1931 census. 

MartinB

**Comment by ShammyLevva** [comment]
I think I'll treat it similar to the 2021 census which only took place in England and Wales and not Scotland (that's next year 2022). It's the opposite situation in 1931 nothing for England and Wales and only Scotland.

**Comment by ShammyLevva** [comment]
Turns out there was an unknown country of SE14 that meant it was looking to see if there was a census year for anywhere in the world because it didn't know where SE14 was. Removing SE14 fixed the issue.

I've changed the text a bit to clarify.
