### ISSUE TITLE
Children's births can provide a tighter early date for a loose death range

### ISSUE THREAD

**Issue by brianfreud** [ShammyLevva/FTAnalyzer#239]
Known birth date: 16 Jul 1782
Last known child's birth date: 24 Feb 1824

FTAnalyzer suggests a loose death date of "BET 1823 AND 1892".  That could be a little tighter - it actually trips a warning in FTMaker, as 1823 is a little *too* loose.  Going for greater precision on the specific date might be overkill, but "BET APR 1823 AND 1892" is safe.  Additionally, as it now excludes Jan-Mar 1823, FTMaker throws no warning for that date range.

**Comment by brianfreud** [comment]
Another example:
Known birth date: 06 Jul 1702
Last known child birth date in not precisely known: 1733
FTA suggests: BET 1732 AND 1812
Better suggestion would be: BET MAR 1732 AND 1812

**Comment by ShammyLevva** [comment]
Is it possible to construct a GEDCOM snippet with an individual that has the necessary facts to show this bug. That makes it easier to construct a test case to demonstrate the bug and prove a fix is effective.

**Comment by ShammyLevva** [comment]
I've had a look and it was setting date to 1st Jan of 9 months before now sets to 1st of month 9 months before. This might risk being too tight as 9 months is an normal range but it's not an exact number. 

Tempted to make it 10 months and round to 1st of month it ends up in. This would avoid a birth on say 1st Feb 1824 suggesting Bet May 1823 AND 1892 as per your example. As May 1st + 9 months is 1st Feb. whereas you rightly suggest that BET APR 1823 AND 1892 is more feasilble.

Fixed for Version 8.4.0.0
