### ISSUE TITLE
Colour Census Reports

### ISSUE THREAD

**Issue by Cliveblackaby** [ShammyLevva/FTAnalyzer#24]
I note that these now include the 1939 National Register for England & Wales. RG101
Unfortunately although the COLUMN is there, the DATE FILTERS haven't been updated, so the report only covers those born before 1911 Census :) 
(simple fix :D )
Incidentally, as RG101 gives exact d.o.b., this is  a potential 'data check' - viz CENS or RESI detected but only partial birth date.

**Comment by ShammyLevva** [comment]
Date issue fixed in v6.3.0.2 - potential data check interesting option I'll leave this open to consider how best to implement that. Should be relatively straightforward though.

**Comment by ShammyLevva** [comment]
Possible error option implemented for v6.4.0.0

**Comment by Cliveblackaby** [comment]
I’ll give this a whirl later in the week
