### ISSUE TITLE
Populating a Custom Data Type in Bulk via Excel

### ISSUE THREAD

**Issue by txmusick** [ShammyLevva/FTAnalyzer#241]
In the List of Individuals csv, I used a blank Excel tab, and created a range of zodiac signs with their date ranges. I did some date/vlookup formulas and populated a new zodiac field in the individual report. Now that I'm putting the results into each person's record in FTM, I am looking for a reverse individual report that will take each person's sign and put it into the corresponding custom field. I've considered viewing the format of the gedcom to determine whether it's something I could do on my own (I can read some code, but not write it). I'd love to see some robust editing tools. The program comes with a Find&Replace that "knows just enough to make it scary," and I will only touch it when I can absolutely guarantee its outcome.

If we could make changes in excel and then convert it back to a gedcom, with proper field matching, it would be amazing.

**Comment by ShammyLevva** [comment]
FTAnalyzer is designed specifically NOT to edit a users data. So the concept of producing data to then edit back into a program is something I've specifically avoided. It is for the user to edit and maintain there data.

I can report on things but the only use I could see for reporting zodiac signs would be to highlight what a load of utter nonsense atrology is.

**Comment by txmusick** [comment]
Your opinion, and mine, of astrology isn't worth lining a waste basket
with. The data we collect in our family trees is not only for us, but for
the generations who follow us. My daughter's interest in the signs of her
ancestors is not for me to judge, and the items I choose to populate custom
fields with, in my family tree, is not for you to judge. If you're unable
or unwilling to provide the programming associated with the request, a
simple statement to that effect would be sufficient, and if not necessarily
polite, it would be much more reminiscent of something professional than
what you have responded with. I don't care if I want to record the color of
the underwear I had in 9th grade, it's my tree. If I want to bulk upload
that data, it doesn't matter if the programmer finds the data of interest.
She can either provide it, or she can't. It's pretty absurd that you felt
compelled to respond in such a snarky way.

Brandi Pool Thomas
***@***.***

**Comment by txmusick** [comment]
As if I would blindly upload a bunch of records with a #value error. Good grief.
