### ISSUE TITLE
Marriage Banns should be taken into account when determining loose birth

### ISSUE THREAD

**Issue by brianfreud** [ShammyLevva/FTAnalyzer#242]
Marriages are taken into account when determining a loose birth date.  In some cases, a Marriage Bann may have been located and entered, but without a corresponding Marriage; either the marriage never took place, or a record has not been found.  Nevertheless, a Marriage Bann has essentially the same minimal age conditions as a Marriage, and thus MARB should also be used for calculating loose birth dates.

**Comment by ShammyLevva** [comment]
Marriage Banns is taken into account. Do you have an example where it's not?

**Comment by ShammyLevva** [comment]
Still waiting for some examples are you able to provide this please?

**Comment by ShammyLevva** [comment]
Assuming this is no longer an issue. If it it please reopen the issue and provide a sample file.
