### ISSUE TITLE
[BUG] custom family facts and events are detected, but not counted, and the involved families can not be shown

### ISSUE THREAD

**Issue by ennoborg** [ShammyLevva/FTAnalyzer#243]
**Version Number problem appears in**
8.3.1.0

**Describe the bug**
When custom facts are found for families, they show up in the custom facts list, but their count is 0, and there is no way to click through to the offending family.

**To Reproduce**
1. Load a GEDCOM with custom family facts,
2. Click on Main Lists/Custom Facts
3. Scroll down to a fact with count 0

**Expected behavior**
The custom facts window description suggests that it's for individuals only, so it could be designed to display custom individual facts only. A better choice would probably be to keep the detection as is, and make sure that these facts are stored with counts and links to these families, so that they can be displayed.

**Screenshots**
![VirtualBox_Windows 10 Pro_14_11_2021_15_47_05](https://user-images.githubusercontent.com/1702834/141686274-62a0dce9-a29c-4f7e-a949-0b76f1bf1992.png)

**Additional context**
In Gramps, we export the following lines to export the family status, for example when the user knows that people were marrried, but has no marriage event:

1 FACT MARRIED
2 TYPE _STAT

Another example is a civil marriage, like:

1 EVEN
2 TYPE civil marriage

You can add either to a family to see the error.

**Comment by ShammyLevva** [comment]
Added in v8.4.0 (avaialble for test in beta 7)
