### ISSUE TITLE
Report misplaced citation(s)

### ISSUE THREAD

**Issue by karlic** [ShammyLevva/FTAnalyzer#246]
**Is your feature request related to a problem? Please describe.**
In FTM, I added a census event for someone (John Jones, say), but accidentally clicked on the wrong citation (for a census piece containing the Smith family, say).

**Describe the solution you'd like**
It would be nice if FTAnalyzer could notice that the citation was linked to (say) four Smiths, but only one Jones and flag this as a possible error. (I've only just started my family tree, but it seems that census citations generally only refer to one family name/household.)

**Describe alternatives you've considered**
I can look at each citation in the Sources tab in FTM and see whom it is linked to, but it would be nice to have it done automagically.

**Additional context**
I haven't thought it through, but would it be possible to extend this to check misplaced BMD (and/or other) citations too? (Although, B&M *do* normally have more than one family name.)

**Comment by ShammyLevva** [comment]
This doesn't sound good idea a vast amount of families are blended familes and census records reflect that scan down the pages of a census to see it's very very common for a family to have other family members with different surnames staying with them. eg: a family with a grown up daughter who is living with them with her new husband and child. The daughter, husband and child would have an alternate surname and would be perfectly correctly recorded.

Citations are also commonly used for other things for instance a marriage citation would tag the husband the wife, the parents of the husband, the parents of the wife, witnesses etc. You can practically guarantee the two families that are getting joined in marriage will have different surnames and the witnesses likely will too. This would mean that all marriage certificates would appear in this list of problems.

SImilarly a birth certificate often has different people's surnames on it especially if the couple were unmarried at the time of the birth. A death certificate commonly has the names of previous spouses and may have been recorded by a son in law as the witness, again all different surnames. 

So in truth I don't think this is a good idea.  It's incredibly difficult to come up with a proper definition that is workable for what constitues a bad source citation.
