### ISSUE TITLE
Running FTAnalyzer on Linux, with Wine

### ISSUE THREAD

**Issue by ennoborg** [ShammyLevva/FTAnalyzer#247]
**Is your feature request related to a problem? Please describe.**
Well, sort of.

**Describe the solution you'd like**
I'd like to run FTAnalyzer on Wine, in Linux, because that's where I run Gramps.

**Describe alternatives you've considered**
I now run the program in VirtualBox, under Windows 10.

**Additional context**
It seems to be quite difficult to install .NET 4.7.2 in Wine.

Do you know any way to solve this?

**Comment by ShammyLevva** [comment]
It may be possible when I eventually move to the open source .Net 5 (more likely .Net 6) as that is being built as cross platform however for now I don't know enough about Wine to comment.

**Comment by ShammyLevva** [comment]
v10.0.0.0-beta2 runs on .Net 6 does this work on wine? If not then I don't know that I can do with anything. I'll close issue for now - reopen if you have further feedback.

**Comment by ennoborg** [comment]
I tried it, but no. The .Net installation seems to work OK, but after installation, FTAnalyzer still says that it wasn't found, and I have no idea how to diagnose this, so I'll stick to the FTAnalyzer running in VirtualBox.
