### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by medows1** [ShammyLevva/FTAnalyzer#248]
**Version Number problem appears in**
v8.3.1.0

**Describe the bug**
Not all errors as described in FTA are being reported.
One example found in my GEDCOM found relates to "Facts dated after death". After loading data into FTA I put same file into RootsMagic8. It highlighted that a person had 5 facts after death which were not reported into FTA. I checked this out in my Ancestry Online tree and these 5 facts were entered after the death date. JOHN DOUBTFIRE (1819-1875) was my example.

**To Reproduce**
1. Load GEDCOM file.
2. Review data error list and look for facts after death.

**Expected behavior**
Any fact after death should be shown in the error list.

**Screenshots**
![image](https://user-images.githubusercontent.com/57760213/143314757-2d9be46d-f506-498b-98c9-51cf73164e6f.png)
![image](https://user-images.githubusercontent.com/57760213/143314852-b464f7a4-ead4-42bf-91a2-df252debe804.png)

**Additional context**
I have been running FTA for several weeks and this has happened on more than 1 occasion.
The only thoughts I had were
a) there maybe a finite numbers of errors allowed in a run but I would think that is unlikely.
b) The fact type was not a recognised fact type for validating ---> fact type was OCCUPATION. This fault was recognised by RootsMagic.
c) Another fault where burial before death may be preventing other checks being done correctly.
 .

**Comment by ShammyLevva** [comment]
I’ll need a GEDCOM snippet of the problem to see what is going on. Can you export that one individual to a file, and check it’s still shows the error as I’ve not seen this before. 

You can either attach the file here as a text file or email it to me at ftanalyzer@gmail.com

**Comment by ShammyLevva** [comment]
Actually are ALL the fact types occupation? If so then yes this is ignored as it’s perfectly possible to observe an occupation for a father particularly on a document dated well after they have died. So if it’s only occupation facts then this is working as intended.

**Comment by ShammyLevva** [comment]
Assuming it is just occupation facts as no post in 3 weeks to say otherwise.
