### ISSUE TITLE
Install and Running give Registry error

### ISSUE THREAD

**Issue by gwallerct5** [ShammyLevva/FTAnalyzer#249]
Hi Shammy,
You have a wonderful program and I used it in the past with no problems.

After/during installation:
![image](https://user-images.githubusercontent.com/71231342/143952009-943e60aa-1a55-4119-a385-39858bf7eee2.png)

After running;
![image](https://user-images.githubusercontent.com/71231342/143951520-7a41d762-6680-4e21-a994-80e4c32125cc.png)

Here are some of my specifications:
OS Name	Microsoft Windows 11 Pro
Version	10.0.22000 Build 22000
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	GEORGE-DELL-202
System Manufacturer	Dell Inc.
System Model	XPS 15 9500
System Type	x64-based PC
System SKU	097D
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz, 2496 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. 1.10.0, 9/28/2021
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Product	0W4CRC
BaseBoard Version	A03
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22000.1"
User Name	GEORGE-DELL-202\George Waller
Time Zone	Eastern Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.8 GB
Available Physical Memory	16.3 GB
Total Virtual Memory	128 GB
Available Virtual Memory	107 GB
Page File Space	96.0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	On
Virtualization-based security	Not enabled
Device Encryption Support	Elevation Required to View
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

Thanks George

**Comment by ShammyLevva** [comment]
Is this a new fresh install? Is this working using a different username?

The error is that the user who has run the program has no access to read the settings data in the registry. This should be available to all users on the machine but it may be some security software is blocking the logged in user from access if the logged in user is different from the user that installed the app. The solution would be to check the permissions on the named registry folder and see why your currently logged in account is denied access. 

The first error after/during installation suggests that the installer is being denied access to create settings the second error is the program unable to find the settings that failed to be created during install. 

So perhaps something during install is blocking setup of user settings?. What install method did you use?

**Comment by gwallerct5** [comment]
Hello Alexander,
Many thanks for your email.  I uninstalled FTAnalyzer and re-installed and
everything is working fine.
Best wishes, George
