### ISSUE TITLE
Highlight selected line in Census Research Suggestions window

### ISSUE THREAD

**Issue by karlic** [ShammyLevva/FTAnalyzer#250]
**Is your feature request related to a problem? Please describe.**
I sort the suggestions by birth date, then look at the red boxes, BUT when I move my eye gaze to the left to read the individual's name, I lose track.

**Describe the solution you'd like**
I should like to be able to click on a red box and have the whole line highlighted so that it was clear which name the box applied to.

**Describe alternatives you've considered**
I know that the form is tabulated and the lines alternate between grey and white colours, but a clear highlight would be preferable.

**Additional context**

**Comment by ShammyLevva** [comment]
Added in v8.5.0
