### ISSUE TITLE
Family Tree Maker shows direct relation but Family Tree Analyzer says: Relation=Unknown

### ISSUE THREAD

**Issue by cathsaigh** [ShammyLevva/FTAnalyzer#251]
FTA: v8.3.1.0
FTM: Version: 2019 (24.0.2.1269)

Within Family Tree Maker there are multiple direct ancestors that when exported to GEDCOM and imported into FTA, Relation = "Unknown".

**Comment by ShammyLevva** [comment]
That's almost always due to the wrong person set as the root person. In the individuals tab find yourself and right click to set as root. That then recalculates the relationships from scratch based on yourself.

**Comment by cathsaigh** [comment]
thanks.  I'll try that and let you know.  I was thinking that it might be
caused by being related to the same person in more than one way.

Tim
