### ISSUE TITLE
TreeTops Report 

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#252]
V8.4.1.0 But present in previous versions

Not sure this is a bug or whether it was designed like this.

When I run the report I get a lot of people who are not my direct ancestors listed. 
So the 1st question is, should this report only show direct ancestors?

![image](https://user-images.githubusercontent.com/29726075/147882904-24b5b03a-f3ee-4112-aeff-574bdef2ce3e.png)

When investigating these people further, they all have one parent missing, which is maybe triggering them to appear on the report?

So should there be 2 reports?  A treetops report that just shows where your direct ancestors stop, and a 2nd one that show's everyone missing one or two parents?

**Comment by ShammyLevva** [comment]
It should filter based on the relationship types selected. If you select only direct ancestors then it should show only direct ancestors?

**Comment by Nichotj** [comment]
Yes, you're correct.  The report works fine, it's just me that has flaws. :)
