### ISSUE TITLE
Surnames Report 

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#254]
v8.5.1.0 and v8.5.0.0-beta3

The count for Individuals, Families and Marriages is not always correct.
![image](https://user-images.githubusercontent.com/29726075/151385752-3fe4e518-49d2-462f-a585-972b2f2999b8.png)
In this screenshot for the surname Abel, there is a count of 1, but when you double click, the new list comes up and says there are 105 individuals and 50 families.

**Comment by ShammyLevva** [comment]
Hmm I wonder if the count is respecting the filters but the list isn't?

Yup that's it the double click isn't using the filters. If you turn on related by marriage, linked through marraige, and unknown (ie: everyone) then the numbers match.

**Comment by ShammyLevva** [comment]
Fixed for v8.5.2.0
