### ISSUE TITLE
[BUG] Add suffix to Individuals export

### ISSUE THREAD

**Issue by eazytime** [ShammyLevva/FTAnalyzer#257]
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
Sorry the template is there for a reason so you can be guided to the information I need. This issue tells me nothing.

**Comment by ShammyLevva** [comment]
User failed to provide any info.
