### ISSUE TITLE
Custom Filters not working

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#258]
v8.5.2.0

On the Main Lists Tab, Individuals Report
Looking at Budgie Code or Relation to Root

![image](https://user-images.githubusercontent.com/29726075/154659178-ddcdffaf-9932-4c41-9094-b84f40e08dee.png)

When you use the custom filter i.e. Begins with, and enter a value, it produces 0 results

This snapshot is from v8.5.0.0beta3 where the image is clearer.
![image](https://user-images.githubusercontent.com/29726075/154659930-3f6c59ba-470b-413b-9760-b55cd989dc0d.png)

**Comment by ShammyLevva** [comment]
Should be working in v10 beta 5 can you confirm and close if working please.

**Comment by Nichotj** [comment]
Yes it appears to be working now.
However there are 2 other things so I'll raise new issues.
