### ISSUE TITLE
[BUG] Father under age 13 error for a 27 year old father

### ISSUE THREAD

**Issue by brianfreud** [ShammyLevva/FTAnalyzer#267]
**Describe the bug**
See the attached file.  Johann Peter Schweitzer, born 1789, would have been 27 in 1816.  However, FTAnalyzer gives a "Birth before father aged 13" error for the birth of his son Johannes in 1816.  There are no erronious duplicated birth events or anything like that in Johan Peter's information.

**To Reproduce**
Load the gedcom, look at the first error in the error list.  (This is a gedcom generated by FTM2019)

**Expected behavior**
No error would be reported.

**Comment by brianfreud** [comment]
Sorry, version 8.5.2.0

**Comment by brianfreud** [comment]
[Johann Peter Schweitzer Family Tree.ged.tar.gz](https://github.com/ShammyLevva/FTAnalyzer/files/9291613/Johann.Peter.Schweitzer.Family.Tree.ged.tar.gz)

**Comment by ShammyLevva** [comment]
The error is showing on Johannes Schweitzer born 13 AUG 1801 when Johann Peter Schweitzer was just 12. 

The GEDCOM for the erroneous individual is 

```
0 @I1461@ INDI
1 NAME Johannes /Schweitzer/
2 SOUR @S277@
3 PAGE Personenstandsregister Sterberegister; Bestand: 907; Signatur: 6283
1 SEX M
1 NAME Johannes Göbel
2 TYPE aka
1 BIRT illegitimate
2 DATE 13 AUG 1801
2 PLAC Solz, Hersfeld-Rotenburg, Hessen, Germany
3 MAP
4 LATI N51
4 LONG E9.8667
1 EVEN
2 TYPE Illegitimate
2 DATE 13 AUG 1801
2 PLAC Solz, Hersfeld-Rotenburg, Hessen, Germany
3 MAP
4 LATI N51
4 LONG E9.8667
1 DEAT
2 DATE 21 DEC 1871
2 PLAC Solz, Hersfeld-Rotenburg, Hessen, Germany
3 MAP
4 LATI N51
4 LONG E9.8667
2 SOUR @S1157@
3 OBJE @M1205@
1 FAMS @F626@
1 FAMS @F627@
1 FAMC @F625@
```

**Comment by brianfreud** [comment]
Sorry, thanks.  This can be closed as invalid; I missed seeing the illegitimate son from 1801, vs seeing the legitimate one with the same name from 1816.
