### ISSUE TITLE
Minimal Gedcom showing details of live people

### ISSUE THREAD

**Issue by KeithHarwood101** [ShammyLevva/FTAnalyzer#270]
v8.5.2.0

I downloaded a Minimalist Gedcom for DNA then uploaded to MyHeritage. The resulting tree shows some details of living people. Options selected were Replace living people with Private Person, Include SIblings, Include Descendants of Siblings. Examples - my wife and I are marked as private, my children are private, but partners of my children, and my grand-children are all named

Thanks for any advice
Keith

**Comment by ShammyLevva** [comment]
Ahhh interesting I’d never tested descendant links in the DNA tree option. I shall investigate, many thanks for bringing it to my attention.

**Comment by ShammyLevva** [comment]
I've had a look and I am struggling to reproduce can you email me at ftanalyzer@gmail.com with a sample file. So I can find out what is going wrong.

**Comment by ShammyLevva** [comment]
Identified as missing birth details. New feature request added as issue 288.
