### ISSUE TITLE
A Marriage of Two Persesons with UNKNOWN Surnames Should Not Be Reported

### ISSUE THREAD

**Issue by bsfinkel** [ShammyLevva/FTAnalyzer#273]
If two persons with unknown surnames marry, then that marriage should not be reported as "Couples with same surname".

**Comment by ShammyLevva** [comment]
Very good point. This is an edge case I'd not considered but it is a bug and will be fixed.

**Comment by ShammyLevva** [comment]
fixed for v10.0.0.0-beta2
