### ISSUE TITLE
Column Widths

### ISSUE THREAD

**Issue by gafii** [ShammyLevva/FTAnalyzer#278]
Column widths are not adjustable compounding issue with no left to right slider to see entire entry.

**Comment by ShammyLevva** [comment]
This is far to vague. WHERE are column widths not adjustable? The program uses a dynamically adjustable grid as standard almost all columns can be moved. Certain forms they are locked. You didn't mention a form so I cannot work out what you are talking about.

**Comment by gafii** [comment]
All column widths in data list and error& fixes remain constant.  I can move columns to a different position by sliding them, but width does not change.

**Comment by ShammyLevva** [comment]
You have not said what version you are running.

**Comment by gafii** [comment]
I am running Win 10, latest update.  It contains net 4.8.
-------- Original message --------From: Alexander Bisset ***@***.***> Date: 1/22/23  17:48  (GMT-05:00) To: ShammyLevva/FTAnalyzer ***@***.***> Cc: gafii ***@***.***>, Author ***@***.***> Subject: Re: [ShammyLevva/FTAnalyzer] Column Widths (Issue #278) 
You have not said what version you are running.

**Comment by ShammyLevva** [comment]
What version of FTAnalyzer? 

You said - "in data lists" please descrtibe what you mean. These one line answers are infuriating.

**Comment by gafii** [comment]
Talk about infuriating – I assume you meant my computer system.  If you mean FTA it is 8.5.2.  

 

You do not need to respond since it appears we are talking 2 different languages.  I will endeavor to resolve them issue myself.
