### ISSUE TITLE
Cell Copy

### ISSUE THREAD

**Issue by gafii** [ShammyLevva/FTAnalyzer#279]
Need ability to select individual cell to copy data for pasting into tree search.

**Comment by ShammyLevva** [comment]
What screens are you using that would require you to copy and paste data? There are numerous data exports and there are automated searches. 

You need to explain better which screens you are using and what sites you are trying to use to paste data because I cannot read your mind.

**Comment by gafii** [comment]
I copy the duplicate or error name and paste into my family tree search.  As it now works, the entire row is highlighted.
-------- Original message --------From: Alexander Bisset ***@***.***> Date: 1/22/23  17:50  (GMT-05:00) To: ShammyLevva/FTAnalyzer ***@***.***> Cc: gafii ***@***.***>, Author ***@***.***> Subject: Re: [ShammyLevva/FTAnalyzer] Cell Copy (Issue #279) 
What screens are you using that would require you to copy and paste data? There are numerous data exports and there are automated searches.
You need to explain better which screens you are using and what sites you are trying to use to paste data because I cannot read your mind.

**Comment by ShammyLevva** [comment]
Yes but from which report? Why are you not using the automated searching?

**Comment by gafii** [comment]
I guess I am totally uninformed.  I am using data errors and duplicates to correct errors (I assume these are reports) in my family tree.  I can not see entire entry in duplicates due to NET (?) issue.  So I want to copy name and paste it into family tree search.  The search option does not help if I can not see the match name due to .NET issues.
