### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Delboy51** [ShammyLevva/FTAnalyzer#281]
V8.5.2.0

Unknown Census Ref: Archive reference RG11 Piece number 1974  Folio 42 Page 3
Unknown Census Ref: Archive reference RG11 Piece number 817 Folio 74 Page 20

Unknown Census Ref: RG11   1781    5   4    587
Unknown Census Ref: RG11   3282   63  10   178
Unknown Census Ref: RG11  1293  16  26   286
Unknown Census Ref: RG11  1576  53  44
Unknown Census Ref: RG11  1666  81  5

I can’t see what is wrong as i have other records using this format that are accepted.

Piece: 10661, Schedule: 109	England & Wales Census 1911
Piece: 10661, Schedule: 109	England & Wales Census 1911
Piece: 1737, Folio: 8, Page: 9	England & Wales Census 1881
Piece: 1827, Folio: 60, Page: 10	England & Wales Census 1881
Piece: 1827, Folio: 60, Page: 10	Scotland Census 1881
Piece: 1827, Folio: 61, Page: 12	England & Wales Census 1881
Piece: 1827, Folio: 61, Page: 12	Scotland Census 1881
Piece: 1827, Folio: 79, Page: 27	England & Wales Census 1881

**Comment by ShammyLevva** [comment]
These should now be picked up in v10.0.0.0-beta2
