### ISSUE TITLE
[BUG] beta installer does not create a start menu entry, or desktop icon

### ISSUE THREAD

**Issue by ennoborg** [ShammyLevva/FTAnalyzer#282]
**BETA RELEASE Version 10.0.0.0-beta 1 - 16th October 2022**

When I install the beta, I don't see anything in the Start menu, nor a new icon on the desktop. I can fix this, by creating a shortcut from the EXE inside the Program Files folder, but the installer should do this for me, just like it does that for the earlier version.

You will mostly likely not notice this when you have the earlier version on your system already.

I tested this on Windows 10 and 11.

**Comment by ShammyLevva** [comment]
Fixed in v10.0.0-beta2
