### ISSUE TITLE
Description field on Burial record no longer appearing in Comments field on Burial Facts record in FTAnalyzer

### ISSUE THREAD

**Issue by gabellouise** [ShammyLevva/FTAnalyzer#283]
This is in follow-up to an issue that I recently reported via the Family Tree Analyzer group in Facebook.  For deceased ancestors and blood relatives,  I have been recording specific burial location/cemetery in the Description field on the Burial record in Ancestry.  In turn, when I then created the GEDCOM field and imported it to FTAnalyzer, the burial location appeared in the Comments field on the file.  This was very helpful in identifying where specific families are concentrated in terms of church affiliation and cemeteries.  Unfortunately, about two months ago, the Burial Description stopped displaying in the Comments field.  There has been no change to my FTAnalyzer version and it's been suggested that perhaps there's been a change in the format of the GEDCOM file.  I have narrowed down the change to sometime between 12/20/2022, when the burial description appeared in the Burial Facts Comments column, and January 7th (the next time I generated the GEDCOM file) when this data stopped displaying in Comments.  I am attaching snippets of both the 12/20/22 field and the 1/7/23 file for comparison.  Please let me know if additional information is required.  Thanks, Louise Gabel
[LMohn GEDCOM 12202022.docx](https://github.com/ShammyLevva/FTAnalyzer/files/10842832/LMohn.GEDCOM.12202022.docx)
[LMohn GEDCOM 01072023.docx](https://github.com/ShammyLevva/FTAnalyzer/files/10842833/LMohn.GEDCOM.01072023.docx)

**Comment by ShammyLevva** [comment]
Yup they have changed the GEDCOM.

Lines that were 
1 FACT sometext here 

have become
1 FACT
2 NOTE sometext here

![image](https://user-images.githubusercontent.com/29687786/232258655-f579dbc6-75e4-4b8e-8ed4-33fd78af98b3.png)

I can check how I load the notes if the fact is empty.

**Comment by ShammyLevva** [comment]
Fixed in v10.0.0.0-beta2
