### ISSUE TITLE
Couples with same surnames[BUG] 

### ISSUE THREAD

**Issue by savagedruth** [ShammyLevva/FTAnalyzer#284]
**Version Number 8.5.2.**

**The Bug**
Double Click to show a list of facts for the selected individual is not working

**To Reproduce**
1. Load Gedcom
2. Click on Errors/Fixes
3. Scroll across to Couples with same surname tick this box - leave others blank

**Expected behavior**
When I see the list generated I expect to be able to double-click to show a list of fact for the selected individual

**Screenshots**
Have attached a screenshot
![Double-click not working](https://user-images.githubusercontent.com/130125555/230543801-d930ab4c-dc22-43c6-8966-ddabb40a7561.jpg)

**Additional context**

**Comment by ShammyLevva** [comment]
Double click bug fixed in v10.0.0.0-beta2
