### ISSUE TITLE
I am trying to install FTAnalyzer (version 8.5.2.0) on my Windows10 Desktop from the Microsoft Store. It seems to download but will not run. I am getting a popup box saying “Windows cannot access specified device, path or file. You may not have appropriate permissions to access this site”.  Can anyone tell me how to avoid this problem?

### ISSUE THREAD

**Issue by martynhugh** [ShammyLevva/FTAnalyzer#285]
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
Usually this indicates that the installer didn’t have the permission to fully install the app and the settings file in particular it couldn’t access. This is a known problem with the Windows Store and happens to many installs. You can try again making sure you run the store app as administrator so it has rights to create the directories. Or you can use the alternative stand alone installer that gives you more control over how the app installs. 

The alternative installer can be found at https://github.com/ShammyLevva/FTAnalyzer/releases/tag/v8.5.2.0
