### ISSUE TITLE
V10.0.0.0 Beta 2 Cosmetic Issue

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#287]
Using a dual screen config on Win10, I started the new beta 2 version of FTAnalyser and dragged it over to my second screen

I then file dragged and dropped a GEDcom file on to the FTAnalyser window and the app correctly processed the GEDcom file.

The pop up message confirming the GEDcom file had been loaded appeared centrally on my first screen, no where near the FTAnalyser window,

Would suggest the app should place such pop-up windows central to the app WINDOW and not to the primary SCREEN of the computer.

Can share a screen shot if that would help.

M

**Comment by ShammyLevva** [comment]
Makes sense. I’m just using the default MessageBox. I probably need to customise it or force some setting to ensure it pops up on top of the current window.

**Comment by EmmArrBee** [comment]
If you're using .Net's MessageBox class, then perhaps Show(Window, String, String) rather than simply Show(String, String) would be more appropriate. That causes the message box to appear in front of the specified window. 

M

**Comment by ShammyLevva** [comment]
Should be fixed for v10 beta 6
