### ISSUE TITLE
Run Google Geocoder to find Locations

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#29]
Hi Shammy,

As you know Google restricts the number of hits to 50 and then you display a warning 
![image](https://user-images.githubusercontent.com/29726075/40969087-ee7c3e96-68ae-11e8-9003-f2de71ba76c1.png)

If I come back and run the Geocoder again after 24 hours I continue to get the warning. I have to close FTA and reload the gedcom before I can continue with the next 50 locations.

Is the warning inside FTA only being reset when you relaunch FTA?  Reloading the gedcom doesn't change anything, only closing and opening FTA works.  It's only a minor pain but when you have 5,000 plus to do, relaunching FTA every day for the next 3 months is going to be a grind.

Thanks.

**Comment by ShammyLevva** [comment]
The 50 limit is 50 queries a second, the daily limit is 2500. So it should only take 2 days to do 5000.

**Comment by Nichotj** [comment]
ok.
Here is the before reading:
![image](https://user-images.githubusercontent.com/29726075/41020969-b8a2941a-695c-11e8-9aa7-efc3cd51e565.png)

Here is a shot while it's running:
![image](https://user-images.githubusercontent.com/29726075/41021057-f79e5d20-695c-11e8-87e0-f6dfac570617.png)

Here is the shot at the end.
![image](https://user-images.githubusercontent.com/29726075/41021367-101e5afc-695e-11e8-9c5b-0ceaa622e019.png)

As you can see it managed 81 on todays run, nowhere near 5,000? Is your count recording attempts as a part of the 5,000?

**Comment by Nichotj** [comment]
I'm now running ver 6.4.2.1 and just had this error pop up.
![image](https://user-images.githubusercontent.com/29726075/41189880-72c92dc4-6bcc-11e8-8015-e99143e4be95.png)

Clicking the ok button brings up this statement
![image](https://user-images.githubusercontent.com/29726075/41189892-9a603e40-6bcc-11e8-8d91-352edd87648e.png)
And now I have to wait 24 hours.

**Comment by ShammyLevva** [comment]
Hmm it appears Google is making changes to their API settings that affects Geocoding - coincidental that it happened same time as a new release. I'll need to read up on the changes and see if I can work around the issue.

Basically they no longer allow queries without a developer key. If I get a developer key then the app can have a certain number of downloads per month, above that number and they bill me for usage. That could mean I pay for a licence and am at the mercy of users racking up geocoding hits and Google billing me for users usage. So not sure how I'm going to get a happy medium on that one.

**Comment by GeoffRiley** [comment]
As a suggestion how about a configuration allowing people to register their own keys and dropping the registration into the app? (I haven't looked how they've updated the API myself yet, so this might be a non-starter, but it's something to throw around.)

**Comment by ShammyLevva** [comment]
Yes this is likely the route I’ll need to go.

**Comment by ShammyLevva** [comment]
Fixed in v6.4..3.0
