### ISSUE TITLE
Suffix, Alias and Title don't display results

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#290]
v10.0.0 Beta2

In the Individuals report, Suffix, Alias (Also Known As?) and Title don't display any results from the gedcom.

![image](https://user-images.githubusercontent.com/29726075/234113687-3283231c-82cb-4957-a9c6-cbdeb89aa1cb.png)

I've sent an example gedcom to you.

**Comment by ShammyLevva** [comment]
I've got the title working. I can't find any Suffix or Alias records in your GED file though. Can you resend the file as I'm just using an old Nicholsxxxxxx.ged file from 2021 you sent me.
