### ISSUE TITLE
Research Suggestions Header

### ISSUE THREAD

**Issue by stevewrightnz** [ShammyLevva/FTAnalyzer#294]
Header not tall enough cutting off data

**Comment by ShammyLevva** [comment]
Can you explain. This is very vague. Which header on which page? Using which font size on what resolution of monitor and what version of the program. 

There is a template to guide users to provide the information I need to understand the issue. If you don't give me the information I need to be able to reproduce the error I can't help.

**Comment by stevewrightnz** [comment]
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ShammyLevva** [comment]
No feedback from user just empty message.
