### ISSUE TITLE
[BUG] Data errors tab does not initialize view properly

### ISSUE THREAD

**Issue by brianfreud** [ShammyLevva/FTAnalyzer#298]
**Version Number problem appears in**
10.0.0.0-beta3

**Describe the bug**
If you load one gedcome, then load a second, the data errors tab will initially show errors from the first gedcom.

**To Reproduce**
1. Open any gedcom.
2. Open any other different gedcom.
3. Go to the Errors/Fixes tab.  The Data Errors tab is the default view.  It will be displaying data errors from the first gedcom, not the second.
4. Go to any other tab within Errors/Fixes (Duplicates, Loose Births, etc).
5. Go back to the Data Errors tab.
6. Now it will be displaying data errors from the current gedcom.

**Expected behavior**
The Data Errors tab should be properly initialized when the Errors/Fixes tab is selected.

**Comment by ShammyLevva** [comment]
I've done a good few updates for beta 4 and cannot replicate this problem now. It may be I fixed it with the other tidyups without realising. Can you verify if you can still replicate it with beta4. I was unable to.

**Comment by ShammyLevva** [comment]
I believe this to be fixed now. Please re-open if still an issue in v10.0.0.0-beta 8 or above.
