### ISSUE TITLE
Facts report error

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#30]
I was looking at this very painful Male Wifes and Female Husbands on the Error/Fixes report.
Double clicked on the offending person, got the facts report open, and scrolled right on got this error message.

![image](https://user-images.githubusercontent.com/29726075/41260235-7de286c0-6dce-11e8-892e-8df270459471.png)

**Comment by ShammyLevva** [comment]
Fixed in v6.4.3.0
