### ISSUE TITLE
[Feature Request] BORN_DURING_CENSUS

### ISSUE THREAD

**Issue by rasamassen** [ShammyLevva/FTAnalyzer#302]
In Research Suggestions => Census Report Suggestions, there's a result called "Died within range of census dates" (or, in CVS export, DIED_DURING_CENSUS. There's no comparable BORN_DURING_CENSUS.

For example, I have one person born 12 Dec 1930. It's saying NO_CENSUS ("No census information entered") for the US 1930 Census. It really should say "Born within range of census dates" and be in that similar tan color that DIED_DURING_CENSUS appears in.

**Comment by ShammyLevva** [comment]
Added in v10.0.0.0-beta4
