### ISSUE TITLE
Report for finding non standard dates

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#306]
When adding Facts from Ancestry (or even if you enter them yourself) they can get added as 25 JANUARY 1974 or MARCH 1 1945.

The international standard used is 25 JAN 1974 or 1 MAR 1945.

I'd like a report that identifies all date entries that are non compliant, maybe sorted or reported by person so that they can be fixed.

It appears that FTAnalyzer seems to auto correct this when it displays dates, e.g. Here's a date I've just found in my FHS: 1923-01-04 but in FTA it's shown as 4 JAN 1923

**Comment by ShammyLevva** [comment]
Nah not going to add this. FactDate does a huge amount of correction otherwise the program would be useless to a load of users. Without it understanding the variety of date formats and correcting it wouldn't do most of it's functions so this is a non starter.
