### ISSUE TITLE
Ver 10 Beta 5 On This Day

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#307]
Ver 10 Beta 5.

Font size is Normal, on the "On this Day" tab the numerical box hasn't moved and is now covered by the "Year Step" text

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/a33165ce-c368-458e-b5fb-c5f87cd8346b)

**Comment by ShammyLevva** [comment]
I think the change to the manual checks for scrollbars has caused some knock on layout issues. I'm not seeing the effects myself so it makes a fix tricky. I'll delete and recreate the controls that have the issues and see if that fixes it. Updated for beta 6.

**Comment by Nichotj** [comment]
Fixed in Beta 6
