### ISSUE TITLE
Ver 10 Beta 5, Results Form starts half way down the screen

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#308]
Ver 10 Beta 5, Font size Normal.

On the Treetops, World Wars and On This Day tabs,  the results form starts halfway down the screen.

I think the results should start populating the screen a line or 2 below the last line of the selection part of the screen, which I'm guessing is dynamic depending on font size?

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/484efa55-8dcf-4e08-8c90-6658aa99f8de)

**Comment by ShammyLevva** [comment]
positioning weirdnesses are very annoying. There is no rhyme nor reason for it. It's meant to be anchored to the bottom of the selection buttons above it. I'll look at the weekend.

**Comment by ShammyLevva** [comment]
I think this is fixed for beta 6.

**Comment by Nichotj** [comment]
Not fixed in Beta 6, still the same.

**Comment by ShammyLevva** [comment]
It's a result of the HighDPI things I've redone this for .Net 8 which is meant to fix a lot of these things and extends support to June 2026.

**Comment by Nichotj** [comment]
This is fixed in Beta 7
