### ISSUE TITLE
Ver 10 Beta 5, Colour BMD Report

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#309]
Ver 10 Beta 5, Font Size Normal

On the Colour BMD Report there appears to be a box with a drop down but the drop down doesn't work, I think it's for selecting Births, Marriages or Deaths?  I've highlighted it in Red in the image.

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/f4657b71-1032-4ec9-9b09-f9fe6e66a25d)

**Comment by ShammyLevva** [comment]
That box only becomes active as a sub filter when you aren't filtering on all individuals. I've changed the behaviour so it is not visible when Filter has all individuals selected.
