### ISSUE TITLE
Drop Down icons on the Individuals Tab

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#310]
Ver 10 Beta 5, Font Normal

The drop down icons on the Individuals tab (it looks like all Tabs with the grid? are very small and difficult to get the cursor onto them.

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/5d719140-5baf-4089-9828-5a00a9452e85)

Can they scale according to the Font size selected?

**Comment by ShammyLevva** [comment]
What screen resolution are you using? It might be down to high DPI settings or it might just be the bug I logged with the control creator https://github.com/davidegironi/advanceddatagridview/issues/124

**Comment by Nichotj** [comment]
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/eba4214e-bf1e-4a5b-87f8-716060be4b04)

**Comment by ShammyLevva** [comment]
Fixed for beta 9.
