### ISSUE TITLE
Husband/Wife/Child in Lost Cousins Reports

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#312]
Ver 10 Beta 5, Font size Normal

When selecting either View Potential Uploads or View Invalid Census Refs on the Lost Cousins Tab, there is a field displayed called Husband/Wife/Child.

This doesn't always show the correct status in relation to the census year.

e.g. in the image below which are all for the 1911 census, Winifred <1 and Mary 12 are both shown as Wife.  There are also examples of where it shows as wife but weren't married till after 1911.

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/fbe5607c-f380-4cb4-a4e2-8c2ead92ee9c)

Is the purpose the the field to show a family relationship? Should Husband/Wife be Father/Mother?
Is the issue with these examples which are wrong because there is no other family members recorded?
These people/examples should all be in the latest big gedcom I sent you this month.

**Comment by ShammyLevva** [comment]
It's actually correct but perhaps confusing, note that the list shows the different family IDs (hence the change in colour banding) so the people are in different families. Their status in that column is the status they have in the family with that family ID.

So for Winifred Mills she is a Wife in family F3624 but is only 1 at the time of the census.

**Comment by Nichotj** [comment]
Ok, that makes sense.  I can ignore the column, don't think it's really relevant to me in this report.
