### ISSUE TITLE
[BUG] Screen appears compressed when in full screen mode.

### ISSUE THREAD

**Issue by ShammyLevva** [ShammyLevva/FTAnalyzer#313]
v10.0.0.0-beta6

Screen appears compressed when in full screen mode.

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29687786/85042a19-415b-4895-aebb-e7659065a448)

**Comment by Lincsman54** [comment]
To confirm, resolution is 1920x1080 and scale is set to 125%
changing scale to 100% fixes the issue but I need it to be 125% on my laptop

Device name	Asus-Laptop
Processor	Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz   1.50 GHz
Installed RAM	8.00 GB (7.74 GB usable)
Device ID	E6FE6BD2-E26D-412A-B4EC-B0FA5A1DEFD4
Product ID	00342-22056-10075-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	23H2
Installed on	‎26/‎11/‎2022
OS build	22631.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Comment by Lincsman54** [comment]
Just to confirm, I have just installed beta 10.7 and the display issue is fixed in that release :-)
