### ISSUE TITLE
Facts Tab, Title Box obscures some of the facts

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#314]
Ver 10 Beta 6 Font size Normal

In the image below, you can see that this box (in red) appears halfway down the list of Facts, I'm guessing it should be at the top?

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/92867648-6e9c-4f4e-b92d-95d830d0d3c8)

**Comment by ShammyLevva** [comment]
I can see various things in the wrong place on that image the select all button, the de-select all button, the surname label and the shw button beneith surname label.

**Comment by ShammyLevva** [comment]
Fixed in beta7
