### ISSUE TITLE
Not all Custom Facts are getting displayed in the Facts Tab

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#315]
Ver 10 Beta 6, Font size Normal.

I have a custom Fact called "DNA Cousin, Keith".  It appears on the home screen but is not present on the Facts Tab.
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/82fa1009-2ddb-4365-ad3c-a65079b7dafb)
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/d398b0d6-60fb-4694-851f-1478ab5e4be3)

But it does appear on the Errors/Fixes Tab, Unknown/Custom Fact Type
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/71d6d3f8-9427-4742-b4c7-f1d9f763f8a8)
It also happens with the custom Fact "CHARLES CAPE"

**Comment by ShammyLevva** [comment]
Did you already send me an example with these two custom fact types (ideally with a custom fact type that does exist) so I can determine what the difference is.

**Comment by Nichotj** [comment]
Yes I sent one via messenger

**Comment by ShammyLevva** [comment]
I think this a PICNIC error. Can you screenshot the whole of the facts tab as I strongly suspect I know what is going on but need to see the setting to determine if my hunch is right.

**Comment by Nichotj** [comment]
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/09bf2b32-6754-4fa7-a61d-b441468cd88c)
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/41b3601a-4f72-428b-8410-f537e2743e5c)
Is this what you needed?

**Comment by ShammyLevva** [comment]
Yup. Now notice the unticked filter boxes. Related by Marriage, Unknown, Linked by Marriage. If you tick them the missing custom facts should appear. That would be my guess as it's what happened with your test data.

**Comment by Nichotj** [comment]
Yes, you're correct.
