### ISSUE TITLE
Date Error messages when month is in French

### ISSUE THREAD

**Issue by liamland** [ShammyLevva/FTAnalyzer#32]
Observation. Date parser generates incorrect error messages when months are in French

**Comment by liamland** [comment]
Joseph Nelson Shannon born 4 MAI 1880
The following is from the Data Error report:
  |   | Birth after father aged 90+ | P04366 | Mary Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | ABT 1916 | 1981
-- | -- | -- | -- | -- | -- | -- | --
  |   | Birth after father aged 90+ | P04367 | William Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | DEC 1909 | UNKNOWN
  |   | Birth after father aged 90+ | P04368 | Flora Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | ABT 1912 | UNKNOWN
  |   | Birth after father aged 90+ | P04369 | Elizabeth Bessie Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | NOV 1904 | UNKNOWN
  |   | Birth after father aged 90+ | P04370 | James Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | MAR 1902 | UNKNOWN
  |   | Birth after father aged 90+ | P04371 | Joseph Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | ABT 1918 | UNKNOWN
  |   | Birth after father aged 90+ | P04372 | Cecile Shannon | Father Joseph Nelson Shannon born 4 MAI 1880 is more than 90 yrs old when individual was born | ABT 1914 | UNKNOWN

**Comment by liamland** [comment]
I am using v 6.4.3.1

**Comment by ShammyLevva** [comment]
Interesting it should auto complete the date when in French. I’ll investigate. Are you able to provide a small GEDCOM snippet of just that family so I can load it and see where the error occurs in the program code.

**Comment by liamland** [comment]
[Sample.txt](https://github.com/ShammyLevva/FTAnalyzer/files/2205538/Sample.txt)

**Comment by ShammyLevva** [comment]
Fixed in v6.5.0.1
