### ISSUE TITLE
Research Suggestions Tab

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#320]
Ver 10 Beta 7

None of the report buttons work.

![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/5d2b1b56-104f-40be-8985-b62a419b63bf)

The only way I could get it to work was to remove the "All Families" and selecting a specific family
![image](https://github.com/ShammyLevva/FTAnalyzer/assets/29726075/ac12e21a-2d67-4d61-9f45-92e281a92dc7)

**Comment by ShammyLevva** [comment]
I'd added a null check without realising that should mean all families. Fixed for Beta 8
