### ISSUE TITLE
No page sliders

### ISSUE THREAD

**Issue by gafii** [ShammyLevva/FTAnalyzer#327]
[ScreenShot.pdf](https://github.com/ShammyLevva/FTAnalyzer/files/14322426/ScreenShot.pdf)
**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**
There are no sliders and can not view all data

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
Known issue fixed in v10 which at time of writing is available as a beta version.
