### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by gerrynuk** [ShammyLevva/FTAnalyzer#34]
Not sure if this can be classed as an issue but the display font is tiny on my laptop (Windows 10). Is there a way to increase the font size, please, as my eyes are struggling to read the text. Thanks.

**Comment by ShammyLevva** [comment]
Hmm interesting one. There are options within Windows 10 to change font sizes as it should use the default on your machine. I can investigate adding an option to make the size bigger though.

It may be that the default screen resolution you have set and the default font size you have set in Windows 10 could do with tweaking especially if you find this is an issue with other apps.

This article may help https://www.laptopmag.com/articles/increase-text-size-computer

Let me know if it's an issue unique to FTAnalyzer or a global issue.

**Comment by gerrynuk** [comment]
Thanks for your reply. I looked at the link you posted but it seems the options to change the font sizes of different elements of the window have been removed in the latest (Creator's?) version of Windows. Currently I have the system font set at 125%, with the screen resolution at 1920x1080.. This is the recommended default, and for most applications the text is comfortably readable. For some reason, the text in FTAnalyzer remains very small. You can see from the screenshot attached that the font is much smaller than in the Word window. If it is possible to add an option to increase the font size and to change the display font that would be very helpful.

![screenshot 156](https://user-images.githubusercontent.com/42680235/44792212-47f02080-ab9b-11e8-8953-2c82921eba5c.png)

**Comment by ShammyLevva** [comment]
Thanks that helps me understand what’s going on. I’ll see what can be done to change font scaling. The main issue is it’s likely to affect the size of the forms with possibly unpredictable results.

**Comment by skip411** [comment]
I'm having the same problem.  When FTA is first loaded, fonts are okay and readable,  but if I then go to Lost Cousins and then try to access FTA,, it comes up in a window where the font is so small it is almost unreadable, much smaller than the example above,.  This may be a bug in MS-Windows 10 but it sure is frustrating.

**Comment by fire-eggs** [comment]
As an exercise, I modified the Font property of MainForm to be a 12 point font.

Much of FTA adjusts fine, with a few exceptions. For example, here is a portion of Lost Cousins screen:

![image](https://user-images.githubusercontent.com/9809727/44996783-d4258d80-af77-11e8-8a06-02dedf339f93.png)

Note the menus are small (I guess that's a separate Font adjustment) and the Recorded facts section.

Stats area:
![image](https://user-images.githubusercontent.com/9809727/44996826-223a9100-af78-11e8-8599-294a5c01d1ee.png)

Locations Tree view is small:
![image](https://user-images.githubusercontent.com/9809727/44996844-38e0e800-af78-11e8-85c1-e9b4f93de7ad.png)

FYI.

**Comment by gerrynuk** [comment]
Big improvement!

**Comment by skip411** [comment]
I usually pull up the lost cousins tab, run the 1881 English Census report,
for example, then go to any other screen, FTM in this example, to check
data.  When I go back to FTA, it's in such a small window that nothing is
readable.

I made some screen shots last night, let me see if I can attach them.

**Comment by ShammyLevva** [comment]
Added in v6.6.0.0

**Comment by gerrynuk** [comment]
Thanks for the new edition. The fonts are much improved and greatly aid use
of this app.

Gerry

**Comment by fire-eggs** [comment]
Very nice!
