### ISSUE TITLE
Facts Erroneously Flagged As Duplicate 

### ISSUE THREAD

**Issue by OcalaDick** [ShammyLevva/FTAnalyzer#36]
I have lots of user created facts like, "Death Certificate Status." I only use the Description field and the choices are "Have" or "Need." FTAnalyzer keeps flagging all of them with a message similar to "Duplicated DEATH CERTIFICATE STATUS fact recorded."

**To Reproduce**
1. Create a User Fact in your database, "Death Certificate Status"
2. Create the GEDCOM
3. Load the GEDCOM into FTAnalyzer
4. Check the error reports

**Expected behavior**
Should not flag it as an error.

**Desktop (please complete the following information):**
 - Win 10 64 Bit
 - Browser Firefox
 - Version 60.2

**Additional context**

**Comment by ShammyLevva** [comment]
Are you able to provide a GEDCOM snippet showing this issue I can’t fix the problem if I can’t reproduce it.

**Comment by ShammyLevva** [comment]
Without a GEDCOM file to demonstrate the issue I cannot address this. Please feel free to reopen the case and attach a GEDCOM file.
