### ISSUE TITLE
Download ALWAYS stop at 89%

### ISSUE THREAD

**Issue by chekblad** [ShammyLevva/FTAnalyzer#37]
I'm not able to use this tool anymore since the download always stops at 89%.
Do you have any suggestion about how to solve this issue?

**Comment by ShammyLevva** [comment]
Uninstall the old version reboot and install fresh. Something has become corrupted with your install so it’s hanging when you try to update.

**Comment by chekblad** [comment]
I did as you mentioned, uninstalled and also tried to find any remainders of the application.
Also downloaded a fresh copy of the installer.
Now the installation hangs at 0% (17,9kb).
(I'm running Win10 in a virtual machine)

**Comment by ShammyLevva** [comment]
What do the details say? 

There is also a zip file version of the application which you can download and unzip to a folder of your choice. That means that whatever is currently broken with your .net installer (the Microsoft click once installer is what is running trying to download the app) can be bypassed and you can get the app running. 
https://github.com/ShammyLevva/FTAnalyzer/releases

**Comment by ShammyLevva** [comment]
Any progress?

**Comment by ShammyLevva** [comment]
No further reply
