### ISSUE TITLE
1939 Census

### ISSUE THREAD

**Issue by BobWhaley** [ShammyLevva/FTAnalyzer#38]
The 1939 Census has been available from Ancestry for some time.  Is there an intent to modify FTAnalyzer to permit access to the 1939 census on Ancestry

Regards
BobW

**Comment by ShammyLevva** [comment]
Can you clarify “permit access” please

**Comment by BobWhaley** [comment]
I can now go to the Colour Census Report and click on the colours to pull up a list of ‘targets’ on the Ancestry website.  This did not happen when I tried a few days ago. At that time I got a messagebox saying that it was not possible to use Ancestry to search the 1939 Census.

 

I think you can close the issue down!

 

BobW

**Comment by ShammyLevva** [comment]
I’ll check the Ancestry links in case they’ve changed something. I know they were updating the website recently. If it all looks ok I’ll close the issue. If the problem reoccurs please let me know.

**Comment by BobWhaley** [comment]
Sorry, but the problem has come back. I can search successfully if I instigate a search by ‘show missing from the UK National Register 1939 record’. However, if I try to click on a cell in the 1939 National Register column of the Colour Census Report, I get a messagebox stating ‘Unable to search the 1939 National Register on Ancestry’.

 

BobW

**Comment by ShammyLevva** [comment]
V6.7.0.0 implements the Ancestry registry properly thanks for raising the issue.
