### ISSUE TITLE
unknown fact type OCCUPATION

### ISSUE THREAD

**Issue by gbouwkamp** [ShammyLevva/FTAnalyzer#39]
Receiving error: "unknown fact type OCCUPATION"
Gedcom has multiple OCCUPATION fact type, one of them is causing an error.
FTA on Facebook asked that I uploaded a one person Gedcom that is causing the error.
See attached. Note that GED upload not supported, changed extension from GED to TXT.
Thanks
[FTM _Gordon_Bouwkamp Family Tree_2018-10-14.txt](https://github.com/ShammyLevva/FTAnalyzer/files/2477129/FTM._Gordon_Bouwkamp.Family.Tree_2018-10-14.txt)

**Comment by ShammyLevva** [comment]
Hmm it seems you've created a custom fact type of Occupation as well as the default fact type of Occupation.

The user has 3 default Occupations eg:
1 **OCCU** Working as a salesman at Haas-Bouwkamp Real Estate, living at 2634 Mid
2 CONC delex Court.
2 DATE 1955
2 PLAC Lafayette, Tippecanoe, Indiana, USA

and 1 custom fact type occupation ie:
1 **EVEN** Advertisement for Gordon's Oil & Grease Center, 515 N 10th street.
2 **TYPE Occupation**
2 DATE 17 APR 1954
2 PLAC Lafayette, Tippecanoe, Indiana, USA

I've added support for custom occupation fields although really it could be said it's an error as the default type should be used.

**Comment by ShammyLevva** [comment]
Cause diagnosed and support for format added for next version.
