### ISSUE TITLE
DIfferent Coordinated Than What's in GEDCOM

### ISSUE THREAD

**Issue by paulp575** [ShammyLevva/FTAnalyzer#43]
(continued from Facebook posting)

Maybe it's not a bug, but if you look at Google Earth, Google Maps, or even Bing maps and find a location west of 0 longitude you'll see the longitude has a minus sign in front of it (that's the standard). Just did a quick look at some of my FTM location. Looks like FTM is using W or E for longitude locations so that must be why they don't have the minus.

[Paul Yelk 2018-03-18 - 2018-10-31 - Heckel, Anna Maria.zip](https://github.com/ShammyLevva/FTAnalyzer/files/2536992/Paul.Yelk.2018-03-18.-.2018-10-31.-.Heckel.Anna.Maria.zip)

[FTAnalyzer-Geocodes-2018-10-31-v7.0.0.2.zip](https://github.com/ShammyLevva/FTAnalyzer/files/2536995/FTAnalyzer-Geocodes-2018-10-31-v7.0.0.2.zip)

**Comment by ShammyLevva** [comment]
Fixed in v7.1.0.

Issue was that the check was has this been geocoded before? The check is now has this been geocoded before OR is this an update to an existing geocode?
