### ISSUE TITLE
MAC version 1.0.2.0 crashes when opening a GEDCOM

### ISSUE THREAD

**Issue by UncleBuck62** [ShammyLevva/FTAnalyzer#46]
**Describe the bug**
FTA MAC version 1.0.2.0
When opening a GEDCOM file the program crashes to an Apple report right away.

**To Reproduce**
Load GEDCOM (supplied by email)

**Expected behavior**
GEDCOM to load and program behave as normal

**Desktop (please complete the following information):**
 - OS: OSX 10.11.6 (Early 2009 MAC Pro)

**Comment by UncleBuck62** [comment]
[FTA MAC Crash report.txt](https://github.com/ShammyLevva/FTAnalyzer/files/2569861/FTA.MAC.Crash.report.txt)

**Comment by UncleBuck62** [comment]
Whoops... Closed by accident.

**Comment by UncleBuck62** [comment]
[Test only tree_2018-11-12.ged.zip](https://github.com/ShammyLevva/FTAnalyzer/files/2570042/Test.only.tree_2018-11-12.ged.zip)
Even the attached simple 3 person GEDCOM is crashing on open. I have done this as it might be easier to work with this file rather than the larger GEDCOM I sent you earlier.

**Comment by ShammyLevva** [comment]
Please try test version at https://www.dropbox.com/sh/n8ahu0sepd8j410/AABoVrLsH5ha7mPuGETElXaka?dl=0

**Comment by ShammyLevva** [comment]
With lots of test versions and loads of assistance we finally got this bug squashed.
