### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by cassyput** [ShammyLevva/FTAnalyzer#57]
In v7.0.5.0 keep getting message "Arithmetic operation resulted in an overflow". 

This has not occurred to me in previous version.

**Comment by ShammyLevva** [comment]
Thanks for the report. However I need a whole lot more information than that to know where to fix it.

In the bug report form there was a series of questions asking you to spell out HOW the error happened. These questions were there for a reason. Sorry but I'm not a mind reader I cannot just guess what happened.

**Comment by cassyput** [comment]
Hi,

Simple, I loaded the GEDCOM and FTA started to run.

A few incorrect dates came up. It seemed to load all the records. Then it
just quit and the error message came up.

This happened every time I ran it.

I'm not at all "techie" and that's all I can tell you.

It started, appeared to load, then quit with the error message then
appearing.

Hope this helps as it's all I know.

ATB

Richard

**Comment by cassyput** [comment]
P. S. If it helps I can run a screen video and send.

**Comment by ShammyLevva** [comment]
Thanks ok that suggests some form of problem with the way it's processing your file. Can you email a GEDCOM to ftanalyzer@gmail.com that demonstrates this error and I'll fix it for v7.1.0 which should be out soon.

**Comment by cassyput** [comment]
Hi,

I've sent the file a Drive link to ftanalyzer@gmail.com. It's about 40 MB.

*Richard Hill*

*Prior to Now <https://www.combedown.org/>*

*115 Church Road, Bath, BA2 5JJ*

M: + 44 (0) 7 956 540 135

**Comment by ShammyLevva** [comment]
Thanks for that. There were two separate issues.

First it threw a wobbly with your Ahnantafel numbers as they exceeded the maximum value that could be saved in that type of variable so I've used an extended decimal number instead which is good for a few dozen more generations.

Secondly there were odd non displayable characters in the file that were getting thrown out as errors.

Both fixed for v7.1.0.0
