### ISSUE TITLE
GEDCOM Name parsing incorrect in one specific case

### ISSUE THREAD

**Issue by fire-eggs** [ShammyLevva/FTAnalyzer#6]
The GEDCOM standard allows _no_ space between the forenames and the surname, e.g.: 
`1 NAME John/Smith/`

In this situation, FTA loses the last character of the forenames.

To fix, in Individual.cs, at line 319, change:
`forenames = startPos == 0 ? Individual.UNKNOWN_NAME : name.Substring(0, startPos -1)`
to this:
`forenames = startPos == 0 ? Individual.UNKNOWN_NAME : name.Substring(0, startPos).Trim();`

**Comment by ShammyLevva** [comment]
Fix applied. I'll publish it after reviewing other issues.
