### ISSUE TITLE
Exception in Error/Fixes Duplicates

### ISSUE THREAD

**Issue by cjades** [ShammyLevva/FTAnalyzer#60]
**Describe the bug**
Having imported a new GEDCOM, clicking on **Errors/Fixes Duplicates?** results in the error message
System.ArgumentOutOfRangeException: Value of '101' is not valid for 'Value'. 'Value' should be between 'minimum' and 'maximum'.
Parameter name: Value
   at System.Windows.Forms.ProgressBar.set_Value(Int32 value)
   at FTAnalyzer.MainForm.<>c__DisplayClass182_0.<SetPossibleDuplicates>b__0(Int32 value)
   at System.Progress`1.InvokeHandlers(Object state)

**To Reproduce**
1. Load new GEDCOM then Go to 'Errors/Fixes.'
2. Click on 'Duplicates?'
3. 'No scrolling required'
4. See error text as above

**Expected behavior**
I expected to see a list of duplicates in the file (if any)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Quantum v64

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ShammyLevva** [comment]
Thanks for the report this is a rounding error will be fixed in v7.2.0.1.
