### ISSUE TITLE
Tree Count

### ISSUE THREAD

**Issue by jfossy** [ShammyLevva/FTAnalyzer#62]
Just as a wishlist item, it would be nice if it had a feature like in RootsMagic where it can count the trees. Basically it shows the number of isolated groups that aren't connected to each other. Handy for cleanup when you try to delete a branch or you have a speculation tree trying to see how they may fit into your main line.

**Comment by ShammyLevva** [comment]
Revisited this. You can get this from people who have a relationship status of Unknown. These are the people who have no link to the root person. So as long as the root person is set correctly this should work.

Sorry I added this in a version over Xmas and haven't updated this issue to say it worked now.
