### ISSUE TITLE
Report / How many Directs

### ISSUE THREAD

**Issue by cjades** [ShammyLevva/FTAnalyzer#63]
**Describe the bug**
Unhandled exception

**To Reproduce**
1. Go to 'Reports'
2. Click on 'How many Directs.'
3. Click on one of the Relations to Root
4. See image

**Expected behavior**
Have not used this feature before so not sure what I expected

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] Quantum 64
![fterrorhowmanydirects](https://user-images.githubusercontent.com/45994652/50309755-eaf4df00-0497-11e9-98cf-ba798c2ab9ce.JPG)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ShammyLevva** [comment]
Thanks fixed for v7.1.0.1
