### ISSUE TITLE
Date range not detected correctly

### ISSUE THREAD

**Issue by GeoffRiley** [ShammyLevva/FTAnalyzer#65]
**Describe the bug**
Error message presented when processing GEDCOM file:

> Error parsing date 'BET 3 AND 4 JAN 2001' for I702: Allan Cochrane Guthrie. Error message was : Problem with date format for: 3JAN 2001 system said: Unrecognised date format for: 3JAN 2001

**To Reproduce**
1. Enter the date range 'Bet. 3 Jan 2001 and 4 Jan 2001' in Family Tree Maker
2. Export GEDCOM
3. Import into FTAnalyzer

**Expected behavior**
It should be accepted like any other date range.

**Desktop**
 - OS: Windows 7
 - Browser Chrome
 - Version 71.0.3578.98 (Official Build) (64-bit)
 - FTAnalyzer version 7.2.0.0

**Additional context**
This has been happening for some time, but I've not looked at it in FTM until today.

Appropriate section from GEDCOM:
> 1 REFN I702
> 1 DEAT Car accident
> 2 DATE BET 3 AND 4 JAN 2001
> 2 PLAC High Wycombe, Buckinghamshire, England

**Comment by ShammyLevva** [comment]
It was just the second one. A space trimming bug. Fixed in v7.2.1.0

**Comment by GeoffRiley** [comment]
Just as a follow up, there is a bug in FTM that mis-interprets 'Bet 3 and 4 Jan 2001' but internally converts to that once it's accepted!

Thanks for the amazingly quick bug fix.

**Comment by GeoffRiley** [comment]
I'm not doing this on purpose!  I just got this date parsing error:

>Error parsing date 'BET 9 AND 10 OCT 1910' for I1354: Cissie Hughes. Error message was : Problem with date format for: 9  OCT 1910 system said: Unrecognised date format for: 9  OCT 1910

To be clear of the error, the date in the GEDCOM appears as:
> BET˽9˽AND˽10˽OCT˽1910

and the _unrecognised format_ appears as:
> 9˽˽OCT˽1910

i,e, with two spaces after the 9.

**Comment by ShammyLevva** [comment]
I did wonder if I should force a stripping of spaces in case there was a double space. Looks like it’s needed.
