### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by cassyput** [ShammyLevva/FTAnalyzer#68]
**Version Number problem appears in**
7.2.4.2

**Describe the bug**
Won't start just says 'cannot access a closed file'

![ft analyzer 2019-01-03_16-07-18](https://user-images.githubusercontent.com/45899655/50648127-4a5fee00-0f72-11e9-9ec6-156448117d34.png)

**Comment by TerryWickenden** [comment]
I am having the same problem since upgrading FTAnalyzer just now

**Comment by Nichotj** [comment]
Hi Guys, Alexander is aware of the issue and working on it as we speak.
Normal service will be resumed shortly :)

**Comment by cassyput** [comment]
*Such excellent service as usual :)*

**Comment by Nichotj** [comment]
And I see it's already fixed, ver 7.2.4.3 is out and available.
