### ISSUE TITLE
Gedcom viewer

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#71]
Hi Shammy,

So I was looking at a guys tree today in FTAnalyzer, to try and help him, and he has a lot of errors, of the type :
_Invalid GEDCOM, Line: 7620. First character in a should be numeric 'Source Information'_

What I was wondering, is it possible to have the abilty to either double click from this error and go to some sort of basic viewer with FTAnalyzer?  One of the main issues is that you report a line number, but there is no way in Notepad to navigate to that line (easily). 
Or maybe identifying the Individual associated with these errors so that people can go and review all the entries for that individual?
Or the abilty to export it and import it into Excel, which would give it line numbers?

Lots of options?

**Comment by ShammyLevva** [comment]
Added in v7.3.0.0
