### ISSUE TITLE
[BUG] FTAnalyzer 7.2.4.4 now locks the GED file, preventing export / reload

### ISSUE THREAD

**Issue by bw86** [ShammyLevva/FTAnalyzer#72]
**Version Number problem appears in**
7.2.4.4

**Describe the bug**
You can no longer re-export a GEDfile from Family Tree Maker while FTAnalyzer has the GEDfile open. Previously you could do so, and then you could reload it.

**To Reproduce**
Export a GEDfile (e.g. from Family Tree Maker). Load the GEDfile in FTAnalyzer.
Make some corrections in FTM based on feedback from FTAnalyzer.
Re-export the GEDfile (while FTAnalyzer is still open).
This has always worked up until now - but now FTM fails - presumably because FTAnalyzer has the GEDfile locked.
Closing FTAnalyzer allows the GEDfile to be exported, but now you can't simply Reload it - you have to launch FTAnalyzer again, and use Recent Files.

**Expected behavior**
I expect FTAnalyzer not to hold the GEDfile open.

**Comment by ShammyLevva** [comment]
Ok thanks for the report I'll investigate.

**Comment by ShammyLevva** [comment]
New faster filestream loading wasn't closing file after it had opened it. Fixed for next version.
