### ISSUE TITLE
JULIAN date not accepted

### ISSUE THREAD

**Issue by GerardSontag** [ShammyLevva/FTAnalyzer#75]
**Version Number problem appears in**
7.2.4.4

**Describe the bug**
Error parsing date 'ABT @#DJULIAN@ 1567' for I3897: Nicolas CONTELLEC. Error message was : Problem with date format for: DJULAN 1567 system said: Unrecognised date format for: DJULAN 1567

**To Reproduce**
0 @I3897@ INDI
1 NAME Nicolas /CONTELLEC/
1 SEX M
1 BIRT
2 DATE ABT @#DJULIAN@ 1567
2 PLAC
1 DEAT
2 DATE 9 APR 1642
2 PLAC Plougonver, 22216, France

**Expected behavior**
This is not an error

**Screenshots**
NA

**Additional context**
NA

**Comment by ShammyLevva** [comment]
Yup I've never had anyone have a Julian date before but as you say it's perfectly acceptable. 

I'll have a look to see what's involved in supporting this.

**Comment by GerardSontag** [comment]
Thank you for taking in account. Did you notice that an 'I' is missing in the message DJULAN 1567?
And many thanks for FTAnalyser

**Comment by ShammyLevva** [comment]
Fixed in v7.3.6.0
