### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#76]
**Version Number problem appears in**
7.3.0.0 Beta 7

**Describe the bug**
In Ancestry, the 1911 Census _Summary_ sheet gets added as a residence fact. These entries are appearing on the report to add to Lost Cosusins (I don't think they should appear here).  They seem to start with the ref RG78, so maybe these can be ignored for this report?  Not sure if this effects other years?

**To Reproduce**
see Evelyn Appleton in my tree

**Expected behavior**
Census Summary sheets should not appear on the reports for loading into Lost Cousins

**Screenshots**

![image](https://user-images.githubusercontent.com/29726075/51120653-79495000-180d-11e9-9231-909156ee49e7.png)

**Additional context**
None.

**Comment by ShammyLevva** [comment]
Catered for in beta 10.
