### ISSUE TITLE
Issue/Suggestion

### ISSUE THREAD

**Issue by Nichotj** [ShammyLevva/FTAnalyzer#77]
**Version Number problem appears in**
7.3.0.0 Beta 7

**Describe the bug**
People who were in institutions at of the time of the 1911 census are created in Ancestry with the format 
Piece: 24366, Page: 24.  This will fail to load to Lost Cousins via your new upload file feature. The accepted format has Schedule and not Page.

**To Reproduce**
Please see people below in my tree

**Expected behavior**
There are 3 possible solutions.
1. On uploading to LC, replace "Page xx" with "Schedule 9999"
2. Detect these errors, maybe colour the lines, and have a hovertip that says the data needs to be changed to Schedule 9999.
3. Do both options 1+2

**Screenshots**

![image](https://user-images.githubusercontent.com/29726075/51122519-fe366880-1811-11e9-8003-b28b2d233142.png)

**Additional context**
None

**Comment by ShammyLevva** [comment]
Page left for display purposes but upload forced to 9999. Fixed in v7.3.0 beta 10
