### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wharton21** [ShammyLevva/FTAnalyzer#84]
7.3.0.0 **Version Number problem appears in**
 Loaded records to Lost Cousins [fantastic].
One record loaded had no census event records.  There was census info in the Notes for several censuses including -
1871 - ED, institution, or vessel: 	28
Piece: 	3663
Folio: 	71
Page Number: 	24

1881 - ED, institution, or vessel: 	10
Piece: 	3477
Folio: 	6
Page Number: 	6

FTA loaded the 1871 references as 1881 to Lost Cousins.
Surprised that it used the Notes and that it picked the wrong year.

**Comment by ShammyLevva** [comment]
Hmm it doesn’t seem to have attached. Can you email it to me at ftanalyzer@gmail.com

**Comment by GeoffRiley** [comment]
A quick note: attachments made to email replies do not get posted onto comment threads due to so many varied attachments being purely automated variations of the written message. 

Attachments to the comment thread should be made using the web interface.  Yes, it confuses lots of people.

**Comment by ShammyLevva** [comment]
Fixed in v7.3.2.4
