### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by wharton21** [ShammyLevva/FTAnalyzer#85]
Errors & Issues has flagged 3 people who are supposed to be on the 1939 Register with birth date not exact, but they clearly have death dates before 1939.

**Comment by Nichotj** [comment]
But have they got a 1939 fact recorded?

**Comment by wharton21** [comment]
No, they do not have a 1939 fact recorded.
I have re-run using v7.3.2.2 and got the same errors.

I inspected the 3 false errors.  They all had other census info in the notes, but no text matching “1939”.
They had deaths before 1939 recorded with a Q.

So I deleted all the census info in the notes for these 3 and re-loaded.
The error messages have disappeared.

I hope this helps.

David

**Comment by ShammyLevva** [comment]
Sounds like it had identified a 1939 census fact from the census references perhaps. Difficult to know now the error has been fixed. 

Note that the 1939 one is NOT an error it was a warning for something to check. Errors are shown with red Xs warnings are blue ?s 

So something in the census note was perhaps getting picked up erroneously. Checking the list of facts for the individual by double clicking could have identified this. 

Please re-open if able to reproduce the bug.

**Comment by ShammyLevva** [comment]
Excellent so 100% a typo and not something I can fix. I assume it should have been RG10/1360/76/7

**Comment by wharton21** [comment]
Yes, my sloppiness when quickly copying from somebody’s tree.  Normally I would have put a space between RG10 and the Piece.
Plus the quirk that the concatenation became RG101.

David
