### ISSUE TITLE
[BUG] On launching - Error upgrading database.

### ISSUE THREAD

**Issue by EmmArrBee** [ShammyLevva/FTAnalyzer#87]
Version 7.3.3.1

On launching FT Analyzer - Error upgrading database. Error is :SQL logic error near *(*: syntax error

Clicking OK then load the FTA main screen and I can then load a GEDCom file without further issue 

**To Reproduce**
Happens on every launch of program

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47026383/51737367-495b4180-2084-11e9-8383-f18aa49ba981.png)

**Additional context**
Not used FTA in a long time, so this may be related to upgrading across one than one major release of FTA

**Comment by ShammyLevva** [comment]
Yup fixed in v7.3.3.2

**Comment by ShammyLevva** [comment]
Fixed in v7.3.3.2 thanks for the report
