### ISSUE TITLE
Unrecognized EW 1939 register References

### ISSUE THREAD

**Issue by MalcolmSpencer** [ShammyLevva/FTAnalyzer#9]
Could you please add a new pattern 'CensusReference.cs' code for the EW 1939 register references.
The format on the find my past website is RG101/0884D/018/13
if i just copy and paste this FT anlayser says it is an unrecognised census ref.

I had a look at the code to see if there was a format i could convert the above to but none of them allow characters in the 'piece' field.

Thanks,
Malcolm.

**Comment by ShammyLevva** [comment]
That format is broken down as what? Is this right? 
Census number RG101 
Piece number 0884D 
fairly sure of those first two
018 is Page?
13 is line?

I no longer have a FMP subscription and am not keen to pay just to check.

**Comment by MalcolmSpencer** [comment]
Your definitions are correct.

The problem seems to be that your current piece definitions only allow numeric characters where as the 1939 register references has a character on the end.

**Comment by ShammyLevva** [comment]
In process of adding this for v6.1.0.0 do you have a GEDCOM snippet with some example references I can test the new code on please?

**Comment by MalcolmSpencer** [comment]
Hi,

 

GEDCOM snippet attached

 

 

Thanks,

 

Malcolm.

**Comment by ShammyLevva** [comment]
Implemented in v6.1.0.0
