### ISSUE TITLE
Census Ref Formats

### ISSUE THREAD

**Issue by mgcope** [ShammyLevva/FTAnalyzer#90]
Using v7.3.5.0 and Lost Cousins tab.
**a**) In Potential Uploads I'm getting 1841 references where the Book is not recognised.
Example:
Piece: 797, Book: see census image (stamped on the census page after the piece number), Folio: 6, Page: 5
1 CENS 
2 DATE 1841
2 SOUR @S12@
3 PAGE HO107/797/10 f6 p5

**b**) In Invalid Census Refs I'm having problems with 1911 references not being recognised.
Example
Unknown Census Ref: RG14/17131 SN117 51 Catherines Cross, Darlaston, Staffordshire. Henry Wilkes Cope & family.
1 CENS 
2 DATE 1911
2 SOUR @S35@
3 PAGE RG14/17131 SN117
3 NOTE 51 Catherines Cross, Darlaston, Staffordshire. Henry Wilkes Cope & family.

Is it possible to accommodate these formats?
Thanks,
Martin Cope

**Comment by ShammyLevva** [comment]
Should be possible yes. In the first case is the book number 10 ie after the piece reference?

In second it’s piece 17131 Schedule 117 I take it?

**Comment by ShammyLevva** [comment]
Fixed for next version.
