### ISSUE TITLE
[BUG] Invalid 1841 Book reference decodes

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#91]
Version Number 7.3.5.1

**Describe the bug**
Decode result is:
Piece: 141, Book: see census image (stamped on the census page after the piece number), Folio: 19, Page: 2

**To Reproduce**
GEDCOM detail … 

Example 1:  … note there are two references, the first one, whilst the info is there, is perhaps difficult to decode. The second one (near end) has a full census reference in a readily digestable form (and should work using EW_CENSUS_1841_51_PATTERN2 if the labels are adjusted (to remove 'number') as I understand you do. 

1 EVEN Leeds Town, Crowan, Helston, Cornwall
2 TYPE Census 1841-Witness
2 DATE 1841
2 PLAC , Helston, Cornwall, England
2 NOTE Role: Witness
3 CONT
2 SOUR @S46@
3 PAGE Leeds Town, Crowan, Helston, Cornwall, England, folio 19, p
4 CONC age 2, John Jenkin; digital images, \i FindMyPast.co.uk\i
4 CONC 0  (https://search.findmypast.co.uk/search-world-Records/18
4 CONC 41-england-wales-and-scotland-census : accessed 5 Oct 2015)
4 CONC ; citing PRO HO/107/141/6
3 QUAY 3
3 DATA
4 TEXT
5 CONT First name(s) Last name Gender Age Birth year Birth place
5 CONT John Jenkin Male 30 1811 -
5 CONT Ann Jenkin Female 25 1816 Cornwall, England
5 CONT John Jenkin Male 7 1834 Cornwall, England
5 CONT Edward Jenkin Male 5 1836 Cornwall, England
5 CONT Elizabeth Jenkin Female 4 1837 Cornwall, England
5 CONT Mary Jenkin Female 3 1838 Cornwall, England
5 CONT William Jenkin Male 1 1840 Cornwall, England
5 CONT
5 CONT Street Leeds Town
5 CONT Parish or township Crowan
5 CONT City or borough -
5 CONT Town -
5 CONT County Cornwall
5 CONT Country England
5 CONT Registration district Helston
5 CONT Archive reference HO107
5 CONT Piece number 141
5 CONT Book number 6
5 CONT Folio number 19
5 CONT Page number 2
5 CONT Record set 1841 England, Wales & Scotland Census
5 CONT Category Census, land & surveys
5 CONT Subcategory Census
5 CONT Collections from Great Britain
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\John Julian 1811 - Census 1841.jpg
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO

Example 2: … note there are three references - two should be readily decodable (I am sure they did in an earlier version??) 

1 EVEN Trevarrack, Uny Lelant
2 TYPE Census 1841-Household Member
2 DATE 1841
2 PLAC , Penzance, Cornwall, England
2 NOTE Role: Household Member
3 CONT
3 CONT «b»«i»First name(s)    Last name    Sex    Age    Birth yea
3 CONC r    Birth place
3 CONT Richard    Hocking    Male    40    1801    Cornwall, Engla
3 CONC nd
3 CONT «/b»Fanny    Hocking    Female    30    1811    Cornwall, E
3 CONC ngland
3 CONT Edwin    Hocking    Male    13    1828    Cornwall, Englan
3 CONC d
3 CONT Richard    Hocking    Male    10    1831    Cornwall, Engla
3 CONC nd
3 CONT William    Hocking    Male    8    1833    Cornwall, Englan
3 CONC d
3 CONT Mary Jane    Hocking    Female    6    1835    Cornwall, En
3 CONC gland
3 CONT Elizabeth    Hocking    Female    4    1837    Cornwall, En
3 CONC gland
3 CONT Edmond    Hocking    Male    1    1840    Cornwall, Englan
3 CONC d
3 CONT
3 CONT «b»House name   «/b»-
3 CONT «b»House number   «/b»-
3 CONT «b»Street   «/b»Trevarrack
3 CONT «b»Parish or township   «/b»Uny Lelant
3 CONT «b»Town   «/b»-
3 CONT «b»City or borough   «/b»St Ives
3 CONT «b»Registration district   «/b»Penzance
3 CONT «b»County   «/b»Cornwall
3 CONT «b»Country   «/b»England
3 CONT «b»Occupation   «/b»-
3 CONT «b»Family member first name(s)   «/b»Elizabeth, Richard, Ed
3 CONC win, Edmond, Mary, Wm, Fanny
3 CONT «b»Family member last name   «/b»Hocking
3 CONT «b»Archive reference   «/b»HO107
3 CONT «b»Piece number   «/b»142
3 CONT «b»Book number   «/b»10
3 CONT «b»Folio number   «/b»51
3 CONT «b»Page number   «/b»1
3 CONT «/i»
2 SOUR @S46@
3 PAGE Uny Lelant, Penzance, Cornwall, folio 51, page 1, Richard H
4 CONC ocking; digital images, \i FindMyPast.co.uk\i0  (https://se
4 CONC arch.findmypast.co.uk/search-world-Records/1841-england-wal
4 CONC es-and-scotland-census : accessed 14 Aug 2018); citing PR
4 CONC O HO/107/142
3 QUAY 3
3 DATA
4 TEXT
5 CONT First name(s)    Last name    Sex    Age    Birth year    B
5 CONC irth place
5 CONT Richard    Hocking    Male    40    1801    Cornwall, Engla
5 CONC nd
5 CONT Fanny    Hocking    Female    30    1811    Cornwall, Engla
5 CONC nd
5 CONT Edwin    Hocking    Male    13    1828    Cornwall, Englan
5 CONC d
5 CONT Richard    Hocking    Male    10    1831    Cornwall, Engla
5 CONC nd
5 CONT William    Hocking    Male    8    1833    Cornwall, Englan
5 CONC d
5 CONT Mary Jane    Hocking    Female    6    1835    Cornwall, En
5 CONC gland
5 CONT Elizabeth    Hocking    Female    4    1837    Cornwall, En
5 CONC gland
5 CONT Edmond    Hocking    Male    1    1840    Cornwall, Englan
5 CONC d
5 CONT
5 CONT House name   -
5 CONT House number   -
5 CONT Street   Trevarrack
5 CONT Parish or township   Uny Lelant
5 CONT Town   -
5 CONT City or borough   St Ives
5 CONT Registration district   Penzance
5 CONT County   Cornwall
5 CONT Country   England
5 CONT Occupation   -
5 CONT Family member first name(s)   Elizabeth, Richard, Edwin, Ed
5 CONC mond, Mary, Wm, Fanny
5 CONT Family member last name   Hocking
5 CONT Archive reference   HO107
5 CONT Piece number   142
5 CONT Book number   10
5 CONT Folio number   51
5 CONT Page number   1
5 CONT Record set   1841 England, Wales & Scotland Censu
5 CONC s
5 CONT Category   Census, land & surveys
5 CONT Subcategory   Census
5 CONT Collections from   Great Britain, England
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\Richard Hocking 1802 - Census 1841.jpg
4 _DATE 1802
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO

**Comment by ShammyLevva** [comment]
Example 1 

3 PAGE Leeds Town, Crowan, Helston, Cornwall, England, folio 19, p
4 CONC age 2, John Jenkin; digital images, \i FindMyPast.co.uk\i
4 CONC 0 (https://search.findmypast.co.uk/search-world-Records/18
4 CONC 41-england-wales-and-scotland-census : accessed 5 Oct 2015)
4 CONC ; citing PRO HO/107/141/6

is matching EW_CENSUS_1841_51_PATTERN6 and getting no book number (as there doesn't appear to be one)
The subsequent text which gets cleaned up to 

Archive reference HO107 Piece 142 Book 10 Folio 51 Page 1 Record set 1841 England Wales & Scotland Census 

Is indeed getting matched with EW_CENSUS_1841_51_PATTERN2 was erroneously setting the Book as an ED not a book thus the book was missing and failing.

Fixed for next version.
