### ISSUE TITLE
[BUG] 1841 Census - Multiple references exist but not decoding the valid one

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#92]
Version Number 7.3.5.1

**Describe the bug**
Multiple versions of census reference exist, but not picking up a valid one (likely related to issue 91??)

**To Reproduce**
GEDCOM detail:  (reference details **_highlighted_**)

1 EVEN Ulleskelf
2 TYPE Census 1841
2 DATE 1841
2 PLAC , Tadcaster, Yorkshire (North), England
2 NOTE The household comprised:
3 CONT   Joshua Hey Male 35 1806 Yorkshire, England
3 CONT   Mary Hey Female 35 1806 Yorkshire, England
3 CONT   Isabella Hey Female 11 1830 Yorkshire, England
3 CONT   Joshua Hey Male 6 1835 Yorkshire, England
3 CONT   Barbara Hey Female 3 1838 Yorkshire, England
3 CONT   Joanah Hey Female 2 1839 Yorkshire, England
3 CONT   Eliz Hey Female 1 1840 Yorkshire, England
3 CONT
2 SOUR @S46@
3 PAGE Ulleskelf, Tadcaster, **_folio 9, Book 8, page 12_,** Joshua He
4 CONC y and family; digital images, \i FindMyPast.co.uk\i0  (http
4 CONC s://search.findmypast.co.uk/search-world-Records/1841-engla
4 CONC nd-wales-and-scotland-census : accessed 12 Jun 2017); citin
4 CONC g **_PRO HO/107/1282_**
3 QUAY 3
3 NOTE No media attached
3 DATA
4 TEXT
5 CONT First name(s) Last name Gender Age Birth year Birth place
5 CONT Joshua Hey Male 35 1806 Yorkshire, England
5 CONT Mary Hey Female 35 1806 Yorkshire, England
5 CONT Isabella Hey Female 11 1830 Yorkshire, England
5 CONT Joshua Hey Male 6 1835 Yorkshire, England
5 CONT Barbara Hey Female 3 1838 Yorkshire, England
5 CONT Joanah Hey Female 2 1839 Yorkshire, England
5 CONT Eliz Hey Female 1 1840 Yorkshire, England
5 CONT
5 CONT Street Ulleskelf
5 CONT Parish or township Kirkby Wharfe
5 CONT City or borough -
5 CONT Town Ulleskelf
5 CONT County Yorkshire, Yorkshire (West Riding)
5 CONT Country England
5 CONT Registration district Tadcaster
**_5 CONT Archive reference HO107
5 CONT Piece number 1282
5 CONT Book number 8
5 CONT Folio number 9
5 CONT Page number 12_**
5 CONT Record set 1841 England, Wales & Scotland Census
5 CONT Category Census, land & surveys
5 CONT Subcategory Census
5 CONT Collections from Great Britain

Steps to reproduce the behaviour:
1. include event detail into a skeleton person GEDCOM
2. load into FTA
3. check result on Census Tab / UK Census 1841 / Show entered on Census

**Expected behaviour**
Decoded as a valid reference:
Piece: 1282, Book: 8, Folio: 9, Page: 12

**Comment by ShammyLevva** [comment]
Is this two different issues and two different patterns for two different years? I need to focus on one issue and close it please. It gets very confusing to know if it's all dealt with if multiple issues are in the same issue.

**Comment by ShammyLevva** [comment]
Right Issue 1 of 2:

The issue here was the format was Piece Folio Book Page rather than the others which is Piece Book Folio Page. YAY for FindMyPast consistency!! Format added as EW_CENSUS_1841_51_PATTERN2A the lower text should be the same issue as the prior issue ie: ED rather than book.

**Comment by ShammyLevva** [comment]
Issue 2 of 2
This was a new pattern required. Part 2 of issue 2 again ED rather than book.
