### ISSUE TITLE
[BUG] Scottish Census References

### ISSUE THREAD

**Issue by mgcope** [ShammyLevva/FTAnalyzer#94]
Using V7.3.5.1
I'm finding that FTA is interpreting my Peterhead references as Bressay.
Example:
1 CENS 
2 DATE 1881
2 PLAC Peterhead, Aberdeenshire
2 SOUR @S7@
3 PAGE 231-1/10 page 20  
Is interpreted as Parish: Bressay, RD: 1, ED: 10, Page: 20

The Peterhead code is given as 232-1 in the LDS transcription on ScotlandsPeople and 232/1 in their own transcription. Both formats give the same result.
After a bit of investigation I wonder if the problem might lie with the code being compound and not a simple number.  Peterhead is not unique in this respect - there are quite a few other such codes. 

Or have I simply not found the right format for the reference?

best regards,
Martin Cope

**Comment by ShammyLevva** [comment]
Ah it was capturing the 1 as the reference and not the 231-1 since RD1 is Bressay that was the bug.

Fixed.
