### ISSUE TITLE
[BUG] Not corrrectly decoding 1841 information

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#95]
Related to #91 - couldn't readily figure out how to reopen it

Version Number 7.3.6.0

Decode result is:
Piece: 1281, Book: see census image (stamped on the census page after the piece number), Folio: 6, Page: 6

**To Reproduce**
GEDCOM detail (references **highlighted**) …

1 EVEN Frystone
2 TYPE Census 1841
2 DATE 1841
2 PLAC , Monk Fryston, Yorkshire (North), England
2 NOTE
3 CONT «b»«i»First name(s)    Last name    Sex    Age    Birth yea
3 CONC r    Birth place
3 CONT Joseph    Long    Male    40    1801    Yorkshire, Englan
3 CONC d
3 CONT «/b»Mary    Long    Female    35    1806    Yorkshire, Engl
3 CONC and
3 CONT William    Long    Male    15    1826    Yorkshire, Englan
3 CONC d
3 CONT Elizabeth    Long    Female    12    1829    Yorkshire, Eng
3 CONC land
3 CONT Joseph    Long    Male    6    1835    Yorkshire, England
3 CONT Mary    Long    Female    2    1839    Yorkshire, England
3 CONT John    Wilson    Male    15    1826    Yorkshire, Englan
3 CONC d
3 CONT «b»  «/b»
3 CONT «b»House name   «/b»-
3 CONT «b»House number   «/b»-
3 CONT «b»Street   «/b»Frystone
3 CONT «b»Parish or township   «/b»Monk Fryston
3 CONT «b»Town   «/b»Monk Fryston
3 CONT «b»City or borough   «/b»-
3 CONT «b»Registration district   «/b»Pontefract
3 CONT «b»County   «/b»Yorkshire, Yorkshire (West Riding
3 CONC )
3 CONT «b»Country   «/b»England
3 CONT «b»Occupation   «/b»-
3 CONT «b»Family member first name(s)   «/b»John, Mary, Elizabeth
3 CONC , William, Joseph
3 CONT «b»Family member last name   «/b»Wilson, Long
**3 CONT «b»Archive reference   «/b»HO107
3 CONT «b»Piece number   «/b»1281
3 CONT «b»Book number   «/b»8
3 CONT «b»Folio number   «/b»6
3 CONT «b»Page number   «/b»6**
3 CONT «b»Record set   «/b»1841 England, Wales & Scotland Censu
3 CONC s
3 CONT «b»Category   «/b»Census, land & surveys
3 CONT «b»Subcategory   «/b»Census
3 CONT «b»Collections from   «/b»Great Britain, Englan
3 CONC d
3 CONT
2 SOUR @S46@
3 PAGE Monk Fryston, folio 6, page 6, Joseph Long; digital images
4 CONC , \i FindMyPast.co.uk\i0  (https://search.findmypast.co.uk/
4 CONC search-world-Records/1841-england-wales-and-scotland-censu
4 CONC s : accessed 13 Jan 2019); citing PRO HO/107/1281
3 QUAY 2
3 DATA
4 TEXT
5 CONT First name(s)    Last name    Sex    Age    Birth year    B
5 CONC irth place
5 CONT Joseph    Long    Male    40    1801    Yorkshire, Englan
5 CONC d
5 CONT Mary    Long    Female    35    1806    Yorkshire, Englan
5 CONC d
5 CONT William    Long    Male    15    1826    Yorkshire, Englan
5 CONC d
5 CONT Elizabeth    Long    Female    12    1829    Yorkshire, Eng
5 CONC land
5 CONT Joseph    Long    Male    6    1835    Yorkshire, England
5 CONT Mary    Long    Female    2    1839    Yorkshire, England
5 CONT John    Wilson    Male    15    1826    Yorkshire, Englan
5 CONC d
5 CONT
5 CONT House name   -
5 CONT House number   -
5 CONT Street   Frystone
5 CONT Parish or township   Monk Fryston
5 CONT Town   Monk Fryston
5 CONT City or borough   -
5 CONT Registration district   Pontefract
5 CONT County   Yorkshire, Yorkshire (West Riding)
5 CONT Country   England
5 CONT Occupation   -
5 CONT Family member first name(s)   John, Mary, Elizabeth, Willia
5 CONC m, Joseph
5 CONT Family member last name   Wilson, Long
5 CONT Archive reference   HO107
**5 CONT Piece number   1281
5 CONT Book number   8
5 CONT Folio number   6
5 CONT Page number   6**
5 CONT Record set   1841 England, Wales & Scotland Censu
5 CONC s
5 CONT Category   Census, land & surveys
5 CONT Subcategory   Census
5 CONT Collections from   Great Britain, England
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\Joseph Long 1796 - Census 1841.jpg
4 TITL 1841 Census entry Joseph Long and family
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO

**Steps to reproduce the behaviour:**
- include event detail into a skeleton person GEDCOM
- load into FTA
- check result on Census Tab / UK Census 1841 / Show entered on Census

**Expected behaviour**
Decoded as a valid reference:
Piece: 1281, Book: 8, Folio: 6, Page: 6

**Comment by bmurcutt** [comment]
Should match EW_CENSUS_1841_51_PATTERN2?
(I gather that the link to the CensusReference.cs script you sent me originally [https://github.com/S...L.../FTAnalyzer.S.../blob/initial/FTAnalyzer.S.../Core/CensusReference.cs] isn't to the current 'prod' version - as updated patterns do not appear in it now? - eg your reference to a new EW_CENSUS_1841_51_PATTERN6A).  I'm OK with that - just checking :)

**Comment by ShammyLevva** [comment]
The core code is at https://github.com/ShammyLevva/FTAnalyzer.Shared/tree/initial/FTAnalyzer.Shared/Core

With the CensusReference.cs module being there. Note the released version will be on the master branch if I'm doing a big new feature then I tend to use the develop branch and commit to master once released.

I tried with v7.3.6 to tackle the bulk of the previous issues but was fairly sure I'd have missed some. Hence I suspected the best course of action was to release what had been fixed and see what remained.

**Comment by ShammyLevva** [comment]
The initial part of the text is parsed as:

Monk Fryston folio 6 page 6 Joseph Long digital images FindMyPast co uk 0 https //search findmypast co uk/search-world-Records/1841-england-wales-and-scotland-census accessed 13 Jan 2019 citing PRO HO/107/1281

which contains a valid but incomplete reference without a book number matching on EW_CENSUS_1841_51_PATTERN6.

What appears to be the issue is that since it found a census reference **ATTACHED TO THE CENSUS FACT** it stopped looking at the rest of the text. I suspect what I need to do is to check is it a valid complete reference if so that's fine if, as in this case it's not a complete reference then continue looking at rest of text for another bite at the cherry.

However what it won't ever do is get two possibly conflicting references from the one fact. If a CENSUS fact has two conflicting census references then there's an error.

**Comment by ShammyLevva** [comment]
Right it now keeps going if it has only got an incomplete status checking to see if any better references exist.

**Comment by ShammyLevva** [comment]
Ok tested and working now.

**Comment by bmurcutt** [comment]
Thanks Alexander.

 

FYI – I can only see ‘Initial’ and ‘Develop’ branches – no ‘Master’.

 

Probably an access issue.  Don’t worry about it – I certainly don’t want access if there is any chance I could unintentionally change anything!!

 

Develop has (at least some of) the additional patterns you have mentioned 😊

 

Regards,

 

Brian

**Comment by ShammyLevva** [comment]
DOH.

 

In the shared folder it called it initial rather than master. As I inadvertently deleted master at one point and never renamed it back 😊

 

In the windows project code folder and the mac project code folder the master branch is called master. In the shared code folder the master branch is called initial – not confusing at all honest.

**Comment by bmurcutt** [comment]
Interesting …

 

Because ‘initial’ has the (presumably) older version …

 



 

as against ‘develop’ …

 



 

B
