### ISSUE TITLE
[BUG] Not corrrectly decoding 1841 information (similar to #95)

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#96]
Version Number 7.3.6.0

**Decode result is:**
Unknown Census Ref: digital images, \i FindMyPast.co.uk\i0  (https://search.findmypast.co.uk/search-world-Records/1841-england-wales-and-scotland-census); citing PRO HO/107 Herland

**To Reproduce**
GEDCOM detail (reference **highlighted**) …

1 EVEN Herland
2 TYPE Census 1841
2 DATE 1841
2 PLAC , Breage, Cornwall, England
2 NOTE
3 CONT «b»«i»First name(s)    Last name    Sex    Age    Birth yea
3 CONC r    Birth place
3 CONT William    Hocking    Male    35    1806    Cornwall, Engla
3 CONC nd
3 CONT «/b»Grace    Hocking    Female    35    1806    Cornwall, E
3 CONC ngland
3 CONT William    Hocking    Male    0    1841    Cornwall, Englan
3 CONC d
3 CONT
3 CONT «b»House name   «/b»-
3 CONT «b»House number   «/b»-
3 CONT «b»Street   «/b»Herland
3 CONT «b»Parish or township   «/b»Breage
3 CONT «b»Town   «/b»-
3 CONT «b»City or borough   «/b»-
3 CONT «b»Registration district   «/b»Helston
3 CONT «b»County   «/b»Cornwall
3 CONT «b»Country   «/b»England
3 CONT «b»Occupation   «/b»-
3 CONT «b»Family member first name(s)   «/b»Grace, Willia
3 CONC m
3 CONT «b»Family member last name   «/b»Hocking
**3 CONT «b»Archive reference   «/b»HO107
3 CONT «b»Piece number   «/b»136
3 CONT «b»Book number   «/b»3
3 CONT «b»Folio number   «/b»56
3 CONT «b»Page number   «/b»3**
3 CONT «/i»
2 SOUR @S46@
3 PAGE digital images, \i FindMyPast.co.uk\i0  (https://search.fin
4 CONC dmypast.co.uk/search-world-Records/1841-england-wales-and-s
4 CONC cotland-census); citing PRO HO/107
3 QUAY 3
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\William Hockin 1804 - Census 1841.jpg
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO

**Steps to reproduce the behaviour:**
- include event detail into a skeleton person GEDCOM
- load into FTA
- check result on Census Tab / UK Census 1841 / Show entered on Census

**Expected behaviour**
Decoded as a valid reference:
Piece: 136, Book: 3, Folio: 56, Page: 3

**Comment by ShammyLevva** [comment]
Fixed via fix for #95.
