### ISSUE TITLE
[BUG] Census / Reference report mismatches - Multiple 'Founds'

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#98]
7.3.7.0 (beta)

Filters:  1841 Census, default types (direct, blood, married to blood, descendants), exclude indivs over 90

Not Found on Census:	595 (563 indiv)
Found on Census: 	        184 (169 indiv)

Good:			146
Incomplete:		  27
Unrecognized:		    0
Missing:		            3
		          	------
			          176 (discrepancy +7)

Multiple entry on ‘Found’ in Census

1 EVEN Leeds Town, Crowan, Helston, Cornwall
2 TYPE Census 1841-Witness
2 DATE 1841
2 PLAC , Helston, Cornwall, England
2 NOTE Role: Witness
3 CONT
2 SOUR @S46@
3 PAGE Leeds Town, Crowan, Helston, Cornwall, England, folio 19, p
4 CONC age 2, John Jenkin; digital images, \i FindMyPast.co.uk\i
4 CONC 0  (https://search.findmypast.co.uk/search-world-Records/18
4 CONC 41-england-wales-and-scotland-census : accessed 5 Oct 2015)
4 CONC ; citing PRO HO/107/141/6
3 QUAY 3
3 DATA
4 TEXT
5 CONT First name(s) Last name Gender Age Birth year Birth place
5 CONT John Jenkin Male 30 1811 -
5 CONT Ann Jenkin Female 25 1816 Cornwall, England
5 CONT John Jenkin Male 7 1834 Cornwall, England
5 CONT Edward Jenkin Male 5 1836 Cornwall, England
5 CONT Elizabeth Jenkin Female 4 1837 Cornwall, England
5 CONT Mary Jenkin Female 3 1838 Cornwall, England
5 CONT William Jenkin Male 1 1840 Cornwall, England
5 CONT
5 CONT Street Leeds Town
5 CONT Parish or township Crowan
5 CONT City or borough -
5 CONT Town -
5 CONT County Cornwall
5 CONT Country England
5 CONT Registration district Helston
5 CONT Archive reference HO107
5 CONT Piece number 141
5 CONT Book number 6
5 CONT Folio number 19
5 CONT Page number 2
5 CONT Record set 1841 England, Wales & Scotland Census
5 CONT Category Census, land & surveys
5 CONT Subcategory Census
5 CONT Collections from Great Britain
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\John Julian 1811 - Census 1841.jpg
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO

This person (Mary) was only 3 years old (as at 1841), but there are entries (in the Found in Census report) for her both as a ‘child’ and as a ‘wife’:

  | F0001 | I0006 | Helston, Cornwall, England | Mary Ann Julian | 3 |   | 27 APR 1838 | Church Town, St Just, Cornwall, England | AFT 1880 | Australia | Child | Direct Ancestor | 2nd great grandmother | Piece: 141, Book: see census image (stamped on   the census page after the piece number), Folio: 19, Page: 2 | UK Census 1841 | 29

  | F0013 | I0006 | Helston, Cornwall, England | Mary Ann Raper  (Julian) | 3 |   | 27 APR 1838 | Church Town, St Just, Cornwall, England | AFT 1880 | Australia | Wife | Direct Ancestor | 2nd great grandmother | Piece: 141, Book: see census image (stamped on   the census page after the piece number), Folio: 19, Page: 2 | UK Census 1841 | 29

Note that (arguably) both references in the GEDCOM are valid and the same (if you can interpret ‘… folio 19, page 2, … PRO HO/107/141/6’ the same as ‘Archive reference HO107 Piece number 141 Book number 6 Folio number 19 Page number 2’ – the earlier one appears to fail though (1841-51 PATTERN6) because the words folio and page are all lower case!

Also note that Book is not set correctly.  And that the individual appears once only in the ‘Good’ reference report.

**Version Number problem appears in**
You MUST provide this information so I know what the scope of the problem is. Bugs without this info are unlikely to be addressed. 
NB. at no time ever in the history of the app has there been a version called “latest” they all have a version number. eg: v7.2.2.0

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ShammyLevva** [comment]
"Note that (arguably) both references in the GEDCOM are valid and the same (if you can interpret ‘… folio 19, page 2, … PRO HO/107/141/6’ the same as ‘Archive reference HO107 Piece number 141 Book number 6 Folio number 19 Page number 2’ – the earlier one appears to fail though (1841-51 PATTERN6) because the words folio and page are all lower case!"

All patterns are case insensitive so that shouldn't be an issue.

**Comment by ShammyLevva** [comment]
As per other report the Census results is based on Census Families NOT on individuals this is CORE to the way this report works I cannot possibly change this without fundamentally re-writing how this works and that's not on my radar.

Note the totals will show unique individuals as well as a row count. For comparison purposes it is the unique individuals that are at issue. 

Without the FAMILY record part of the GEDCOM I cannot replicate this issue sorry.

**Comment by bmurcutt** [comment]
I forgot the case sensitivity thing - I put it through Regex but it doesn't (by default at least) do that :)
I'll see if I can create a small GEDCOM for test purposes later today.

**Comment by ShammyLevva** [comment]
![image](https://user-images.githubusercontent.com/29687786/52152803-a7cd8480-266f-11e9-9d82-1e1fc578911d.png)
check the button top right of the regex line that's the options you can turn on

**Comment by bmurcutt** [comment]
Hi Alexander.

 

A GEDCOM attached.  Person of interest is @i6@ Mary Ann Julian

 

Note when you look at the Census and Reference reports, you will need to tick the ‘Related by Marriage’ filter option.

 

I think the essence of #98 has already been dealt with anyway - Multiple entries in ‘Found on Census’ – Mary will appear (and will continue to) as both a wife and a child (in separate family units).

 

Of remaining interest though (also noted in #98) is:

 

The reference:

3 PAGE Leeds Town, Crowan, Helston, Cornwall, England, folio 19, page 2, John Jen

4 CONC kin; digital images, \i FindMyPast.co.uk\i0  (https://search.findmypast.co

4 CONC .uk/search-world-Records/1841-england-wales-and-scotland-census : accesse

4 CONC d 5 Oct 2015); citing PRO HO/107/141/6

Appears (to me) to fail (EW_CENSUS_1841_51_PATTERN6) because of the comma after ‘folio 19’ (after I get the regex options hopefully correct for case insensitivity??)

 

It does catch (further down the fact - EW_CENSUS_1841_51_PATTERN2) another reference:

5 CONT Archive reference HO107
5 CONT Piece number 141
5 CONT Book number 6
5 CONT Folio number 19
5 CONT Page number 2

 

You will note though that the ‘Book’ attribute has not been set correctly – but are all flagged as ‘good’ references.

 

Something is amiss on that front 😊

 

Regards,

 

Brian

**Comment by bmurcutt** [comment]
The essence of this issue has been resolved.  The side issue of the invalid reference is covered now in #117
