### ISSUE TITLE
[BUG] Census / Reference report mismatches - Multiple 'References'

### ISSUE THREAD

**Issue by bmurcutt** [ShammyLevva/FTAnalyzer#99]
7.3.7.0 (beta)

Appearing on multiple reference reports

**1 EVEN St Dominic Street
2 TYPE Census 1841-Witness**
2 DATE 1841
2 PLAC , Kenwyn, Cornwall, England
2 NOTE Role: Witness
3 CONT
3 CONT Archive reference HO107
3 CONT Piece number 147
3 CONT Book number 15
3 CONT Folio number 17
3 CONT Page number 26
3 CONT Record set 1841 England, Wales & Scotland Census
3 CONT
3 CONT Eliza Crago Female 29 1812 Cornwall, England
3 CONT May Crago Female 5 1836 Cornwall, England
3 CONT Emily Crago Female 3 1838 Cornwall, England
3 CONT Thos Crago Male 1 1840 Cornwall, England
3 CONT
2 SOUR @S46@
3 PAGE Truro, Cornwall, England, folio 17, page 26, Eliza Crago; d
4 CONC igital images, \i FindMyPast.co.uk\i0  (https://search.find
4 CONC mypast.co.uk/search-world-Records/1841-england-wales-and-sc
4 CONC otland-census : accessed 23 Oct 2010); citing PRO HO/107/147
3 QUAY 3
3 DATA
4 TEXT
5 CONT First name(s) Last name Gender Age Birth year Birth place
5 CONT Eliza Crago Female 29 1812 Cornwall, England
5 CONT May Crago Female 5 1836 Cornwall, England
5 CONT Emily Crago Female 3 1838 Cornwall, England
5 CONT Thos Crago Male 1 1840 Cornwall, England
5 CONT
5 CONT Street St Dominic Sreet
5 CONT Parish or township Kenwyn
5 CONT City or borough Truro
5 CONT Town -
5 CONT County Cornwall
5 CONT Country England
5 CONT Registration district Truro
5 CONT Archive reference HO107
5 CONT Piece number 147
5 CONT Book number 15
5 CONT Folio number 17
5 CONT Page number 26
5 CONT Record set 1841 England, Wales & Scotland Census
5 CONT Category Census, land & surveys
5 CONT Subcategory Census
5 CONT Collections from Great Britain
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\Eliza Williams 1813 - Census 1841.jpg
4 TITL 1841 Census entry Eliza Crago and family
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO
**1 EVEN
2 TYPE Census 1841**
2 DATE 1841
2 PLAC , Truro, Cornwall, England
1 _UID C6734D95EB1A4C378720B193F07BD667364E
1 CHAN
2 DATE 29 Mar 2016
3 TIME 16:17

The first event/fact contains a combination of valid and incomplete census references.  The valid reference/s are detected.
The second event/fact has missing references.

The individual appears only once in the ‘Found on Census’ report.

F0287 | I0662 | Kenwyn, Cornwall, England | Mary Jane Crago | 5 |   | 5 APR 1836 | Truro, Cornwall, England | ABT AUG 1842 | Truro, Cornwall, England | Child | Blood Relation | 2nd great grandaunt | Piece: 147, Book: 15, Folio: 17,   Page: 26 | UK Census 1841 | 0 |  

The valid census reference appears on the ‘Good’ reference report.

  | I0662 | Mary Jane | Crago | Census | 1841 | Crago | Blood Relation | 2nd great grandaunt | 5 APR 1836 | Kenwyn, Cornwall, England | St Dominic Street | 1841 | Piece: 147, Book: 15, Folio: 17,   Page: 26 | 4 to 5 | TRUE | 1841 England, Wales & Scotland   Census. Digital images.

The missing census fact/reference appears on the ‘Missing’ reference report.

  | I0662 | Mary Jane | Crago | Census | 1841 | Crago | Blood Relation | 2nd great grandaunt | 5 APR 1836 | Truro, Cornwall, England | 1841 |   | 4 to 5 | FALSE |  

In this case there is a data error.  However, how the entries are handled and appear in the reports is perhaps a matter for consideration.
-	If you have mismatching (complete) references within a fact, you will likely (as discussed earlier) handle as an error.  How should the entries appear in the ‘Found in Census’, and in the ‘Reference’ reports?
-	If you have mismatching (at least one complete) references across separate facts, is this legitimate or an error?  
	[ I would suggest this is legitimate, but there should be separate entries on the ‘Found in Census’ report, and handled in the reference reports appropriately.  This would keep the counts in alignment.
	Alternative, of course, is to understand that this could be a cause for an inconsistency in the counts  – but how to readily find it? ]    
-	If you have matching multiple facts with references, should there be multiple (and matching equivalent) entries across the reports?

Like many things, 10% of the cases can take 90% of the effort to manage.  At some point you have to decide what is important and what is not.  So long as you can understand (and explain it!), you don’t have to actually ‘fix’ it!!

Here is an example where there are multiple 1841 facts with references to assist in considerations … it generated one 'Found in Census' record, and two 'Good' references

**1 EVEN
2 TYPE Census 1841**
2 DATE 1841
2 PLAC , Pontefract, Yorkshire (West), England
2 SOUR @S46@
**3 PAGE Pontefract, Yorkshire, England, folio 15/34, page 22, Mar
4 CONC y Long; digital images, \i FindMyPast.co.uk\i0  (https://se
4 CONC arch.findmypast.co.uk/search-world-Records/1841-england-wal
4 CONC es-and-scotland-census : accessed 5 Jan 2011); citing PRO H
4 CONC O/107/1310**
3 QUAY 2
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\Joseph Long 1796 - Census 1841.jpg
4 TITL 1841 Census entry Joseph Long and family
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO
**1 EVEN Frystone
2 TYPE Census 1841-Household Member**
2 DATE 1841
2 PLAC , Monk Fryston, Yorkshire (North), England
2 NOTE Role: Household Member
3 CONT
3 CONT «b»«i»First name(s)    Last name    Sex    Age    Birth yea
3 CONC r    Birth place
3 CONT Joseph    Long    Male    40    1801    Yorkshire, Englan
3 CONC d
3 CONT «/b»Mary    Long    Female    35    1806    Yorkshire, Engl
3 CONC and
3 CONT William    Long    Male    15    1826    Yorkshire, Englan
3 CONC d
3 CONT Elizabeth    Long    Female    12    1829    Yorkshire, Eng
3 CONC land
3 CONT Joseph    Long    Male    6    1835    Yorkshire, England
3 CONT Mary    Long    Female    2    1839    Yorkshire, England
3 CONT John    Wilson    Male    15    1826    Yorkshire, Englan
3 CONC d
3 CONT «b»  «/b»
3 CONT «b»House name   «/b»-
3 CONT «b»House number   «/b»-
3 CONT «b»Street   «/b»Frystone
3 CONT «b»Parish or township   «/b»Monk Fryston
3 CONT «b»Town   «/b»Monk Fryston
3 CONT «b»City or borough   «/b»-
3 CONT «b»Registration district   «/b»Pontefract
3 CONT «b»County   «/b»Yorkshire, Yorkshire (West Riding
3 CONC )
3 CONT «b»Country   «/b»England
3 CONT «b»Occupation   «/b»-
3 CONT «b»Family member first name(s)   «/b»John, Mary, Elizabeth
3 CONC , William, Joseph
3 CONT «b»Family member last name   «/b»Wilson, Long
**3 CONT «b»Archive reference   «/b»HO107
3 CONT «b»Piece number   «/b»1281
3 CONT «b»Book number   «/b»8
3 CONT «b»Folio number   «/b»6
3 CONT «b»Page number   «/b»6**
3 CONT «b»Record set   «/b»1841 England, Wales & Scotland Censu
3 CONC s
3 CONT «b»Category   «/b»Census, land & surveys
3 CONT «b»Subcategory   «/b»Census
3 CONT «b»Collections from   «/b»Great Britain, Englan
3 CONC d
3 CONT
2 SOUR @S46@
3 PAGE Monk Fryston, folio 6, page 6, Joseph Long; digital images
4 CONC , \i FindMyPast.co.uk\i0  (https://search.findmypast.co.uk/
4 CONC search-world-Records/1841-england-wales-and-scotland-censu
4 CONC s : accessed 13 Jan 2019); citing PRO HO/107/1281
3 QUAY 2
3 DATA
4 TEXT
5 CONT First name(s)    Last name    Sex    Age    Birth year    B
5 CONC irth place
5 CONT Joseph    Long    Male    40    1801    Yorkshire, Englan
5 CONC d
5 CONT Mary    Long    Female    35    1806    Yorkshire, Englan
5 CONC d
5 CONT William    Long    Male    15    1826    Yorkshire, Englan
5 CONC d
5 CONT Elizabeth    Long    Female    12    1829    Yorkshire, Eng
5 CONC land
5 CONT Joseph    Long    Male    6    1835    Yorkshire, England
5 CONT Mary    Long    Female    2    1839    Yorkshire, England
5 CONT John    Wilson    Male    15    1826    Yorkshire, Englan
5 CONC d
5 CONT
5 CONT House name   -
5 CONT House number   -
5 CONT Street   Frystone
5 CONT Parish or township   Monk Fryston
5 CONT Town   Monk Fryston
5 CONT City or borough   -
5 CONT Registration district   Pontefract
5 CONT County   Yorkshire, Yorkshire (West Riding)
5 CONT Country   England
5 CONT Occupation   -
5 CONT Family member first name(s)   John, Mary, Elizabeth, Willia
5 CONC m, Joseph
5 CONT Family member last name   Wilson, Long
5 CONT Archive reference   HO107
**5 CONT Piece number   1281
5 CONT Book number   8
5 CONT Folio number   6
5 CONT Page number   6**
5 CONT Record set   1841 England, Wales & Scotland Censu
5 CONC s
5 CONT Category   Census, land & surveys
5 CONT Subcategory   Census
5 CONT Collections from   Great Britain, England
3 OBJE
4 FORM jpg
4 FILE C:\Users\BrianM\Documents\Family Tree\Records\Hey records\Joseph Long 1796 - Census 1841.jpg
4 TITL 1841 Census entry Joseph Long and family
4 _DATE 1841
4 _SCBK Y
4 _PRIM Y
4 _TYPE PHOTO

**Comment by ShammyLevva** [comment]
To get to the bottom of this I need to understand are there duplicate Census Facts here? That's going to throw the numbers off as the census report is going to ignore the duplicates whereas the reference count won't as it's counting references not individuals.

Thus what the mismatch MAY be highlighting is duplicate facts. These duplicates sound like they are at the root of the issue?

**Comment by bmurcutt** [comment]
The first GEDCOM extract has two census facts, one has a good reference, one is missing.
The second GEDCOM extract has two census facts, each with a good (but different) reference.

The issue - in relation to consistency of counts across Found in Census and references - was that the individual appeared only once in the 'Found', but twice in the references, therefore making the count reconciliation error.

I gather from your feedback so far on related issues that it is probably behaving as expected - it just means that there are scenarios where the reference counts will not match the counts of Individuals on the 'Found' report.  So long as we understand and are happy with that, all is good methinks!

Happy for this to be closed unless there is something you want to follow up on.

**Comment by bmurcutt** [comment]
Resolved
